### ISSUE TITLE
BR keyboard keys issues

### ISSUE THREAD

**Issue by LuccaPrado** [kwhat/jnativehook#100]
Some keys like ', [, ], ~ and ç

I don't know why, but in layout br this keys are showig as \ and () when detected by lib...

**Comment by kwhat** [comment]
what OS and which version of the library?

**Comment by kwhat** [comment]
Any update to this issue?  Please test the latest snapshot https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by dp-t-rex** [comment]
I have the same problem with my german kayboard. I am using v2.0.3.
Even the keycodes change per key, when i switch between german and US layout (qwerty <-> qwertz).

I wrote my own getKeyText(int i) method as a workaround.

**Comment by kwhat** [comment]
Which key events are incorrect?  Key Typed or Key Up/Down?  Which operating system are you using?

**Comment by dp-t-rex** [comment]
My OS is Windows 10 (all Updates).
When i am printing the KeyCodes to the console in the nativeKeyTiyped method, it is alwys 0 (zero) (german and eglish layout). Printing the KeyCodes in nativeKeyPressed or nativeKeyReleased results in confusing values:
Every normal letter and number as well as ctrl, shift, alt and so on are correct (besides the german umlauts ä, ö, ü, ß).
But i.e. the key to the right of "P" prints KeyCode 39 (semicolon) while using the german layout (it acutally should be Ü) and 26 (opening square bracket) while using the english layout (this is correct (?)).
I am not able to find any regularity or pattern in the way the german keycodes are different:

I hope this can help, and sorry for my english :)

**Comment by kwhat** [comment]
Hi, there is a fix for this potential issue from #170.  A fix should be available in the next release/nightly.  If the issue persists, please let me know.
