### ISSUE TITLE
jnativehook 2.0.3 fails loading with JRE 64bit on Windows 7

### ISSUE THREAD

**Issue by deinhofer** [kwhat/jnativehook#101]
When trying to load jnativehook (calling GlobalScreen.registerNativeHook()), the loading fails with the following exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\mad\AppData\Local\Temp\JNativeHook-2.0.3.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
	at InitGlobalScreen.main(InitGlobalScreen.java:11)

It seems that loading of the native code fails for 64bit.

I have a windows 7 64bit machine and JRE 1.8.0_92

**Comment by kwhat** [comment]
I strongly suspect that you started with 32 bit JRE, and then launched a 64 bit JRE. Delete the DLL and see if that solves your issue.  The extracted binary should prob be versioned by bit width, so leave this bug open and report back.

**Comment by kwhat** [comment]
This should be fixed in the trunk at ee46ae2be687c8cd990327ae9604df60c9aec122

**Comment by deinhofer** [comment]
Yes, deleting the DLL in the user temp directory solved the problem.

Thanks for the fast response and fixing it!! :-)

Do you plan to release a new version soon? Otherwise the workaround 
could be to delete all temporary .dll files before or after starting the 
program.

Thanks in advance!!

Best Regards!

Martin

Am 24.05.2016 um 22:37 schrieb Alex Barker:
>
> I strongly suspect that you started with 32 bit JRE, and then launched 
> a 64 bit JRE. Delete the DLL and see if that solves your issue. The 
> extracted binary should prob be versioned by bit width, so leave this 
> bug open and report back.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/kwhat/jnativehook/issues/101#issuecomment-221383504>
>

-- 
Martin Deinhofer, MSc
Research and Development, International Projects

University of Applied Sciences Technikum Wien
Hoechstaedtplatz 6, 1200 Vienna, Austria, Europe
T: +43 1 333 40 77-297, F: +43 1 333 40 77-99 297
E: martin.deinhofer@technikum-wien.at
I: embsys.technikum-wien.at

**Comment by kwhat** [comment]
Yes, probably a 2.0.4 and 2.1.0 when I get though the bug backlog.  You can work around the problem by implementing your own LibraryLocator or just borrowing the updated version.  See the wiki for instructions.
