### ISSUE TITLE
How to detect mouse movement - not cursor

### ISSUE THREAD

**Issue by dermoritz** [kwhat/jnativehook#102]
I need to detect movement of mouse after (while dragging) cursor reaches screen border. Alternatively i need to set the position of the cursor.

Is this possible with your library?

The use case is dragging a large zoomed in picture. It should be possible to drag/view the complete picture. at the moment dragging stops if cursor reached border of screen.

**Comment by kwhat** [comment]
It should be possible by listening for drag events and posting events to the global screen when your condition is met.

**Comment by kwhat** [comment]
I think what you maybe looking for is relative mouse movement which is outside of the scope of this library.  I may create a raw input hook in the future.
