### ISSUE TITLE
Mouse focus locked in pane

### ISSUE THREAD

**Issue by allesspassig** [kwhat/jnativehook#104]
After using JNativeHook in a project, my mouse got locked into a single pane of my IDE. It could still move outside of the pane, but any key presses or mouse clicks registered only in that pane. To escape, I have to use keyboard shortcuts to switch to another window and back. A similar issue is described [here](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/362359). After some testing, it seems like JNativeHook is the cause.

**Comment by kwhat** [comment]
I will need much more information about this issue.  Are you also on Linux? Which distro at what version?  Gnome or KDE?  Which IDE?  What version of the library? Always the same window? What testing did you do?

**Comment by CubeMaster007** [comment]
I was using eclipse Mars on Windows 10. Not always the same window. I'm using JNativeHook 2.0.3. I closed all other programs running and still this issue occurred. Today, the issue just doesn't occur.

-----Original Message-----

**Comment by kwhat** [comment]
I cannot duplicate this issue and suspect it was an upstream problem.
