### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Er1807** [kwhat/jnativehook#105]
When I try to compile it with msys2 I get this Error. 

 [cc] C:/Program Files/Java/jdk1.8.0_66/include/win32/jni_md.h:34:9: Fehler: unbekannter Typname: »__int64«
       [cc] C:/Program Files/Java/jdk1.8.0_66/include/win32/jni_md.h:34:9: Fehler: unbekannter Typname: »__int64«
       [cc] In file included from C:/Program Files/Java/jdk1.8.0_66/include/jni.h:45:0,
       [cc]  typedef __int64 jlong;
       [cc]  typedef __int64 jlong;
       [cc]          ^
       [cc]          ^
       [cc]                  from C:/Users/Eric/Desktop/jnativehook-2.0.3/src/jni/jni_Logger.c:19:
       [cc] In file included from C:/Program Files/Java/jdk1.8.0_66/include/jni.h:45:0,
       [cc] C:/Program Files/Java/jdk1.8.0_66/include/win32/jni_md.h:34:9: Fehler: unbekannter Typname: »__int64«
       [cc]                  from C:/Users/Eric/Desktop/jnativehook-2.0.3/src/jni/jni_Properties.c:19:
       [cc]  typedef __int64 jlong;
       [cc] C:/Program Files/Java/jdk1.8.0_66/include/win32/jni_md.h:34:9: Fehler: unbekannter Typname: »__int64«
       [cc]          ^
       [cc]  typedef __int64 jlong;
       [cc]          ^

Would be nice if you could help me with this.

Complete log : http://pastebin.com/cRjW0d31

**Comment by kwhat** [comment]
Something is wrong with your compiler.  The error you are getting is in the JDK source and not the library.  What compiler are you using?  Cygwin?

**Comment by Er1807** [comment]
I dont know if I made everything bad after reinstalling jdk but know both compielers say that they cant find the jni.h file but the file is in the Java/include folder.

**Comment by Er1807** [comment]
both compilers are now having problems with undefind references:
 C:/Users/Eric/Desktop/jnativehook-2.0.3/bin/obj/jni/jni_Load.o:jni_Load.c:(.text+0xce): undefined reference to `jni_ClearProperties'

it failed at: \build.xml:452: exec returned: 1

**Comment by kwhat** [comment]
jni_ClearProperties is defined by jni_Properties.h and implemented in jni_Properties.c which are both included in the src/jni folder.  Did you follow the setup guide in the wiki?  Did you try doing an `ant distclean` ?

**Comment by kwhat** [comment]
I just remembered that there is a path issue with recent versions of msys outlined here https://github.com/msys2/msys2.github.io/issues/20 and https://sourceforge.net/p/msys2/discussion/general/thread/dbe17030/  You need to set the MSYS2_PATH_TYPE env variable to inherit, but if that was the issue, javac would have failed :/
