### ISSUE TITLE
How to abort a event?

### ISSUE THREAD

**Issue by z1003031335** [kwhat/jnativehook#108]

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/wiki/ConsumingEvents

**Comment by z1003031335** [comment]
It does not work for me.

**Comment by kwhat** [comment]
Are you on Linux?

**Comment by kwhat** [comment]
Did you implement the VoidDispatchService?

**Comment by z1003031335** [comment]
Yes,on Linux.

**Comment by kwhat** [comment]
The future is unsupported on Linux because it is not possible.

**Comment by z1003031335** [comment]
OK,thinks for your answer.In addition,this
