### ISSUE TITLE
Mac: ConsumingEvents: GlobalScreen.unregisterNativeHook hangs - app has to be killed

### ISSUE THREAD

**Issue by RaiMan** [kwhat/jnativehook#109]
I know about "ConsumingEvents not supported", but I tested it and it works.

... but using the method to listen to the ESC key to shutdown the app using JNativeHook does not work: it hangs in GlobalScreen.unregisterNativeHook (I guess at the Thread.join()).

So 2 simple questions:
 - Anything to do with the ExecutorService, to not block GlobalScreen.unregisterNativeHook (besides not using it ;-)
 - is it ok, to just use System.exit() in this case without issuing a GlobalScreen.unregisterNativeHook

**Comment by RaiMan** [comment]
BTW: using 2.0.2 from Maven

**Comment by kwhat** [comment]
Hi RaiMan,

I just woke up and haven't had any coffee yet, but IIRC, you should be able to execute GlobalScreen.unregisterNativeHook() on any other thread to stop it.  You just cant unregister the hook from the thread that receives the event callback from the native system.  Try something like:

    SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            GlobalScreen.unregisterNativeHook()
        }
    });

**Comment by RaiMan** [comment]
... and I am now short before having my private evening ;-)

Great thanks for the speedy answer. I will try and report back.
All the best.

The other question:
is it safe, to use System.exit() without doing the unregister ?

**Comment by kwhat** [comment]
System.exit shouldn't cause an issue, but let me know if you see any unusual behavior.

**Comment by RaiMan** [comment]
The invokeLater() does it - thanks.

... so I only need to use System.exit(), if unregistering does not work and throws exception (which is an unusual situation then anyways).
