### ISSUE TITLE
Convert KeyCodes from VK to VC and vice versa

### ISSUE THREAD

**Issue by henne90gen** [kwhat/jnativehook#112]
Hey I was wondering if there was an easy way to convert between the two key codes.

**Comment by kwhat** [comment]
There is no, but there is a ticket (#106) to add this functionality to a dispatcher.   If you would like to create a lookup table for the key codes, that would save me a bit of time.

**Comment by ivanshen** [comment]
See #113. I created a VK to VC table.

**Comment by henne90gen** [comment]
Thanks, good work. :-D

**Comment by kwhat** [comment]
This has been addressed here https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/keyboard/SwingKeyAdapter.java
