### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by christau** [kwhat/jnativehook#114]
In the Wiki [Compiling](https://github.com/kwhat/jnativehook/wiki/Compiling)
there's a little typo when it comes to building on OSX.

> sudo port install automake **pkg-config** libtool apache-ant

should be
> sudo port install automake **pkgconfig** libtool apache-ant

Also installing autoconf is required, otherwise it won't compile on OSX. At least on my system (10.11.6)
So the line in my case had to be
> sudo port install automake pkgconfig libtool apache-ant **autoconf**

Thanks for sharing this great lib!

**Comment by kwhat** [comment]
Hi, 

Thanks for the bug report, are you using brew or ports?

**Comment by christau** [comment]
I was using ports. On brew there is pkg-config or pkgconfig valid.

**Comment by kwhat** [comment]
Hi, 

Should be correct, please double check at https://github.com/kwhat/jnativehook/wiki/Compiling
