### ISSUE TITLE
set out special keys?

### ISSUE THREAD

**Issue by RedToor** [kwhat/jnativehook#116]
as I can configure the outputs of the special keys (ENTER, ControlLeft, Shift ETC) not be registered or otherwise leave?

`Left ControlLeft ControlLeft ControlLeft ControlLeft ControlCIntroLeft ControlVSSSLeft AltTabuladorLeft ControlCIntroIntroLISTOEspacioBROIntroLOEspacioDEEspacioUPDAREEspacioLRetrocesoRetrocesoRetrocesoRetrocesoTEEspacioLOEspacioRetrocesoSEspacioBINARIOSEspacioTAMBIE`

to example->>>
`<-<-<-<-< SSS [TAB] .... LISTO [\n]`

Thank you.

**Comment by kwhat** [comment]
Hi, 

I'm sorry, I do not understand the question.  If you would like to disable console output, see https://github.com/kwhat/jnativehook/wiki/ConsoleOutput

**Comment by RedToor** [comment]
ControlLeft replace <- in output

OutPut : 

ControlLeft = <-
ControlC     = Ctrl^c

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/blob/2.0/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L715

try java -jar -DAWT.control_r="->" jar/JNativeHook.jar

**Comment by kwhat** [comment]
you cannot make that replacement for ctrl + c thats two keys.

**Comment by RedToor** [comment]
just that I needed, thank you very much.
