### ISSUE TITLE
Mac trackpad freezes

### ISSUE THREAD

**Issue by SlightlyCyborg** [kwhat/jnativehook#117]
I don't really understand what is happening, but when I registernNativeHook it really messes with the functionality of the mac trackpad. 3 finger swipe is really messed up. I know it is just the mouse that is causing the problem because I can still switch workspaces with hotkeys and scroll using the up and down arrows with no lag.

**Comment by kwhat** [comment]
What do you mean "really messes with the functionality?"  Can you paste some of the console output at debug log level?  Thanks

**Comment by SlightlyCyborg** [comment]
I mean that 3 finger swipes to switch desktops is extremely laggy if it exists at all. 2 finger scrolling is almost unusable. As soon as I stop the hook thread all of those problems clear up.

**Comment by kwhat** [comment]
Does it happen with the demo included with the jar, or in the program you are creating?  There isn't a whole lot going on with mouse movement when the hook is running.

**Comment by SlightlyCyborg** [comment]
That is reassuring. It works well using the demo JAR. Perhaps I am doing something wrong. I am using `com.1stleg/jnativehook "2.0.3"` from maven using Clojure's `lein`

My code looks like this

```
(def keylogger
  (proxy [NativeKeyListener] []
    (nativeKeyPressed [e]
      (println (.getModifiers e)))))

(defn start-key-logger []
  (GlobalScreen/registerNativeHook)
  (GlobalScreen/addNativeKeyListener
   keylogger))

```

Where proxy instantiates an anonymous class.

**Comment by SlightlyCyborg** [comment]
Ok. I I think I figured it out. It has to do with the underlying libuiohook lib. There was a div by 0 error in horizontal scrolling. I patched libuiohook and submitted a pull request.
