### ISSUE TITLE
OSX - Unhandled Darwin event: 0X1D - Example: GlobalMouseListenerExample.java

### ISSUE THREAD

**Issue by r1c4r60** [kwhat/jnativehook#120]
OSX 10.12 - Sierra

Sep 29, 2016 9:16:03 AM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_event_proc [919]: Unhandled Darwin event: 0X1D.

**Comment by r1c4r60** [comment]
There is an older issue open for this case. It seems that the log message should just be ignored and could be switched off by recompiling with specific flags. Closing.

**Comment by kwhat** [comment]
You can change the log level from default (INFO) to WARN to suppress the message.  This should probably be a debug message not an info message for all platforms.

https://github.com/kwhat/libuiohook/blob/master/src/darwin/input_hook.c#L1098
