### ISSUE TITLE
works with jersey on mac os but not on raspbian

### ISSUE THREAD

**Issue by keviin55** [kwhat/jnativehook#121]
I created a web-server with Eclipse using Java and Jersey. In one request I create a new thread and I used this library to get the input of the keyboard in the background. If I launch the service with Eclipse on my mac OSX in works perfectly and I was able to get the Keyboard input. On a Raspberry Pi 3 with Raspbian and a keyboard attached on it, I launched the maven project with this command 
`mvn clean verify org.codehaus.cargo:cargo-maven2-plugin:run`
all POST/GET requests worked fine outside the one responsible of start getting the keyboard input. I get this error in Jersey.

> [INFO] [talledLocalContainer] # Problematic frame:
> [INFO] [talledLocalContainer] # C  [libX11.so.6+0x824a4]  XkbGetUpdatedMap+0x8
> [INFO] [talledLocalContainer] #
> [INFO] [talledLocalContainer] # Core dump written. Default location: /home/pi/server/target/cargo/configurations/jetty8x/core or core.2932
> [INFO] [talledLocalContainer] #
> [INFO] [talledLocalContainer] # An error report file with more information
> 
> [INFO] [talledLocalContainer] java.net.ConnectException: Connection refused
> [INFO] [talledLocalContainer]   at java.net.PlainSocketImpl.socketConnect(Native Method)
> [INFO] [talledLocalContainer]   at java.net.AbstractPlainSocketImpl.doConnect

**Comment by kwhat** [comment]
Its crashing in the native XkbGetUpdatedMap function.  There should be some dump information in a file called hs_err_####.log  What version of the library are you trying to use?  I don't believe I am calling XkbGetUpdatedMap so I am not sure what could be causing the crash without the dump or some sample code to cause the crash.

**Comment by keviin55** [comment]
I am using the version 2.0.3. here is the log file http://m.uploadedit.com/ba3s/1475856417570.txt

**Comment by keviin55** [comment]
The problem happens when I connect to the Raspberry Pi through SSH  from my mac and launch my program from there. If I launch the program directly from the Raspberry Pi terminal it works fine. Maybe it's some security on linux ... Someone have an idea ?

**Comment by kwhat** [comment]
Sounds like your trying to do XForwarding and the library is crashing.  I wouldn't expect that to ever work, but you should take a look at the nightly for 2.1 on maven central.  I rewrote the X11 subsystem using xkb common.

https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by DanielWulfert** [comment]
I encountered the same problem. I'm tying to run jnativehook on an Arch Linux on a Raspberry Pi through SSH and the JVM instantly crashes with problematic frame 'C  [libX11.so.6+0x80ff4]  XkbGetUpdatedMap+0x4'.
Also tried the 2.1.SNAPSHOT (2.1.20161116.071055-7 to be exact). Same error.

http://textuploader.com/d5igz

**Comment by DanielWulfert** [comment]
forgot to mention ... X11-forwarding is disabled.

**Comment by kwhat** [comment]
@DanielWulfert Its definitely a strange problem.  What model raspberry pi? Also grab the version of Arch you are using.  I don't use XkbGetUpdatedMap directly so I suspect there is a bug in a different X11 function.  Can you also set the log level to debug and paste the console output of the crash?  That will help me locate where in the code it craps out.

Have you tried compiling from source?  I know there are at least two supported  arch architectures raspberry pi, arm6j and arm7a, and Java's support for arm is just for generic "arm."  I don't know if this is what maybe causing your issue, however, the code in question certainly works without issue on x86 and x86_64.

**Comment by kwhat** [comment]
Does it crash on start, or when you register the thread?

**Comment by DanielWulfert** [comment]
It's crashing when registering native hook. After enabling logging, I figured out these were the last lines that were logged before the crash:

```
Dec 01, 2016 7:26:36 PM org.jnativehook.DefaultLibraryLocator getLibraries
WARNING: Invalid library manifest!
Dec 01, 2016 7:26:36 PM org.jnativehook.DefaultLibraryLocator getLibraries
INFO: Library extracted successfully: /tmp/libJNativeHook-4108A6AE2E245B931A2B86AEB1C17E5666B42192.arm.so (0x4108A6AE2E245B931A2B86AEB1C17E5666B42192).
```

Also tried OpenJRE with no luck. It was running on a Pi3 with the latest linux version 4.4.33-1-ARCH. On Windows x86_64 it works like a charm, so thanks for your efforts.
I will try to compile it from source in the next couple of days. Hope I'll get it to run.

**Comment by kwhat** [comment]
Ok if the last line in the log is "Library extracted successfully" then the issue is putting the library into the JVM.  I suspect you are not arm6j.

**Comment by kwhat** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=36230&p=304688

**Comment by DanielWulfert** [comment]
Right, it's an arm7h architecture.

**Comment by kwhat** [comment]
Ok, so take a look at the link I pasted. The issue is that someone over at OpenJDK screwed the pooch with Arm7 so there is no way for me to know what ABI to automatically load for you.  I can compile an arm7a version for you, however, you will need to tell the JVM that version of the library to load by adding a property, or using a custom library loader or setting the library.path you self.  If you can figure out how to detect what arm ABI the running JVM was compiled for from within Java, please let me know. 

https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeSystem.java#L147

**Comment by kwhat** [comment]
Just making sure, you are still 32 bit, right?

**Comment by DanielWulfert** [comment]
Yeah, arm7l should still be 32-bit. Java version is build 1.8.0_111-b14 and JVM is a
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode). So everything 32-bit.

**Comment by DanielWulfert** [comment]
I will try to figure out how to get the exact JVM architecture in Java, perhaps it's working with Oracle JDK.

**Comment by kwhat** [comment]
Its the same in oracle.

**Comment by kwhat** [comment]
For reference, there is a lot of talk about how to fix this here:

http://labb.zafena.se/?p=727
http://mail.openjdk.java.net/pipermail/porters-dev/2013-January/000426.html
http://jogamp.org/git/?p=gluegen.git;a=blob;f=src/java/jogamp/common/os/elf/ElfHeader.java;h=3b82a69ca9bcef0e482c76e9c6b5d6c07b04d6ec;hb=371e1dbff6f5f255ab27ed0ab32368abb06eed82
http://jogamp.org/git/?p=gluegen.git;a=blob;f=src/java/jogamp/common/os/PlatformPropsImpl.java;h=0c597cbc15a883a46adee42d263fee12bcc4c5b2;hb=371e1dbff6f5f255ab27ed0ab32368abb06eed82

**Comment by DanielWulfert** [comment]
Mhh. Would it help if I come up with a solution for linux in java by parsing the exact processor architecture out of lscpu or /proc/cpuinfo? That should work for all linux based architectures.

**Comment by kwhat** [comment]
arm is broken on gentoo right now so I cant build...

**Comment by kwhat** [comment]
Please try the latest [nightly](https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20161203.174335-10.jar).  Set the os.arch property on start, `java -jar jnativehook-2.1.20161203.174335-10.jar -Dos.arch=arm7`

**Comment by kwhat** [comment]
eh i am guessing you cannot override os.arch.

**Comment by kwhat** [comment]
Can you try os.arch.variant and see if it has a value?

**Comment by DanielWulfert** [comment]
Sorry, os.arch.variant is null. And as you said I am not able to override os.arch resulting in loading the wrong lib:
`Library extracted successfully: /tmp/libJNativeHook-C27870A05464A392A3552234D2E46D6129E828C2.arm6.so`

**Comment by DanielWulfert** [comment]
I tested processing information from lscpu and /proc/cpuinfo and made a small test project. I've uploaded it to http://s000.tinyupload.com/?file_id=68415404791373692836 . If it helps, you can use any code from it as you like.

**Comment by kwhat** [comment]
Can you post your /proc/cpuinfo?

**Comment by DanielWulfert** [comment]
Sure ...
```
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2709
Revision        : a02082
Serial          : 0000000043bf280f
```

**Comment by kwhat** [comment]
Try https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20161207.162900-13.jar

**Comment by kwhat** [comment]
I added an arm7 check.

**Comment by DanielWulfert** [comment]
Thanks so much for your efforts so far. I think we are nearly there, but something seems worng with the pattern used for matching the ARMv7 architecture. It still tries to load the arm6 lib and crashes. 
If I change the pattern to armv7 it successfully detects the ARMv7 architecture.

**Comment by kwhat** [comment]
No problem, thanks for testing.  I seem to have made a typo in the regex.  See if this fixes it.

https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20161208.160543-18.jar

**Comment by DanielWulfert** [comment]
Sorry, still detecting arm6 as architecture. I think it's the missing 'v' between arm and 7. I think the pattern `arm[v]?7` should work for both cases.

**Comment by kwhat** [comment]
hahah your right!  I totally missed the v!  https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20161209.161645-21.jar

**Comment by DanielWulfert** [comment]
Now it loads the rigth library, but still crashes with the same error:
```
INFO: Library extracted successfully: /tmp/libJNativeHook-38342DCF3B5447F5361706C7BB8F9DFC13A0F31.arm7.so (0x38342DCF3B5447F5361706C7BB8F9DFC13A0F31).

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x644e5ff4, pid=781, tid=0x6474f470
```
http://txt.do/dd61f

**Comment by kwhat** [comment]
I have kind of run out of ideas here.  Have you tried compiling from src locally?  That may help me determine a direction.

**Comment by DanielWulfert** [comment]
Took the latest jnativehook-2.1.20161209.161652-22-sources, jnitasks version 0.2.0 and successfully builded the jar from the instructions in the wiki. I had to manually move the generated .so file to a new arm7 directory instead of leaving it the generic arm directory, so it will be loaded on the arm7 system.
After running the resulted .jar, it crashed exactly as before. Any information I can provide to help getting to the core of the problem?

**Comment by kwhat** [comment]
> I had to manually move the generated .so file to a new arm7 directory instead of leaving it the generic arm directory, so it will be loaded on the arm7 system.

I totally forgot about this issue.  It's going to be hard to get that info in ant.

> Any information I can provide to help getting to the core of the problem?

The fact that it didn't work locally for you tells me that I don't need to mess around with my compiler anymore, there is something else broken.  The next step would be to run the native code independently to figure out what is crashing.  Also let me know what version of what OS and what Hardware this is running on.  I have a Raspberry A & B+ laying around.

This is from memory so it may need a tweak or two. Hopefully this will provide a decent backtrack.

- Download the latest master https://github.com/kwhat/libuiohook
- ./bootstrap.sh
- ./configure --enable-demo --enable-static --disable-shared --with-pic
- make
- gdb ./demo_hook
- # continue
- # bt

**Comment by kwhat** [comment]
also paste the build.properties file generated for your jnativehook build.

**Comment by DanielWulfert** [comment]
build.properties:
```
ant.build.debug=false
ant.build.javac.compiler=modern
ant.build.javac.source=1.8
ant.build.javac.target=1.8
ant.build.javac.include=/usr/lib/jvm/java-8-jdk//include
ant.build.javac.args=
ant.build.native.toolchain=gcc
ant.build.native.jobs=auto
ant.build.native.cflags=-O2 -pipe
ant.build.native.ldflags=
```

**Comment by DanielWulfert** [comment]
./bootstrap.sh
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory config
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:63: installing 'config/ar-lib'
configure.ac:62: installing 'config/compile'
configure.ac:54: installing 'config/config.guess'
configure.ac:54: installing 'config/config.sub'
configure.ac:59: installing 'config/install-sh'
configure.ac:59: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
```
./configure --enable-demo --enable-static --disable-shared --with-pic
```
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking target system type... armv7l-unknown-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc option to accept ISO C99... none needed
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for stdint.h... (cached) yes
checking for uint64_t... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert armv7l-unknown-linux-gnueabihf file names to armv7l-unknown-linux-gnueabihf format... func_convert_file_noop
checking how to convert armv7l-unknown-linux-gnueabihf file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking operating system... armv7l-unknown-linux-gnueabihf (Linux Compatible)
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for X11... yes
checking for XTST... yes
checking for XRecordQueryVersion in -lXtst... yes
checking for X11/extensions/record.h... yes
checking for XT... yes
checking for XTestQueryExtension in -lXtst... yes
checking for X11/extensions/XTest.h... yes
checking for XINERAMA... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for X11_XCB... yes
checking for XKBCOMMON... yes
checking for XKBCOMMON_X11... yes
checking for XKBFILE... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating pc/uiohook.pc
config.status: creating Makefile
config.status: creating include/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
```
For building successfully I had to add `#include <wchar.h>` to src/demo_hook_async.c and src/demo_hook.c because otherwise the build process failed with complaining about unknown type `wint_t`. After adding the include it worked.
make
```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/libuiohook_la-logger.lo -MD -MP -MF src/.deps/libuiohook_la-logger.Tpo -c -o src/libuiohook_la-logger.lo `test -f 'src/logger.c' || echo './'`src/logger.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/libuiohook_la-logger.lo -MD -MP -MF src/.deps/libuiohook_la-logger.Tpo -c src/logger.c  -fPIC -DPIC -o src/libuiohook_la-logger.o
mv -f src/.deps/libuiohook_la-logger.Tpo src/.deps/libuiohook_la-logger.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-input_helper.lo -MD -MP -MF src/x11/.deps/libuiohook_la-input_helper.Tpo -c -o src/x11/libuiohook_la-input_helper.lo `test -f 'src/x11/input_helper.c' || echo './'`src/x11/input_helper.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-input_helper.lo -MD -MP -MF src/x11/.deps/libuiohook_la-input_helper.Tpo -c src/x11/input_helper.c  -fPIC -DPIC -o src/x11/libuiohook_la-input_helper.o
mv -f src/x11/.deps/libuiohook_la-input_helper.Tpo src/x11/.deps/libuiohook_la-input_helper.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-input_hook.lo -MD -MP -MF src/x11/.deps/libuiohook_la-input_hook.Tpo -c -o src/x11/libuiohook_la-input_hook.lo `test -f 'src/x11/input_hook.c' || echo './'`src/x11/input_hook.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-input_hook.lo -MD -MP -MF src/x11/.deps/libuiohook_la-input_hook.Tpo -c src/x11/input_hook.c  -fPIC -DPIC -o src/x11/libuiohook_la-input_hook.o
mv -f src/x11/.deps/libuiohook_la-input_hook.Tpo src/x11/.deps/libuiohook_la-input_hook.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-post_event.lo -MD -MP -MF src/x11/.deps/libuiohook_la-post_event.Tpo -c -o src/x11/libuiohook_la-post_event.lo `test -f 'src/x11/post_event.c' || echo './'`src/x11/post_event.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-post_event.lo -MD -MP -MF src/x11/.deps/libuiohook_la-post_event.Tpo -c src/x11/post_event.c  -fPIC -DPIC -o src/x11/libuiohook_la-post_event.o
mv -f src/x11/.deps/libuiohook_la-post_event.Tpo src/x11/.deps/libuiohook_la-post_event.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-system_properties.lo -MD -MP -MF src/x11/.deps/libuiohook_la-system_properties.Tpo -c -o src/x11/libuiohook_la-system_properties.lo `test -f 'src/x11/system_properties.c' || echo './'`src/x11/system_properties.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2 -MT src/x11/libuiohook_la-system_properties.lo -MD -MP -MF src/x11/.deps/libuiohook_la-system_properties.Tpo -c src/x11/system_properties.c  -fPIC -DPIC -o src/x11/libuiohook_la-system_properties.o
mv -f src/x11/.deps/libuiohook_la-system_properties.Tpo src/x11/.deps/libuiohook_la-system_properties.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -I./include -I./src/x11 -I./src -g -O2  -Wl,--no-undefined -Wl,--no-undefined -o libuiohook.la -rpath /usr/local/lib src/libuiohook_la-logger.lo  src/x11/libuiohook_la-input_helper.lo src/x11/libuiohook_la-input_hook.lo src/x11/libuiohook_la-post_event.lo src/x11/libuiohook_la-system_properties.lo   -lxkbfile -lxkbcommon-x11 -lxkbcommon -lxkbcommon -lX11-xcb -lX11 -lxcb -lXinerama -lXt -lX11 -lXtst -lXtst -lX11
libtool: link: ar cru .libs/libuiohook.a  src/libuiohook_la-logger.o src/x11/libuiohook_la-input_helper.o src/x11/libuiohook_la-input_hook.o src/x11/libuiohook_la-post_event.o src/x11/libuiohook_la-system_properties.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libuiohook.a
libtool: link: ( cd ".libs" && rm -f "libuiohook.la" && ln -s "../libuiohook.la" "libuiohook.la" )
gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -MT src/demohookasync-demo_hook_async.o -MD -MP -MF src/.deps/demohookasync-demo_hook_async.Tpo -c -o src/demohookasync-demo_hook_async.o `test -f 'src/demo_hook_async.c' || echo './'`src/demo_hook_async.c
src/demo_hook_async.c: In function 'hook_enable':
src/demo_hook_async.c:276:6: warning: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
      __FUNCTION__, __LINE__, priority, (unsigned long) hook_thread);
      ^~~~~~~~~~~~
src/demo_hook_async.c:324:5: warning: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
     __FUNCTION__, __LINE__, status);
     ^~~~~~~~~~~~
mv -f src/.deps/demohookasync-demo_hook_async.Tpo src/.deps/demohookasync-demo_hook_async.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2  -lXinerama -lXt -lX11 -lXtst -lXtst -lX11  -Wl,--no-undefined -o demohookasync src/demohookasync-demo_hook_async.o ./libuiohook.la -lxkbfile -lxkbcommon-x11 -lxkbcommon -lxkbcommon -lX11-xcb -lX11 -lxcb -lXinerama -lXt -lX11 -lXtst -lXtst -lX11
libtool: link: gcc -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -Wl,--no-undefined -o demohookasync src/demohookasync-demo_hook_async.o  ./.libs/libuiohook.a -lxkbfile -lxkbcommon-x11 -lxkbcommon -lX11-xcb -lxcb -lXinerama -lXt -lXtst -lX11 -pthread
gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -MT src/demopost-demo_post.o -MD -MP -MF src/.deps/demopost-demo_post.Tpo -c -o src/demopost-demo_post.o `test -f 'src/demo_post.c' || echo './'`src/demo_post.c
mv -f src/.deps/demopost-demo_post.Tpo src/.deps/demopost-demo_post.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2  -lXinerama -lXt -lX11 -lXtst -lXtst -lX11  -Wl,--no-undefined -o demopost src/demopost-demo_post.o ./libuiohook.la -lxkbfile -lxkbcommon-x11 -lxkbcommon -lxkbcommon -lX11-xcb -lX11 -lxcb -lXinerama -lXt -lX11 -lXtst -lXtst -lX11
libtool: link: gcc -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -Wl,--no-undefined -o demopost src/demopost-demo_post.o  ./.libs/libuiohook.a -lxkbfile -lxkbcommon-x11 -lxkbcommon -lX11-xcb -lxcb -lXinerama -lXt -lXtst -lX11 -pthread
gcc -DHAVE_CONFIG_H -I. -I./include     -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -MT src/demoprops-demo_properties.o -MD -MP -MF src/.deps/demoprops-demo_properties.Tpo -c -o src/demoprops-demo_properties.o `test -f 'src/demo_properties.c' || echo './'`src/demo_properties.c
mv -f src/.deps/demoprops-demo_properties.Tpo src/.deps/demoprops-demo_properties.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2  -lXinerama -lXt -lX11 -lXtst -lXtst -lX11  -Wl,--no-undefined -o demoprops src/demoprops-demo_properties.o ./libuiohook.la -lxkbfile -lxkbcommon-x11 -lxkbcommon -lxkbcommon -lX11-xcb -lX11 -lxcb -lXinerama -lXt -lX11 -lXtst -lXtst -lX11
libtool: link: gcc -Wall -Wextra -pedantic -pthread -g -O2 -I./include -g -O2 -Wl,--no-undefined -o demoprops src/demoprops-demo_properties.o  ./.libs/libuiohook.a -lxkbfile -lxkbcommon-x11 -lxkbcommon -lX11-xcb -lxcb -lXinerama -lXt -lXtst -lX11 -pthread
```

**Comment by DanielWulfert** [comment]
After building I started gdb and did a first run.
```
Starting program: /home/dev/libuiohook-master/demohook
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
on_library_load [456]: XOpenDisplay failure!
load_input_helper [1907]: XkbGetKeyboard failed to locate a valid keyboard!

Program received signal SIGSEGV, Segmentation fault.
0x76de3ff4 in XkbGetUpdatedMap () from /usr/lib/libX11.so.6
```
backtrace gave
```
#0  0x76de3ff4 in XkbGetUpdatedMap () from /usr/lib/libX11.so.6
#1  0x76de4110 in XkbGetMap () from /usr/lib/libX11.so.6
#2  0x00014d90 in load_input_helper (disp=0x0) at src/x11/input_helper.c:1911
#3  0x0001191c in on_library_load () at src/x11/system_properties.c:492
#4  0x00014ebc in __libc_csu_init ()
#5  0x76c0f60c in __libc_start_main () from /usr/lib/libc.so.6
#6  0x000119b8 in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
What suprises me is the open display failure and that it couldn't locate a valid keyboard.
lsusb says: `Bus 001 Device 004: ID 046a:0023 Cherry GmbH CyMotion Master Linux Keyboard G230`

**Comment by kwhat** [comment]
Is X11 running?

**Comment by kwhat** [comment]
hmmm is an xkb map issue.  Not sure why its segfaulting, you have xkb...  `keyboard_map = XkbGetMap(disp, XkbAllClientInfoMask, XkbUseCoreKbd);` seems the be the issue, but the disp is good.  You could try passing XOpenDisplay(NULL) instead of disp to `XkbGetMap(...)` and see if that has any effect.  

If that doesn't work, you may want to entertain the idea of deleting [1868-1909](https://github.com/kwhat/libuiohook/blob/master/src/x11/input_helper.c#L1868)

**Comment by DanielWulfert** [comment]
Thanks. I'll try that.

**Comment by DanielWulfert** [comment]
Good news. It finally runs. 
The problem wasn't your code but my setup, so sorry for the trouble it caused. The crash and most of the debug output was very misleading. The one line that caught my attention was the ' XOpenDisplay failure'. It was a security issue on the X server while trying to open the display. 
I always auto-logged-in with one user and changed to another one. It seems I have to transfer the authorization information used to connect to the X server to the second user with `xauth add ...` along with the information provided by `xauth list` from the first user.
Since it is running now with the latest 2.1 snapshot version from the repository, you can close this issue.
Thanks for the help and the patience.

**Comment by kwhat** [comment]
oh awesome!  I am so glad we figured this one out ;)  That's really strange way that things failed indeed. I would expect that XkbGetKeyboard should at least return some kind of error state if there was insufficient access but maybe it's just doesn't account for that case.  Did the arm7 stuff work?  That was the last thing for 2.1.

**Comment by DanielWulfert** [comment]
Yeah. The arm7 recognition in 2.1 works perfectly. Keep up the good work!

**Comment by kwhat** [comment]
Last Question, I promise ;)  Did you confirm that the 2.0 arm6j binary does not work for your architecture?

**Comment by DanielWulfert** [comment]
You are right. Haven't tested that yet. 
At a first glance it seems that the 2.0 version also runs on armv7. I will make a more detailed test tomorrow and post the results.

**Comment by DanielWulfert** [comment]
I have just tested and can confirm that the 2.0.3 version of jnativehook runs perfectly on armv7. So it was an xauth problem right from the beginning.

**Comment by kwhat** [comment]
Cool, thanks for testing.  I will back out some of the arm stuff and hopefully get 2.1 out the door soon.
