### ISSUE TITLE
Can I know the time when user is long press a key ?

### ISSUE THREAD

**Issue by yussef123** [kwhat/jnativehook#123]
Hi,
I want to handle the case when user long press in a key.

**Comment by yussef123** [comment]
Can you answer me please ? because I need this feature in my app.

**Comment by kwhat** [comment]
You mean hold the key down or do you want to track how long the key is held?  This is all possible.  Auto repeat only causes a key down and key typed bounce.  Just track the key up for the release.

**Comment by yussef123** [comment]
I want to track how long the key is held. Can you create for me a small snipet explain how can I do it please if this will not bother you ?

**Comment by kwhat** [comment]
```
long startTime = 0;

public function keyPressed(NativeKeyEvent e) {
    if (startTime == 0 && e.getKeyCode() == NativeKeyCode.VK_A) {
        startTime = System.currentTimeMillis();
    }
}

public function keyReleased(NativeKeyEvent e) {
    if (startTime != 0 && e.getKeyCode() == NativeKeyCode.VK_A) {
        long holdTime = System.currentTimeMillis() - startTime;
        startTime = 0;
    }
}
```
