### ISSUE TITLE
JNativehook and Linux keyboard layouts

### ISSUE THREAD

**Issue by sam455** [kwhat/jnativehook#125]
After using JNativehook 2.1 on LXLE (Ubuntu based OS) I found a bug when typing Arabic characters, the listener receive a lot of events for one key and the result is werid characters, And  sometimes the JVM crash afterword (I was unable to reproduce the crash recently)
Note that everything works fine when typing English characters.

Here is the code I am using 
       
    try
	{
		GlobalScreen.registerNativeHook();
		GlobalScreen.addNativeKeyListener(new NativeKeyListener() 
		{
		    @Override
		    public void nativeKeyPressed(NativeKeyEvent e) {
		    }

		    @Override
		    public void nativeKeyReleased(NativeKeyEvent e) {
		    }

		    @Override
		    public void nativeKeyTyped(NativeKeyEvent e)
		    {
		        System.out.println("Char: " + e.getKeyChar());
		    }
		});
	}
	catch(Exception e){e.printStackTrace();}

Here is a small part of the output after I typed one Arabic key

	Oct 21, 2016 3:11:37 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: xrecord_query [875]: XRecord version: 1.13.

	Oct 21, 2016 3:11:42 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [281]: Key 0X26 pressed. (0X6C)

	Oct 21, 2016 3:11:42 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char: l
	INFO: hook_event_proc [314]: Key 0 typed. (l)

	Oct 21, 2016 3:11:42 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [366]: Key 0X26 released. (0X6C)

	Oct 21, 2016 3:11:47 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [281]: Key 0X2A pressed. (0XFFE1)

	Oct 21, 2016 3:11:47 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [281]: Key 0X3A pressed. (0XFE08)

	Oct 21, 2016 3:11:47 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [366]: Key 0X3A released. (0XFE08)

	Oct 21, 2016 3:11:47 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [366]: Key 0X2A released. (0XFFE1)

	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [281]: Key 0X26 pressed. (0X5E5)

	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [314]: Key 0 typed. (ü
	Char: 
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [314]: Key 0 typed. (缩)

	Char: 缩
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char: 뼐
	INFO: hook_event_proc [314]: Key 0 typed. (ü
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char: 缩
	INFO: hook_event_proc [314]: Key 0 typed. (缩)

	Char: 춠
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [314]: Key 0 typed. (ü
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char: 缩
	Char: 地
	INFO: hook_event_proc [314]: Key 0 typed. (缩)

	Char: 缩
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [314]: Key 0 typed. (ü¼
	Char: 
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char: 缩
	Char: $
	INFO: hook_event_proc [314]: Key 0 typed. (缩)

	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	INFO: hook_event_proc [314]: Key 0 typed. (ü
	Oct 21, 2016 3:11:48 AM org.jnativehook.GlobalScreen$NativeHookThread enable
	Char:

**Comment by kwhat** [comment]
Try setting the log level to debug.

**Comment by kwhat** [comment]
Are you utf-16?  Also xkbcommon version.

**Comment by sam455** [comment]
I already tried that, nothing changed

**Comment by kwhat** [comment]
No, I need more information to figure out why this is not working.

**Comment by kwhat** [comment]
See if this solves the issue or if you get the correct output on the console.

[jnativehook-2.1.20161023.zip](https://github.com/kwhat/jnativehook/files/546588/jnativehook-2.1.20161023.zip)

**Comment by kwhat** [comment]
This should be fixed in the trunk.  I can't confirm because I don't have support for Arabic and there are about a 1000 things that could be wrong with UTF on either of our systems.

**Comment by kwhat** [comment]
Check the latest build here https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by sam455** [comment]
The problem has been solved in the latest build
Thanks you
