### ISSUE TITLE
Link to LGPL 3.0 license on Maven Central leads to GPL 3.0 license

### ISSUE THREAD

**Issue by ubershy** [kwhat/jnativehook#127]
Hello. Thank you for maintaining JNativeHook library.

On [this page](https://mvnrepository.com/artifact/com.1stleg/jnativehook/2.0.2) I see that the link to LGPL 3.0 license leads to GLP 3.0 license: [https://www.gnu.org/licenses/gpl-3.0.txt](https://www.gnu.org/licenses/gpl-3.0.txt)

I think the correct link should be this one: [https://www.gnu.org/licenses/lgpl.html](https://www.gnu.org/licenses/lgpl.html).

**Comment by kwhat** [comment]
I believe it's been fixed in the trunk

**Comment by ubershy** [comment]
Yes, you are right. Thanks.
