### ISSUE TITLE
syntax error near unexpected token `X11,'

### ISSUE THREAD

**Issue by TheHaker117** [kwhat/jnativehook#129]
When I try to build Jnativehook, i have this error:

![captura de pantalla 119](https://cloud.githubusercontent.com/assets/22799095/20163529/d6b29a62-a6c2-11e6-8c0e-e006821ffcda.png)

And I don't know why, I've installed all the prerequisites of JNativeHook and libuihook (I think so).

**Comment by kwhat** [comment]
It looks like you ran the bootstrap file on linux and then tried to compile on windows.  use `ant distclean`

**Comment by kwhat** [comment]
Did distclean solve the issue?

**Comment by TheHaker117** [comment]
Sorry for not responding, I used distclean and finally it could be compiled!

![captura de pantalla 120](https://cloud.githubusercontent.com/assets/22799095/20204850/e0eca8e8-a798-11e6-8342-8116c59b61ca.png)

Thanks for help! You're great!

**Comment by kwhat** [comment]
Awesome, your welcome :)
