### ISSUE TITLE
Support log levels via SLF4J/log4j?

### ISSUE THREAD

**Issue by dmg46664** [kwhat/jnativehook#130]
Perhaps I'm missing something because some of the log output looks like level is outputted, but I cannot see how to control this.

Changing the log level to DEBUG doesn't prevent INFO output from occurring.

**Comment by kwhat** [comment]
The library uses the Java core logging:
 https://docs.oracle.com/javase/8/docs/technotes/guides/logging/overview.html
 https://docs.oracle.com/javase/8/docs/api/java/util/logging/package-summary.html

Setting the log level to debug will include everything at that level or higher.  I am not sure how Log4j works, but that behavior is inline with most logging I have encountered.

**Comment by dmg46664** [comment]
@kwhat,
Thanks, I'm an idiot. Please ignore.
