### ISSUE TITLE
Unhandled OS events in Mac OSX Sierra 10.12.1

### ISSUE THREAD

**Issue by dmg46664** [kwhat/jnativehook#131]
```
Nov 14, 2016 7:14:58 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_event_proc [919]: Unhandled Darwin event: 0X1D.
```

If it doesn't matter I still can't see how to disable it.

**Comment by kwhat** [comment]
I believe that was set to debug in Beta1.

**Comment by dmg46664** [comment]
@kwhat thanks again.
I guess I need to compile binaries on a Mac to get this beta version. Any idea about the release date for 2.1.0 is?

**Comment by dmg46664** [comment]
Okay, judging from the NEWS log it is probably 6 months away. Happy to close this issue and thanks for your help 👍 :-)

**Comment by kwhat** [comment]
2.1 is pretty much done.  I am just going though a 2 or 3 beta release and it should be good to go after that.  I would expect Dec.

**Comment by kwhat** [comment]
You can get the latest snapshots here: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by kwhat** [comment]
2.1 will be out this week.
