### ISSUE TITLE
getKeyChar as a static getter

### ISSUE THREAD

**Issue by xunkar** [kwhat/jnativehook#132]
Hello,

I'm wondering if it would be possible to retrieve the actual character of a key, like getKeyChar() does, but through a static method that would take a key code as parameter. The problem I'm having is that getKeyText() returns erroneous names if your keyboard layout isn't qwerty. For example, key code 39 returns "Point-virgule" (semicolon) on my french azerty layout, although it should be the dollar sign. Furthermore, the full name of a key—even if correct—is most of the time too long and harder to understand that simply showing the actual character.

Thank you.

**Comment by kwhat** [comment]
Hi,

No API currently exists to accomplish that task and would not be possible without taking into account modifier masks and lock masks.  The getKeyText() should function exactly like it does for java.awt.event.KeyEvent.  Do you get the correct key code and/or key text from the java.awt.event.KeyEvent?  Also what platform are you using?

**Comment by xunkar** [comment]
Here's the snippet code I tested

      try {
         GlobalScreen.registerNativeHook();
         GlobalScreen.setEventDispatcher(new SwingDispatchService());
      } catch (NativeHookException x) {
         LOG.error("Cannot register native hook, cause: {}", x.getMessage());
         System.exit(ERROR_NATIVE_HOOK);
      }      
      GlobalScreen.addNativeKeyListener(new NativeKeyListener() {
         @Override public void nativeKeyPressed(NativeKeyEvent event) {
            System.out.println(
                  "Native key " + event.getKeyCode() 
                  + " is " + NativeKeyEvent.getKeyText(event.getKeyCode()));
         }
         @Override public void nativeKeyReleased(NativeKeyEvent event) {}
         @Override public void nativeKeyTyped(NativeKeyEvent event) {}
      });      
      addKeyListener(new KeyAdapter() {
         @Override public void keyPressed(KeyEvent event) {
            System.out.println(
                  "Java key " + event.getKeyCode()
                  + " is " + KeyEvent.getKeyText(event.getKeyCode()));
         }
      });

And the result is as follows

    Native key 39 is Point-virgule
    Java key 515 is Dollar
    Native key 50 is M
    Java key 77 is M
    Native key 57 is Espace
    Java key 32 is Espace

Strangely enough, the M letter is correct although its place differs between azerty and qwerty, but the dollar key erroneously returns 'Point-virgule'. Most keys aside from the letters are incorrect. I then switched over my keyboard layout and language settings to English (US) and got the following result for the dollar key.

    Native key 27 is Crochet fermant
    nov. 16, 2016 1:57:23 PM org.jnativehook.GlobalScreen$NativeHookThread enable
    GRAVE: refresh_locale_list [583]: Could not find keyboard map for locale 0X0000000004090409!
    Java key 93 is Crochet fermant

Note that 'Crochet fermant' means 'Closing bracket' which I assume is in qwerty layout in place of the azerty dollar. I'm using Windows 10 (1511, no anniversary update).

**Comment by kwhat** [comment]
Thanks for the info, that has been helpful.  The error "Could not find keyboard map for locale 0X0000000004090409" means that the library could not locate the dll to load for the current keyboard map in the registry.  That will only effect the key typed events.  It probably wouldnt hurt to add some debugging during the key map lookup process so at leats we know what failed: https://github.com/kwhat/libuiohook/blob/4e968caafff82bc1828559f6bfbf731efc86cc98/src/windows/input_helper.c#L433

The output based on your example suggests that the scancode lookup table is incorrect.  For the Point-virgule result, what is the native events raw code?  Native key 39 maps to semicolon on a qwerty keyboard.  If the raw code is 186, it looks like it maps to VK_OEM_1 which has a very liberal definition:  "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:' key."  I will look around and see if there is a way to lookup what that should translate to on the current keyboard map.

**Comment by xunkar** [comment]
I checked with other keys and it seems all OEM keys indeed return wrong descriptions even though Java returns the correct one through its key listener. Here is the complete log from JNativeHook when pressing this "native key 39"

    nov. 23, 2016 3:12:02 PM org.jnativehook.GlobalScreen$NativeHookThread enable
    INFOS: process_key_pressed [239]: Key 0X27 pressed. (0XBA)

    nov. 23, 2016 3:12:02 PM org.jnativehook.GlobalScreen$NativeHookThread enable
    INFOS: keycode_to_unicode [651]: Using keyboard layout 0XFFFFFFFFF0C0040C.

    nov. 23, 2016 3:12:02 PM org.jnativehook.GlobalScreen$NativeHookThread enable
    INFOS: process_key_pressed [264]: Key 0 typed. ($)

    nov. 23, 2016 3:12:02 PM org.jnativehook.GlobalScreen$NativeHookThread enable
    INFOS: process_key_released [295]: Key 0X27 released. (0XBA)

However, I doubt the key I'm pressing is VK_OEM_1, on a qwerty keyboard it is the "closing bracket" key which is indeed recognized as such both by Java and JNativeHook when switching the layout to qwerty. Could the key codes not match their physical positions?

I will have some difficulties testing out your library with the new debug function as I do not have the necessary tools to compile it right now, I will try to look into it though.

**Comment by kwhat** [comment]
0XBA is VK_OEM_1 on Windows ;)  There are a number of keys that will likely suffer from this bug:

    0x00BA, // VK_OEM_1
    0x00BB, // VK_OEM_PLUS
    0x00BC, // VK_OEM_COMMA
    0x00BD, // VK_OEM_MINUS
    0x00BE, // VK_OEM_PERIOD
    0x00BF, // VK_OEM_2
    0x00C0, // VK_OEM_3
    0x00DB, // VK_OEM_4
    0x00DC, // VK_OEM_5
    0x00DD, // VK_OEM_6
    0x00DE, // VK_OEM_7
    0x00DF, // VK_OEM_8
    0x00E2, // VK_OEM_102

As far as I can tell, Windows does not define a way to determine how these key codes should be interpreted.  I will add some more debug out put to the next build to see if I can spot something usable.  I am guessing based on the output and the Java char, they are using the key char to determine the key code in most cases.  That is probably a better design decision for virtual key codes than was chosen for this library, but it does come at the additional cost of looking up a key char on key up.

This library does not currently have a VC_DOLLAR key code and possibly several others that maybe required.  What is this key that you are pressing?  Is it literally a Dollar key?  Supporting this kind of behavior properly will require changing the way keys are looked up naively for all platforms.  I will put a work around in place for a few of these keys, but I am not sure how many other bugs like this exist.

**Comment by xunkar** [comment]
Yes it is indeed a literal dollar sign key. The only workaround I can think of right now is to rely on the key char for those few keys on key typed by simulating a KeyEvent with the appropriate key code, a bit messy but should allow me to retrieve a string that more appropriately describe the key. Good luck with your work.

**Comment by kwhat** [comment]
I am closing this as I won't be creating a static method to getKeyCodes.  Please open a new ticket if there is something else.
