### ISSUE TITLE
Raw codes of numpad arrow keys are the same with the codes of ordinary arrows

### ISSUE THREAD

**Issue by fidelcom1** [kwhat/jnativehook#135]
Raw codes of Numpad's arrows are the same with the codes of ordinary arrows.
For example (with turned off Num lock) :

Trying to press 'Left Arrow' button:
Key code: 57419, raw code: 37 

Trying to press 'Num 4' button:
Key code: 57419, raw code: 37

The same problem for 'Right Arrow' and 'Num 6':
Key code: 57421, raw code: 39
Key code: 57421, raw code: 39

(jNativeHook version 2.0.3)

And here is screenshot from PassMark KeyboardTest. Same "BIOS codes", but flag "E" is on when pressing Arrow.
https://i.imgur.com/TvZaPJl.png

**Comment by kwhat** [comment]
The number keys being the same is intended.  The key location should denote the number pad.  You are looking at the platform specific key your setup is producing which will very by installation.

**Comment by fidelcom1** [comment]
Thank you for response!
Unhappily, the key location is always the same :(

Key code: 57419, raw code: 37, key location: 1
Key code: 57419, raw code: 37, key location: 1

I see no differences between this keys in jNativeHook, only in Passmark KeyboardTest I see the difference in flag 'E'. But it's not open source software and I can't determine, how it flag appears. Any chance to help in this case?

**Comment by kwhat** [comment]
interesting, try the latest nightly.  2.1 did fix a key location issue.  https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20161203.174335-10.jar

**Comment by fidelcom1** [comment]
Thank you a lot, now works fine!

Key code: 57419, raw code: 37, key location: 1
Key code: 57419, raw code: 37, key location: 4
