### ISSUE TITLE
local Keyboard ( QWERTY, AZERTY ...)

### ISSUE THREAD

**Issue by PASTJL** [kwhat/jnativehook#136]
How can I configure the type of Keyboard in jnativehook ? By default it seems to be configured with a QWERTY keyboard.
I am French, and before remapping all keys ( to AZERTY Keyboard) , i prefer to know if you have implemented this feature.

**Comment by kwhat** [comment]
The short answer is you can't as of right now.  I will have to change the way the keycodes are represented to add support for keyboard detection.  The key-typed events will produce the correct keychar but the down and up codes will be incorrect.  I will update this and the other tickets with progress.

**Comment by PASTJL** [comment]
Ok, i will play with a keycode map with an AZERTY keyboard. What is the best keycode (invariant in a couple  OS/KeyBoard) to use (NativeKeyEvent.getKeyCode(), NativeKeyEvent.getRawCode() ...) ?
On my desktop win 10 64bits, jnativehook 2.1 beta december 9th, java 8.111 and a jfx application the key- typed event is not captured. Key-pressed and key-released are correctly treated. Is there an issue about this ?

**Comment by PASTJL** [comment]
Sorry, i close the issue by error

**Comment by kwhat** [comment]
So the getKeyCode is a normalized scancode and probably what you want to focus on.  The getRawCode function returns the platform dependent keycode.  Key typed events _should_ only occur if that key combination doesn't produce a char.  For example the 'a' key will produce a key up and down as well as a typed event, where the left-arrow will only produce the up and down events.

**Comment by PASTJL** [comment]
Thanks for the advice ( getKeyCode).
On my configuration the 'a' key and arrows keys don't produce a key event.

**Comment by kwhat** [comment]
This maybe solved by #170.  Please test the new to be released version.

**Comment by kwhat** [comment]
This should be solved with 2.2.0, please reopen if the issue persists.
