### ISSUE TITLE
Dead keys

### ISSUE THREAD

**Issue by BBric** [kwhat/jnativehook#138]
On my keyboard i have a "dead key" for a circumflex accent (^) or a tremulous (¨) with shift, press this key modify the next valid character pressed, but when this key is pressed i have the result : 

```
￿ // keychar
26 // keycode (open bracket)
65106 // rawcode
```
And the next character is the base character. How you can detect this type of key with JNativeHook ?

**Comment by kwhat** [comment]
It is probably the result of a bug because I have not been able to test these situations with my U.S. keyboard.  If you cant provide more information, I can help resolve the issue.

Which operating system are you using?  

Can you provide the Debug logging console output?  See https://github.com/kwhat/jnativehook/wiki/ConsoleOutput for enabling the debug log level.

The raw code for each event as well as that event type would also help.

Thanks.

**Comment by BBric** [comment]
I use a AZERTY french keyboard (Logitech) and Ubuntu 14.04.

```
déc. 18, 2016 11:19:10 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFOS: hook_event_proc [266]: Key 0X1A pressed. (0XFE52)
pressed, ￿, 26, 65106 // ^
INFOS: hook_event_proc [329]: Key 0X1A released. (0XFE52)
released, ￿, 26, 65106 // ^
INFOS: hook_event_proc [266]: Key 0X10 pressed. (0X61)
pressed, ￿, 16, 97 // a
INFOS: hook_event_proc [293]: Key 0 typed. (a)
typed, a, 0, 97 // a
INFOS: hook_event_proc [329]: Key 0X10 released. (0X61)
released, ￿, 16, 97 // a
```

**Comment by Tinytimrob** [comment]
Had a user of one of my apps report this today - seems to still be broken. (Windows 10 x64)

After calling GlobalScreen.registerNativeHook function, the dead key is non-functional and does nothing (even in unrelated programs). It doesn't work again until calling unregisterNativeHook. I was able to confirm by just changing keyboard layouts to French AZERTY in the Control Panel. Should be easy to reproduce even with a US keyboard.

**Comment by bluelhf** [comment]
> 
> 
> Had a user of one of my apps report this today - seems to still be broken. (Windows 10 x64)
> 
> After calling GlobalScreen.registerNativeHook function, the dead key is non-functional and does nothing (even in unrelated programs). It doesn't work again until calling unregisterNativeHook. I was able to confirm by just changing keyboard layouts to French AZERTY in the Control Panel. Should be easy to reproduce even with a US keyboard.

This is still an issue -- any updates?

**Comment by kwhat** [comment]
Have you tested the latest [2.2 nightly](https://github.com/kwhat/jnativehook/suites/3847568111/artifacts/95442869)?  There was a small fix for something similar recently.  

If it is still a problem, I am going to need extensive details about how to reproduce the problem.  Ex: What keys do I press in which order for [French AZERTY](https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg) layout.

**Comment by kwhat** [comment]
Ok I've tested best I can and I think it works...

id=4,when=2914390,mask=0x0,keycode=30,rawcode=0x41 // Key down (a)
keycode_to_unicode [697]: Using keyboard layout 00000000040C040C. // French (France) keyboard layout AZERTY
id=3,when=2906609,mask=0x0,keychar=a,rawcode=65 // Key typed (a)
win_hook_event_proc [616]: Restarting Windows input hook on window event: 0X800C. // Workaround for some other unrelated issue.
id=5,when=2906718,mask=0x0,keycode=30,rawcode=0x41 // Key up (a)

id=4,when=2908218,mask=0x0,keycode=27,rawcode=0xDD // Key down (^)
keycode_to_unicode [697]: Using keyboard layout 00000000040C040C. // French (France) keyboard layout AZERTY
id=5,when=2908375,mask=0x0,keycode=27,rawcode=0xDD / Key up (^)

id=4,when=2914390,mask=0x0,keycode=30,rawcode=0x41 // Key down (a)
keycode_to_unicode [697]: Using keyboard layout 00000000040C040C. // French (France) keyboard layout AZERTY
id=3,when=2914390,mask=0x0,keychar=Γ,rawcode=65 // Key typed (â)
win_hook_event_proc [616]: Restarting Windows input hook on window event: 0X800C. // Workaround for some other unrelated issue.
id=5,when=2914468,mask=0x0,keycode=30,rawcode=0x41 // Key up (a)

There seems to be a problem with key typed events in the Java library, this was tested directly with libuiohook demo_hook.exe on the CLI.  I am looking into why there are no typed events at the java level now.

**Comment by kwhat** [comment]
Alright I just tested the Java library and it also seems to work correctly.  Make sure you run `del %tmp%\JNativeHook*` to clear out any older versions of the native library.
