### ISSUE TITLE
Clarification : launching with java -jar doesn't run

### ISSUE THREAD

**Issue by PASTJL** [kwhat/jnativehook#140]
It seems that native library can't be load using java -jar ...

**Comment by kwhat** [comment]
Hi,

It should but it will depend on the platform.  Can you provide more information?

**Comment by PASTJL** [comment]
My configuration
Windows 10, jdk Oracle 1.8_111, jnativehook beta 2.1 Binary 9th December
a classic ( without native libs)  java executable jar application starts correctly with the META-INF/MANIFEST.MF file correctly configured ( Class-Path and Main-Class).
With a native library like jnativehook.dll, i got in French:
"Impossible de trouver ou de charger la classe <full-name-classe>"
Impossible to find or load the class <full-qualified-name-classe>
The application runs correctly with the classic launcher java <options> <Main-Class>

So, it is certainly more a pure java problem than a jnativehook issue.

**Comment by kwhat** [comment]
> The application runs correctly with the classic launcher java

I am having a hard time understanding what you mean by this. Are you saying "a classic ( without native libs) java executable jar" as in one that you complied locally without access to a native dll inside the jar?

**Comment by PASTJL** [comment]
Sorry for my poor English. I mean by classic application jar, just a kind of Hello Word that doesn't need native lib.

**Comment by kwhat** [comment]
Can you provide an error message or output?

**Comment by abc123me** [comment]
Works fine for me, are you sure its not a problem with how you're compiling it

**Comment by PASTJL** [comment]
Sorry for the delay. I will retry soon. Have you  test with the demos of jnativehook ?




Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : Jeremiah Lowe <notifications@github.com> 
Date : 27/01/2017  21:06  (GMT+01:00) 
À : kwhat/jnativehook <jnativehook@noreply.github.com> 
Cc : PASTJL <jean-louis.pasturel@orange.fr>, Comment <comment@noreply.github.com> 
Objet : Re: [kwhat/jnativehook] Clarification : launching with java -jar
  doesn't run (#140) 

Works fine for me, are you sure its not a problem with how you're compiling it

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kwhat/jnativehook","title":"kwhat/jnativehook","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kwhat/jnativehook"}},"updates":{"snippets":[{"icon":"PERSON","message":"@abc123me in #140: Works fine for me, are you sure its not a problem with how you're compiling it"}],"action":{"name":"View Issue","url":"https://github.com/kwhat/jnativehook/issues/140#issuecomment-275761347"}}}

**Comment by abc123me** [comment]
I haven't had any problems with compiling and running as a jar
________________________________

**Comment by PASTJL** [comment]
Ok. Can you please copy and paste your MANIFEST.MF? This file is not big.Thank you 


Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : Jeremiah Lowe <notifications@github.com> 
Date : 30/01/2017  18:04  (GMT+01:00) 
À : kwhat/jnativehook <jnativehook@noreply.github.com> 
Cc : PASTJL <jean-louis.pasturel@orange.fr>, Comment <comment@noreply.github.com> 
Objet : Re: [kwhat/jnativehook] Clarification : launching with java -jar
  doesn't run (#140) 





I haven't had any problems with compiling and running as a jar

________________________________

**Comment by abc123me** [comment]
Sure, Here it is

Ignore the package name :)


________________________________

**Comment by kwhat** [comment]
Can you provide the console output of the error or the error message? I strongly suspect that you have compiled the Java files but not the native C files.

**Comment by PASTJL** [comment]
Ok that runs for me also.
What i tried to do is to load the jnativehook.jar packaged in my application.jar ( a jar in a jar : possible perhaps with OneJar ). After modifying my MANIFEST.MF as below 
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: Jean-Louis
Class-Path: ../lib/jnativehook-2.1.0.jar
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121
Main-Class: com.jlp.whatido.MyMouseKeyboardListener

the lib/nativehook-2.1.0.jar is outside my jar application.
Sorry for the noise. I close this issue.

**Comment by PASTJL** [comment]
To complete my explanation,
I don't compile the JNI and native C code, i use directly the nightly snapshots of jnativehook...
I am very lazy ;-)
