### ISSUE TITLE
Problem using KeyListener after MouseListener

### ISSUE THREAD

**Issue by Peiki** [kwhat/jnativehook#141]
Hello, I've been trying to implement a NativeKeyListener after a NativeMouseInputListener where the user has to click wherever he wants to on the screen.
However, after the click, the keys typed on the keyboard doesn't work anymore, I tried many ways but i'm not able to understand how to fix this.
If I do the opposite (with a key input before a mouse input), only the key input works and the mouse input doesn't work anymore.

The code is like this:

MouseListener:

	Gui gui;
    public void nativeMouseClicked(NativeMouseEvent e){
    	try{
    		GlobalScreen.removeNativeMouseListener(this);
			new KeyListener(gui,e.getPoint().getX(),e.getPoint().getY());
		}catch (Exception e1) {
			e1.printStackTrace();
		}
    }
    public MouseListener(Gui gui){
    	this.gui=gui;
        try{
            GlobalScreen.registerNativeHook();
            GlobalScreen.addNativeMouseListener(this);
        }catch (NativeHookException e){
        	e.printStackTrace();
        }
        disableOutput();
    }

KeyListener:

    boolean run=false;
	Robot mouse;
	Gui gui;
	int clickX,clickY;
    public void nativeKeyPressed(NativeKeyEvent event){
        if(event.getKeyCode()==NativeKeyEvent.VC_2)
        	System.exit(0);
        else if(event.getKeyCode()==NativeKeyEvent.VC_5){
        	if(!run){
        		gui.getStatuslbl().setForeground(Color.GREEN);
        		gui.getStatuslbl().setText("RUNNING");
        	}
        	else{
        		gui.getStatuslbl().setForeground(Color.RED);
        		gui.getStatuslbl().setText("WAITING");
        	}
        	run=!run;
        }
    }
    public KeyListener(Gui gui,double clickX,double clickY)throws AWTException{
    	this.clickX=(int)clickX;
    	this.clickY=(int)clickY;
    	System.out.println("X= "+clickX);
    	System.out.println("Y= "+clickY);
    	this.gui=gui;
		mouse=new Robot();
		mouse.setAutoDelay(5);
          try {
			GlobalScreen.registerNativeHook();
		} catch (NativeHookException e){
			e.printStackTrace();
		}
        GlobalScreen.addNativeKeyListener(this);
        start();
    }

Thank you for your time, I really find your library helpful.

**Comment by kwhat** [comment]
Your approach is making your problem harder than it needs to be.  Both the mouse and key events are always registered and dispatched by the native library regardless of listeners.  You should be able to dynamically add and remove listeners from the library without restarting the hook.  You would probably benefit from your own application dependent signaling for the click state.
