### ISSUE TITLE
Could you add a method to detect if shift or ctrl is pressed

### ISSUE THREAD

**Issue by abc123me** [kwhat/jnativehook#143]

**Comment by kwhat** [comment]
Do a little reading about bit masks and then take a look at https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeInputEvent.java#L180 and https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeInputEvent.java#L103

Hope that helps.

**Comment by abc123me** [comment]
thanks, helps me a lot

**Comment by ghost** [comment]
``` java
private boolean isShiftDown( final NativeKeyEvent e ) {
  return (e.getModifiers() & SHIFT_MASK) != 0;
}
```
