### ISSUE TITLE
Question. What is the licence of JNativeHook GPL or LGPL?

### ISSUE THREAD

**Issue by PASTJL** [kwhat/jnativehook#146]
I have almost finished a little tool ( 2 Classes and 2000 loc only) using JNativeHook, and before uploading it to GitHup, i want to use the same licence as JNativeHook.
The tool shows  transparent images of the mouse in top of all applications ( thanks to java FX framework, a limitation with windows pop up menus that are always on top) and shows mouse events (button pressed, wheel rotation)  and keyboard/modifiers/control keys.
For French AZERTY keyboard, i have add the sound spelling the events in French.
Tested only on Windows ( it depends on the port of Java FX on Linux and Darwin)
It would be use for live demos of an application or to record videos tutorials showing all what you do with the mouse and keyboard.

**Comment by kwhat** [comment]
Hi,

It is covered under both the GPL and LGPL.  The LGPL is really just an extension of the GPL that allows a developer to us a GPL library without requiring the GPL for their program.  The LGPL basically states, that as long as you use the library without modification, you do not need to release your source code.

Hope that helps, let me know if you have any questions.

**Comment by PASTJL** [comment]
Ok thanks.
I will put a message here when my tool will be in githup.
i close this thread
