### ISSUE TITLE
Mac and Windows not syncronised

### ISSUE THREAD

**Issue by ojsdude** [kwhat/jnativehook#150]
Hi there,

I am using your class to help with recording key presses to control a drone, and it was working really well until recently we found that some of the keys don't match up on mac and windows; for example "Space" on windows is actually "␣" on Mac when we are using the NativeKeyEvent.getKeyText(e.getKeyCode()) command (even though e.getKeyCode() is the same). We can't use the keyCode directly because we are taking input from users to specify the controls.

Hopefully you can help,

Oliver

**Comment by ojsdude** [comment]
Ideally we would like a way to convert from 'keyEvent' to 'NativeKeyEvent'. If this is possible that would be amazing

**Comment by kwhat** [comment]
Good morning,

I have only finished half a cup of coffee so I don't quite understand the first issue, however, it sounds like the second issue is at last partially covered by the [org.jnativehook.keyboard.SwingKeyAdapter](https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/keyboard/SwingKeyAdapter.java).  That adapter and its mouse listener counter parts will go from NativeInputEvent's to InputEvent's in Java.  I will swing back around to the other part of your question in another 12oz ;)

**Comment by kwhat** [comment]
Hi Oliver, 

One more thing, can you put the app into log level debug, and send me the console output of the lines in keys in question on both platforms.  That will help me determine what is happening on each platform.  I am working on a new approach to use Java's InputEvent's for version 3, which was the original goal of this library at v1, but it was to difficult at the time to get things working due to the component requirement of all input events.

**Comment by ojsdude** [comment]
Hi Alex,

Sorry for the lack of clarity; what we have got is an input that takes keypresses and saves the value:

**Comment by ojsdude** [comment]
Hi Alex,

Sorry for the lack of clarity; what we have got is an input that takes a keypress on a Java textField and inputs the name in the field:
```
final EventHandler<KeyEvent> keyEventHandler = new EventHandler<KeyEvent>() {
    public void handle(final KeyEvent keyEvent) {
        textField.setText(keyEvent.getCode().getName());
    }
};
```
this is then saved as a value for later on.

We use jnative hook to listen to key events later on and we want to be able to compare them directly to the keys that the user pressed before to set them to the value, but when we use the nativeKeyPressed function, some of the values don't match up when we use: `NativeKeyEvent.getKeyText(e.getKeyCode())` we also tried with the keyCode but they don't match up all of the time either. This is the solution we have so far:

```
String codeString = NativeKeyEvent.getKeyText(e.getKeyCode());
// Temp fix for inconsistencies between NativeKeyEvent and the Java Key event
if(codeString.contains("Shift")){
    codeString = "Shift";
}
if(codeString.contains("Control")){
    codeString = "Ctrl";
}
if(codeString.equals("␣")){
    codeString = "Space";
}
if(codeString.equals("←")){
    codeString = "Left";
}
if(codeString.equals("→")){
    codeString = "Right";
}
if(codeString.equals("↑")){
    codeString = "Up";
}
if(codeString.equals("↓")){
    codeString = "Down";
}
if(codeString.equals("⏎")){
    codeString = "Enter";
}
processKeyPress(codeString);
```

I hope this is clearer.

Thanks,

Oliver

**Comment by kwhat** [comment]
Hi Oliver,

I think what you are describing are the AWT Toolkit property differences between Windows and OS X.  You should be able to override these values with a custom [Toolkit ](https://docs.oracle.com/javase/7/docs/api/java/awt/Toolkit.html). All available properties are in [NativeKeyEvent.java](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L593)
