### ISSUE TITLE
nativeKeyTyped issue

### ISSUE THREAD

**Issue by nguyenphongpla** [kwhat/jnativehook#151]
I want my app to catch string when typing. I have a label when typing the label will display what I typed as a string. I try to use nativeKeyTyped but I does not working. 
my code looks like:

`public void nativeKeyTyped(NativeKeyEvent nke) {
       String input = lbText.getText();
       if (nke.getRawCode() == 8) {
             if (!input.isEmpty()) {
                    lbText.setText(input.substring(0, input.length() - 1));
              }
         } else {
      lbTextsetText(input + nke.getKeyText(nke.getKeyChar()));
 }`

Im don't know why, please help me
Sorry for my poor english.

**Comment by dyorgio** [comment]
Did you initialize jnativehook?

```java
GlobalScreen.registerNativeHook();
GlobalScreen.addNativeKeyListener(this);
```

**Comment by hendriks73** [comment]
Which OS is this on?

On OS X 10.10.5 I get two `nativeKeyReleased` events when pressing a media key, but no `nativeKeyTyped` event. Perhaps this is connected (using v2.1.0).

**Comment by kwhat** [comment]
That's because the media key does not produce a valid char to return.  Just
like with the official jvm key events, only keydown events that produce a
character code will be sent as key typed events.  Key down and key typed
events will bounce when the key is held and a single key Up will be sent on
release.

**Comment by hendriks73** [comment]
Thanks for the explanation.

> Key down and key typed
events will bounce when the key is held and a single key Up will be sent on
release.

Is there also an explanation for why I'm always getting two `nativeKeyReleased ` events?

**Comment by kwhat** [comment]
@hendriks73 Not sure why your getting two release events.  If you set the log level to debug and still get two events, it is because the OS sent two events or possibly due to deadkey bug.  Please open a new bug report with the debug output if your still having an issue.

Thanks!
