### ISSUE TITLE
Issue with AbstractMethod error - jNativeHook 2.1

### ISSUE THREAD

**Issue by Marwix** [kwhat/jnativehook#156]
**jNativeHook version 2.1.0**

I recently wrote a code that I lated obfuscated with **ProGuard**. Somehow, the jar file gives me a very strange error. The code itself works fine without obfuscation, but I would like to know why this behaviour occurs when the jar has been obfuscated. I have tried changing the obfuscation settings and see if any of them was the problem. I even tried only applying obfuscation with no extra settings, still gave me the same error.

This is the error I get everytime I press a key. 
https://puu.sh/uA4DX.png

Obfuscation settings:
https://puu.sh/uA4xL.pro

Do you have any clue why this occurs?

Thanks!

**Comment by kwhat** [comment]
It's probably occurring because the native code is looking up the Java classes, methods and properties that proguard has probably renamed for you.  Try adding an exception in proguard for the org.jnativehook namespace.

**Comment by kwhat** [comment]
Set the log level to debug and see what it complains about when the program starts and when the hook starts.

**Comment by Marwix** [comment]
Ok will post in a minute.

**Comment by Marwix** [comment]
I'm sure not how to add an exception for proguard. Do you know how to do it? I have also set the log level to debug but still recieve the same exception through the command line.

**Comment by kwhat** [comment]
I think you can do something like this:
```
-keep public class org.jnativehook.** {
  public protected private *;
}
```

**Comment by Marwix** [comment]
Will try that now. Give me a moment :)

**Comment by Marwix** [comment]
https://gyazo.com/a878ee55b55ba9822d2f22b14f0e5c84

Didn't seem to work unfortunately.

**Comment by kwhat** [comment]
The error is happening in the super class of  [DefaultDispatchService.java](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/dispatcher/DefaultDispatchService.java) but I still don't understand why based on that output.  You could try using the SwingDispatchService instead and see if you get a different error.  You can use GlobalScreen. setEventDispatcher(...) to do this.

**Comment by Marwix** [comment]
I added that to begin with but that didn't stop the error from occuring.

One thing I noticed was that if I ignored kept all classes in a package where the initalizer is, the entire jar works, however those are the files I need obfuscated. Instead, it gave me this:
https://gyazo.com/c8b44a53670eb7421aec24a2c92d93c5

**Comment by kwhat** [comment]
It cannot find the namespace and class `org/jnativehook/Keyboard/NativeKeyListener`, this is probably because pro-guard mangled the name.
