### ISSUE TITLE
JNativeHook library does not follow currently selected OS language

### ISSUE THREAD

**Issue by MoofMonkey** [kwhat/jnativehook#157]
Same as #64 
[Output of "locale -a"](http://pastebin.com/EyV4dRuK)
[Log](http://pastebin.com/mNgVfL7E)
UPD: same at windows with us/ru locales
UPD2: WTF is going on?! On linux it uses starting locale (ex. changed to AA locale - program displays all chars at AA locale, changed to BB locale -  program displays all chars at BB locale. Switching locale not helps).
Maybe bug of DLL

**Comment by MoofMonkey** [comment]
Maybe reply? 6 days since issue created.

**Comment by MoofMonkey** [comment]
Sorry for too long reply
I'm using lasted Gnome 17.04, X server + NVIDIA propietary

**Comment by kwhat** [comment]
please paste console output for the debug log level from jar start until the wrong key is pressed.

**Comment by MoofMonkey** [comment]
[Console output](http://pastebin.com/raw/AdDyxcGN)
Input is "wrong не верно"
Cannot reply at time, I'll try to reply at time tomorrow

**Comment by MoofMonkey** [comment]
I found solution (by minecraft forums ;D) - make english as 1st language in the system and all works.
