### ISSUE TITLE
[Windows] wrong NativeKeyEvent

### ISSUE THREAD

**Issue by yenon** [kwhat/jnativehook#158]
I seem to be getting a key down event every time a key is typed and no key typed events at all. I also tested on Linux and it seems to be fine there.
When Mumble is focused, you don't get any Updates at all, also it doesn't receive any input from NativeKeyEvents that are posted.
Edit: Upon further inspection, no events of any kind register when Mumble is in the foreground, they start again immediately after it loses its focus.

This appears in the log when i should receive an event:
`Mär 10, 2017 11:03:22 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: win_hook_event_proc [634]: Restarting Windows input hook on window event: 0X800C.`

Here is all code i used, maybe it's me doing something wrong. (Edit: In case you were wondering, this is Kotlin)
<details>
<summary>HookThread.kt</summary>
package util

import javafx.beans.property.SimpleObjectProperty
import org.jnativehook.GlobalScreen
import org.jnativehook.NativeHookException
import org.jnativehook.keyboard.NativeKeyEvent
import org.jnativehook.keyboard.NativeKeyListener
import org.jnativehook.mouse.NativeMouseEvent
import org.jnativehook.mouse.NativeMouseListener
import org.jnativehook.mouse.NativeMouseMotionListener
import java.util.logging.Level
import java.util.logging.Logger

object HookThread : Thread(), NativeKeyListener, NativeMouseListener, NativeMouseMotionListener {

    val mouseUpEventProperty: SimpleObjectProperty<NativeMouseEvent> = SimpleObjectProperty()
    val mouseDownEventProperty: SimpleObjectProperty<NativeMouseEvent> = SimpleObjectProperty()
    val keyUpEventProperty: SimpleObjectProperty<NativeKeyEvent> = SimpleObjectProperty()
    val keyDownEventProperty: SimpleObjectProperty<NativeKeyEvent> = SimpleObjectProperty()

    override fun run() {
        println("Starting JNativehook")
        val logger = Logger.getLogger(GlobalScreen::class.java.`package`.name)
        logger.level = Level.OFF

        // Change the level for all handlers attached to the default logger.
        val handlers = Logger.getLogger("").handlers
        for (handler in handlers) {
            handler.level = Level.OFF
        }
        try {
            GlobalScreen.registerNativeHook()
            GlobalScreen.addNativeKeyListener(this)
            GlobalScreen.addNativeMouseListener(this)
            GlobalScreen.addNativeMouseMotionListener(this)
            Runtime.getRuntime().addShutdownHook(object : Thread() {
                override fun run() {
                    println("Stopping JNativehook")
                    GlobalScreen.unregisterNativeHook()
                }
            })
        } catch (e: NativeHookException) {
            e.printStackTrace()
        }
    }

    val debug:Boolean=false

    fun printKeyEvent(prefix:String,event:NativeKeyEvent){
        if(debug) {
            println("$prefix\n" +
                    "id       : ${event.id}\n" +
                    "modifiers: ${event.modifiers}\n" +
                    "rawCode  : ${event.rawCode}\n" +
                    "keyCode  : ${event.keyCode}\n" +
                    "keyChar  : ${event.keyChar.toInt()}\n" +
                    "location : ${event.keyLocation}\n" +
                    "-------------------------")
        }
    }

    fun printMouseEvent(prefix:String,event:NativeMouseEvent){
        if(debug){
            println("$prefix\n" +
                    "id       : ${event.id}\n" +
                    "modifiers: ${event.modifiers}\n" +
                    "x        : ${event.x}\n" +
                    "y        : ${event.y}\n" +
                    "clickCnt : ${event.clickCount}\n" +
                    "button   : ${event.button}\n" +
                    "-------------------------")
        }
    }

    override fun nativeKeyTyped(nativeKeyEvent: NativeKeyEvent) {
        printKeyEvent("Typed",nativeKeyEvent)
    }

    override fun nativeKeyPressed(nativeKeyEvent: NativeKeyEvent) {
        keyDownEventProperty.value = nativeKeyEvent
        printKeyEvent("Down",nativeKeyEvent)
    }

    override fun nativeKeyReleased(nativeKeyEvent: NativeKeyEvent) {
        keyUpEventProperty.value = nativeKeyEvent
        printKeyEvent("Up",nativeKeyEvent)
    }

    override fun nativeMouseClicked(nativeMouseEvent: NativeMouseEvent) {
        printMouseEvent("Clicked",nativeMouseEvent)
    }

    override fun nativeMousePressed(nativeMouseEvent: NativeMouseEvent) {
        mouseDownEventProperty.value = nativeMouseEvent
        printMouseEvent("Down",nativeMouseEvent)
    }

    override fun nativeMouseReleased(nativeMouseEvent: NativeMouseEvent) {
        mouseUpEventProperty.value = nativeMouseEvent
        printMouseEvent("Up",nativeMouseEvent)
    }

    override fun nativeMouseMoved(p0: NativeMouseEvent) {
        printMouseEvent("Moved",p0)
    }

    override fun nativeMouseDragged(p0: NativeMouseEvent) {
        printMouseEvent("Dragged",p0)
    }
}
</details>

<details>
<summary>LibIO.kt</summary>
package lua

import org.jnativehook.GlobalScreen
import org.jnativehook.keyboard.NativeKeyEvent
import org.jnativehook.mouse.NativeMouseEvent
import org.jnativehook.mouse.NativeMouseWheelEvent
import org.luaj.vm2.LuaNumber
import org.luaj.vm2.LuaTable
import org.luaj.vm2.LuaValue
import org.luaj.vm2.Varargs
import org.luaj.vm2.lib.VarArgFunction
import java.awt.MouseInfo
import java.awt.Point

object LibIO : LuaTable() {

    init {
        set("pressKey", object : VarArgFunction() {
            override fun invoke(args: Varargs): Varargs {
                GlobalScreen.postNativeEvent(NativeKeyEvent(
                        NativeKeyEvent.NATIVE_KEY_PRESSED,
                        0,
                        0,
                        args.checkint(1),
                        NativeKeyEvent.CHAR_UNDEFINED))
                return LuaValue.NIL
            }
        })
        set("releaseKey", object : VarArgFunction() {
            override fun invoke(args: Varargs): Varargs {
                GlobalScreen.postNativeEvent(NativeKeyEvent(
                        NativeKeyEvent.NATIVE_KEY_RELEASED,
                        0,
                        0,
                        args.checkint(1),
                        NativeKeyEvent.CHAR_UNDEFINED))
                return LuaValue.NIL
            }
        })
    }
}
</details>

**Comment by yenon** [comment]
I can write a small test in Java if that helps, seeing that this issue has yet to be assigned.

**Comment by kwhat** [comment]
I am assuming this is windows?  You wouldn't be getting key typed events if I the library could not determine the natural language setting or layout.  Start the program and and take a look around the first key event and see what locale it finds.  

As far as this not working with Muble; The win_hook_event_proc [634]: Restarting Windows input hook on window event: 0X800C message is a hack to try and resolve that issue.  It seems to work sometimes but it also seems like Microsoft is changing hooking behavior and not telling anyone.  Try contacting their developers and asking them why SetWindowsHookEx with low-level mouse and keyboard input doesn't work with their application.

**Comment by yenon** [comment]
Your assumption was correct. I think this is the locale part you wanted:
`Mär 17, 2017 9:46:28 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: process_key_pressed [227]: Key 0X1D pressed. (0XA2)

Mär 17, 2017 9:46:28 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: refresh_locale_list [470]: GetKeyboardLayoutList(0, NULL) found 1 layouts.

Mär 17, 2017 9:46:28 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: refresh_locale_list [487]: Received 1 locales.

Mär 17, 2017 9:46:28 PM org.jnativehook.GlobalScreen$NativeHookThread enable
SEVERE: refresh_locale_list [628]: Could not find keyboard map for locale 0X0000000004070407!`

**Comment by yenon** [comment]
I have decided to dig a little further. You might have noticed that i'm using a german keyboard layout. Because of the missing locale, a few issues are appearing, some quite known (i've worked on linux with american layout on a german keyboard before), others completely wrong, for example the multiply key on the numpad which seems to be triggering a press of PrintScreen. Maybe it has something to do with the hardware i'm using. My main keyboard is a Razer Blackwidow with a broken bootloader and a few errors in it's firmware (thanks razer). I'll see if i can reproduce these issues on another keyboard. Other system info: I'm running an english version of Windows 8.1 with german keyboard layout set. If you need any other information, feel free to contact me.

**Comment by yenon** [comment]
I just remembered another thing: I applied a small registry tweak to disable caps lock. That might throw your application off. If you want to see the .reg files: http://www.sempervideo.de/capslock.zip

**Comment by kwhat** [comment]
I believe this issue was resolved by issue #170.  There was a memory corruption issue with the string size for the registry key.  Trunk should work, nightly coming soon.

**Comment by yenon** [comment]
May i please have a link to this? The one on the main page only has versions from January.

**Comment by kwhat** [comment]
Try the latest jar from here https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by yenon** [comment]
Thanks, did you just upload that or am i getting senile and missed it?

**Comment by kwhat** [comment]
I just got the builds working again and just uploaded.
