### ISSUE TITLE
Mouse sensitivity speeds up?

### ISSUE THREAD

**Issue by kingArchie** [kwhat/jnativehook#159]
The mouse sens speeds up when I use JNativeHook - any idea?

**Comment by kwhat** [comment]
Which platform​?

**Comment by kingArchie** [comment]
Windows - my software is only for windows. Some users are complaining that their mouse sens is speeding up whilst playing minecraft and using software which uses JNativeHook. I also use JNA and Gson - but those don't effect the mouse so I assumed it must be JNH.

**Comment by kwhat** [comment]
There are only 3 functions that inspect the mouse acceleration issue:

hook_get_pointer_acceleration_multiplier
hook_get_pointer_acceleration_threshold
hook_get_pointer_sensitivity

https://github.com/kwhat/libuiohook/blob/1.1/src/windows/system_properties.c#L157

These functions all do roughly the same thing, call SystemParametersInfo and read the info.  I don't do much else aside from installing a hook via SetWindowsHookEx(WH_MOUSE_LL, but that shouldn't affect acceleration or sensitivity.

**Comment by kingArchie** [comment]
Hmm okay - thank you.

**Comment by kwhat** [comment]
Try and gather a bit more info about their mouse sensitivity.  Are they using some special software?
 Maybe the program is disrupting something proprietary by reading those elements in that way.

**Comment by kingArchie** [comment]
The client said it automatically fixed. 

Thank you for your time.

**Comment by kwhat** [comment]
Awesome, no worries.
