### ISSUE TITLE
How can i get working the library in a service in linux?

### ISSUE THREAD

**Issue by hectomg** [kwhat/jnativehook#162]
Hello, I was trying to run a jar file with the library in a service but it always get an error:

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdf8fb517d4, pid=10345, tid=0x00007fdfdffc9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libX11.so.6+0x8d7d4]  XkbGetUpdatedMap+0x4

After so many tests I have found that it happens because a service run a process with no $DISPLAY element, I mean, it has no access to a display and I have seen the library register a listener to the "screen" so i think it is the origin of the error. So I would like to know how can I run that library with no display access in my service. 

Regards,

**Comment by kwhat** [comment]
Hi,

For some reason the libX11 library segfaulted on your computer.  If you do not have a display, does that mean you are running outside of X11?  X11 is currently required for support on linux.

**Comment by kwhat** [comment]
Can you attach the full log for the dump?  it should be err#####.log or something like that in the folder where you ran the jar.

**Comment by hectomg** [comment]
Hi, thanks for your response.
Yes! I have libX11 in my computer, Im using Ubuntu 16.04 with unity interface.

As I told you before it looks like a service can load correctly the library but it runs in the background, inside a scope where $DISPLAY doesn't exists. I run directly a bash script like "sh ./myScript.sh" and it works correctly! $DISPLAY has a value like ":0" but when I run that script from a system service it do not works and $DISPLAY doesn't exists.

**Comment by kwhat** [comment]
The library currently needs to run with an active screen as a userland process.  The information is available as a system service, however, the library only utilizes the userland access at this time.  I will take a look at alternatives as part of issue #163.

**Comment by dyorgio** [comment]
@hectomg, as @kwhat said this library runs on user land space, if you is running it as a service, you need to create a sub-process to runs as target user.
Take a look in this issue for a possible solution: https://github.com/dorkbox/SystemTray/issues/63
