### ISSUE TITLE
Detect lower case

### ISSUE THREAD

**Issue by kevlarinxp** [kwhat/jnativehook#165]
The Example show me all letters of my keyboard in upper case but... how can I detect lower case?
Thank you for answer ;)

**Comment by kwhat** [comment]
Get key text is case sensitive on key typed events.

**Comment by kevlarinxp** [comment]
Yes but how Do I do it? I have this...
System.out.println("Key pressed: " + NativeKeyEvent.getKeyText(e.getKeyCode()));

And it takes all letters like uppercase :/

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L403

**Comment by kwhat** [comment]
You can use getKeyChar() on any key typed events to check for lower or upper case.

**Comment by HouariZegai** [comment]
Using **getKeyChar** in **nativeKeyTyped** method doesn't work,
it's don't print anything!

**Comment by robinjos333** [comment]
I am also looking for the how to detect lowercase letters. Using getKeyChar method which prints like this " ￿ " .

**Comment by robinjos333** [comment]
```
public void nativeKeyTyped(NativeKeyEvent nativeKeyEvent) {
     logger.info("Key typed : " +nativeKeyEvent.getKeyChar());
}
```
Worked for me

**Comment by HouariZegai** [comment]
Thanks @robinjos333, the issue has been solved!
