### ISSUE TITLE
[HELP Required] How to use the GlobalScreen.postNativeEvent(); method

### ISSUE THREAD

**Issue by TheAppService** [kwhat/jnativehook#167]
Hello,

since there is no entry in the wiki, nor I was able to figure this out through the documentation, would it be possible to give a short example of how to use the GlobalScreen.postNativeEvent(); method ? (So what exactly needs to be passed and how to create this NativeInputEvent object and how the parameters should be used).
(I want so simulate a Keyboard Pressing of Media Keys)

Best regards and thanks for answers in advance!

Daniel

**Comment by kwhat** [comment]
Hi Daniel,

You should be able to construct a native input object directly and pass 
it to that function.  If I remember correctly, key typed events are 
ignored and all modifier keys are applied for the single events.  It's 
still a little experimental, so if you encounter problems please let me 
know.

Best,

Alex

**Comment by TheAppService** [comment]
Hey Alex,

thanks for your quick answer! You solved my problem.
The posting of native keys works fine as far as I can tell!
In case anyone's interested, here's my code for the three media keys:

`    public static void main(String[] args) {
        try {
			GlobalScreen.registerNativeHook();
		} catch (NativeHookException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
}
//Those methods can be called afterwards
    public static void MediaKeyForward(){
	    GlobalScreen.postNativeEvent(new NativeKeyEvent(2401,0,176,57369,org.jnativehook.keyboard.NativeKeyEvent.CHAR_UNDEFINED));

    }
    public static void MediaKeyBack(){
	    GlobalScreen.postNativeEvent(new NativeKeyEvent(2401,0,177,57360,org.jnativehook.keyboard.NativeKeyEvent.CHAR_UNDEFINED));

    }
    public static void MediaKeyPause(){
   	 GlobalScreen.postNativeEvent(new NativeKeyEvent(2401,0,179,57378,org.jnativehook.keyboard.NativeKeyEvent.CHAR_UNDEFINED));
	
    }

`

Many thanks and best regards

Daniel
