### ISSUE TITLE
Add Maven version artifacts (debug, java5, java7 & javafx)

### ISSUE THREAD

**Issue by dyorgio** [kwhat/jnativehook#169]
Include in release a new artifact with classifier tag (I propose "debug") to help to test this library, ex:

```xml
<dependency>
    <groupId>com.1stleg</groupId>
    <artifactId>jnativehook</artifactId>
    <version>2.1.0</version>
    <classifier>debug</classifier>
</dependency>
```

**Comment by kwhat** [comment]
Hi,

Thank you for your bug report.  Can you add a little context, I am not that familiar with Maven.

Thanks

**Comment by dyorgio** [comment]
Ok!
According with http://maven.apache.org/pom.html

> * classifier:
> The classifier allows to distinguish artifacts that were built from the same POM but differ in their content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number.
> As a motivation for this element, consider for example a project that offers an artifact targeting JRE 1.5 but at the same time also an artifact that still supports JRE 1.4. The first artifact could be equipped with the classifier jdk15 and the second one with jdk14 such that clients can choose which one to use.
> 
> Another common use case for classifiers is the need to attach secondary artifacts to the project's main artifact. If you browse the Maven central repository, you will notice that the classifiers sources and javadoc are used to deploy the project source code and API docs along with the packaged class files.

Deploy comand: http://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-classifiers.html

**Comment by kwhat** [comment]
As I understand it, there should be different jar files?  One for debug and the other without.  Please let me know if that is correct, thanks!

**Comment by dyorgio** [comment]
Yes! Two different artifacts. Exactly as you said.

**Comment by kwhat** [comment]
I will do a split in v3.

**Comment by kwhat** [comment]
This should be done in 2.2 with the maven migration.
