### ISSUE TITLE
KeyTyped not working on jnativehook-2.1.0.jar

### ISSUE THREAD

**Issue by doppelgunner** [kwhat/jnativehook#171]
Im usng java 8 and jnativehook-2.1.0.jar
The KeyTyped is not working only KeyPressed and KeyReleased. I need to for example determine which happened first for example shift + A. I need it on a specific order SHIFT then A. Sometimes when I used the KeyReleased people has a habit of releasing A first before SHIFT so it becomes A then SHIFT. I hope you fixed this issue I really need the KeyTyped for my Keyboard Snooper program. Here is the link to my youtube tutorial playlist: [Keyboard Snooper playlist](https://www.youtube.com/watch?v=QcEAiVRO6xk&list=PLlRMSK1suXjNzJYi2LFrcizgV9mSUto6x)

Also, I like your library keep it up. I was able to do my program because of you guys

**Comment by kwhat** [comment]
Hi,

Can you set the log level to debug and check issue #170.  I suspect that the bug resolved in this issue is why you are not getting key typed events.

Best,
Alex

**Comment by doppelgunner** [comment]
So this popped up in the logger. can you help me solve this? I don't know what this means.
![screenshot 62 _li](https://cloud.githubusercontent.com/assets/10264898/26483003/334043ec-421d-11e7-8b3c-17f81f307267.jpg)

**Comment by kwhat** [comment]
Yup, that is what #170 addressed.  I am going to try and make a build this weekend if I can make some time.  Things are going to be a little hectic until at least Monday.

**Comment by kwhat** [comment]
The fix is already in the 2.1 trunk if you want to build from src.

**Comment by doppelgunner** [comment]
Thanks check it out in the future if im not busy. Really like the library.

**Comment by kwhat** [comment]
I have released a nightly in the maven snapshot repo.

**Comment by gpotter2** [comment]
@kwhat Hi.
I know that you've been struggling with this, but I still got the bug (i'm using the latest released version).
```
nov. 23, 2017 10:19:37 PM org.jnativehook.GlobalScreen$NativeHookThread enable
GRAVE: refresh_locale_list [628]: Could not find keyboard map for locale 0X00000000040C040C!

nov. 23, 2017 10:19:37 PM org.jnativehook.GlobalScreen$NativeHookThread enable
GRAVE: refresh_locale_list [628]: Could not find keyboard map for locale 0X0000000008090809!

nov. 23, 2017 10:19:37 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFOS: process_key_released [286]: Key 0X21 released. (0X46)
```
any updates ?
