### ISSUE TITLE
Native Mouse Event getWhen() returning only 0

### ISSUE THREAD

**Issue by Strongkong** [kwhat/jnativehook#172]
> Version: 2.1.0, Java 8_131

Dear everyone,
I am writing a program that needs somewhat more precise recording and playback of mouse events, so I figured I would call the _getWhen()_ function to save the exact time when the event happened, instead of calling _System.currentTimeMillis()_, since it gets called while saving, having a bit of a delay.
Now I am not sure, I might have missed something, but whenever I try to call _getWhen()_, I just get  0.
`long t = System.currentTimeMillis(); `
 `System.out.println("Time: " + t + ", When: " + nme.getWhen());`

Where nme is a NativeMouseEvent.
Output is: 

> Time: 1495977378907, When: 0

Regardless of whether I click or move the mouse or anything. 
The program works fine with System.currentTimeMillis(), but there is some noticable delay that I measured that I want to cut.
Any ideas whether it's a bug or I'm missing something?
Thank you,
Strongkong

**Comment by kwhat** [comment]
Hi @Strongkong,

So the "time" time source used by 2.1 was switched away from Unix time to the native event time source.  You should still receive a number, it is just not the time.  What platform are you getting zero on?  Are you constructing the event, or is it received from the dispatcher like that?

Thanks,
Alex

**Comment by Strongkong** [comment]
Hi @Alex,
I am using Windows 8.1 Enterprise, 64bit, and I am getting absolutely zero everywhere, and the event I am getting is "natural" from a NativeMouseListener, I am not modifying it at any point. Everything else regarding the listener works, except the time one, but I need the 2.1.0 version because of the ability to convert from NativeKeyEvent to KeyEvent. (Note: I am not converting it at this point, so that probably isn't the problem)
Class:
> public class JavaMouseHook implements NativeMouseListener

Function:
> public void nativeMousePressed(NativeMouseEvent nme)

Thanks for your reply,
Strongkong

**Comment by khanhtd36** [comment]
I had the same prolem when use JNativeHook 2.1.0 in Windows 7 64bit

**Comment by kwhat** [comment]
Hm, I will take a look, I assume by "I am getting absolutely zero everywhere" you are saying that all of the event data is zero?  Is the event delivered?  Also which JRE version?

**Comment by kwhat** [comment]
Oh also, if you can set the log level to debug, that may help isolate where the issue maybe.

**Comment by kwhat** [comment]
Ok, I have confirmed that this is still an issue.

**Comment by kwhat** [comment]
2.2.2 switched back to the timestamp.  I cannot duplicate the zero issue with or without the timestamp change so I am going to call this closed.  If you are still having a problem, please reopen.
