### ISSUE TITLE
Backspace cant be detected

### ISSUE THREAD

**Issue by DevilLordAero** [kwhat/jnativehook#173]
Hi whats wrong with my code, i tryed alot time but not working, the back space it not deleting my last char from  worldName
`package org.redeagle.keymapper;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.dispatcher.SwingDispatchService;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;

public class Main extends JFrame implements NativeKeyListener, WindowListener {
	Boolean onState;
	public JLabel lblWorldName;
	String worldName = "";
	public Main() {
		onState = false;
		getContentPane().setBackground(Color.BLACK);
		getContentPane().setForeground(Color.BLACK);
		// Set the event dispatcher to a swing safe executor service.
		GlobalScreen.setEventDispatcher(new SwingDispatchService());

		setTitle("JNativeHook Swing Example");
		setSize(557, 131);
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(this);
		getContentPane().setLayout(null);
		
		lblWorldName = new JLabel("World : ");
		lblWorldName.setForeground(Color.WHITE);
		lblWorldName.setBackground(Color.WHITE);
		lblWorldName.setFont(new Font("Tahoma", Font.PLAIN, 35));
		lblWorldName.setBounds(10, 11, 521, 71);
		getContentPane().add(lblWorldName);
		setVisible(true);
	}

	public void windowOpened(WindowEvent e) {
		// Initialze native hook.
		try {
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
			System.err.println("There was a problem registering the native hook.");
			System.err.println(ex.getMessage());
			ex.printStackTrace();

			System.exit(1);
		}

		GlobalScreen.addNativeKeyListener(this);
	}

	public void windowClosed(WindowEvent e) {
		//Clean up the native hook.
		try {
			GlobalScreen.unregisterNativeHook();
		} catch (NativeHookException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		System.runFinalization();
		System.exit(0);
	}

	public void windowClosing(WindowEvent e) { /* Unimplemented */ }
	public void windowIconified(WindowEvent e) { /* Unimplemented */ }
	public void windowDeiconified(WindowEvent e) { /* Unimplemented */ }
	public void windowActivated(WindowEvent e) { /* Unimplemented */ }
	public void windowDeactivated(WindowEvent e) { /* Unimplemented */ }

	public void nativeKeyReleased(NativeKeyEvent e) {	
		if(onState == true && e.getKeyCode() == 62) {
				worldName.substring(0, worldName.length()-1);
				lblWorldName.setText("World: " + worldName);
		}
	}

	public void nativeKeyPressed(NativeKeyEvent e) { 
		if(e.getKeyCode() == NativeKeyEvent.VC_F6) {
			worldName = "";
			lblWorldName.setText("World: " + worldName);
			onState = true;
			System.out.println("Key Started");
		}
		if(onState == true && e.getKeyCode() == NativeKeyEvent.VC_ENTER) {
			onState = false;
			System.out.println("Key Ended");
		}
		
		if(onState == true && e.getKeyCode() == 62) {
				worldName.substring(0, worldName.length()-1);
				lblWorldName.setText("World: " + worldName);
		}
		if(onState == true && (e.getKeyCode() == NativeKeyEvent.VC_A
				|| e.getKeyCode() == NativeKeyEvent.VC_B
				|| e.getKeyCode() == NativeKeyEvent.VC_C
				|| e.getKeyCode() == NativeKeyEvent.VC_D
				|| e.getKeyCode() == NativeKeyEvent.VC_E
				|| e.getKeyCode() == NativeKeyEvent.VC_F
				|| e.getKeyCode() == NativeKeyEvent.VC_G
				|| e.getKeyCode() == NativeKeyEvent.VC_H
				|| e.getKeyCode() == NativeKeyEvent.VC_I
				|| e.getKeyCode() == NativeKeyEvent.VC_J
				|| e.getKeyCode() == NativeKeyEvent.VC_K
				|| e.getKeyCode() == NativeKeyEvent.VC_L
				|| e.getKeyCode() == NativeKeyEvent.VC_M
				|| e.getKeyCode() == NativeKeyEvent.VC_N
				|| e.getKeyCode() == NativeKeyEvent.VC_O
				|| e.getKeyCode() == NativeKeyEvent.VC_P
				|| e.getKeyCode() == NativeKeyEvent.VC_Q
				|| e.getKeyCode() == NativeKeyEvent.VC_R
				|| e.getKeyCode() == NativeKeyEvent.VC_S
				|| e.getKeyCode() == NativeKeyEvent.VC_T
				|| e.getKeyCode() == NativeKeyEvent.VC_U
				|| e.getKeyCode() == NativeKeyEvent.VC_V
				|| e.getKeyCode() == NativeKeyEvent.VC_W
				|| e.getKeyCode() == NativeKeyEvent.VC_X
				|| e.getKeyCode() == NativeKeyEvent.VC_Y
				|| e.getKeyCode() == NativeKeyEvent.VC_Z
				|| e.getKeyCode() == NativeKeyEvent.VC_1
				|| e.getKeyCode() == NativeKeyEvent.VC_2
				|| e.getKeyCode() == NativeKeyEvent.VC_3
				|| e.getKeyCode() == NativeKeyEvent.VC_4
				|| e.getKeyCode() == NativeKeyEvent.VC_5
				|| e.getKeyCode() == NativeKeyEvent.VC_6
				|| e.getKeyCode() == NativeKeyEvent.VC_7
				|| e.getKeyCode() == NativeKeyEvent.VC_8
				|| e.getKeyCode() == NativeKeyEvent.VC_9
				|| e.getKeyCode() == NativeKeyEvent.VC_0)) {
			worldName += NativeKeyEvent.getKeyText(e.getKeyCode());
			lblWorldName.setText("World: " + worldName);
		}			
	}
	public void nativeKeyTyped(NativeKeyEvent e) { 
		
	}
	
	public static void main(String[] args) {
		 SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new Main();
			}
		});
	}
}`

**Comment by kwhat** [comment]
What are you trying to do?

**Comment by kwhat** [comment]
I am not seeing any backspace check in your code.

**Comment by DevilLordAero** [comment]
if(onState == true && e.getKeyCode() == 62) {
			worldName.substring(0, worldName.length()-1);
			lblWorldName.setText("World: " + worldName);
	}
62 is backspace key code right? i tried too e.getKeyCode() == NativeKeyEvent.VC_BACKSPACE is not working

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L151 is 0x0E or 14, not 62.  You may also want to look at https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/keyboard/SwingKeyAdapter.java
