### ISSUE TITLE
Build JnativeHook.dll in visual studio

### ISSUE THREAD

**Issue by nrusingh-auroin** [kwhat/jnativehook#174]
Hi, 
I want to build JnativeHook.dll in visual studio,
kindly suggest me the steps, I should follow.
Thanks

**Comment by kwhat** [comment]
I don't have support for VisualStudio in this library quite yet.  I am still working on the cmake file located in libuiohook master.  It reportedly works in VisualStudio, but I have not tested it.  You will probably need to specify the compiler, linker and cflags in the build properties file.

**Comment by kwhat** [comment]
Everything should build with visual studio as of 2.2

**Comment by kwhat** [comment]
The Windows toolchain has been fully supported in 2.2 via cmake.
