### ISSUE TITLE
Compile-jni

### ISSUE THREAD

**Issue by nrusingh-auroin** [kwhat/jnativehook#175]
Hi,
I am getting error while compile-jni using MingW64.
Please note I follwed each step provided in wiki.
My system is having Windows 7 OS - 64bit
This is the error I'm getting:
`AuroIN@AuroIN-PC MINGW64 /d/Mitu_Auroin/Eclipse Workspace/JNativeHookTest2 (master)
$ ant compile-jni
Buildfile: D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\build.xml

init:
     [echo] Initializing local build environment...
     [echo] Project:            jnativehook 2.1.20170608
     [echo] Debug:              false
     [echo] Java Compiler:      modern
     [echo] Java Source:        1.8
     [echo] Java Target:        1.8
     [echo] Java Include:       C:/Program Files/Java/jdk1.8.0_102/include
     [echo] Java Args:
     [echo] Native Lib:         JNativeHook.dll
     [echo] Native OS:          windows
     [echo] Native Arch:        x86_64
     [echo] Native Toolchain:   gcc
     [echo] Native CFLAGS:      -O2 -pipe
     [echo] Native LDFLAGS:
[propertyfile] Creating new property file: D:\Mitu_Auroin\Eclipse Workspace\JNativeHook                                                                                                         Test2\build.properties

download-libuiohook:

bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...

BUILD FAILED
D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\build.xml:344: Problem: failed to cre                                                                                                         ate task or type autoreconf
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

Total time: 0 seconds
`

Also note I've made change in build.xml (line ~ 167):
`
		<typedef resource="net/sf/antcontrib/antlib.xml" classpath="${dir.dist}/ant-contrib-1.0b3.jar" onerror="failall" />
`
[Note: compile-java is running perfect]

please help.
Thank you.

**Comment by kwhat** [comment]
You need to add the [JNITasks](https://github.com/kwhat/jnitasks) Ant library to the root of the project.  See the [Wiki](https://github.com/kwhat/jnativehook/wiki/Compiling) for more information.

**Comment by nrusingh-auroin** [comment]
Thanks kWaht,
please check this error:
`AuroIN@AuroIN-PC MINGW64 /d/Mitu_Auroin/Eclipse Workspace/JNativeHookTest2 (master)
$ ant compile-jni
Buildfile: D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\build.xml

init:
     [echo] Initializing local build environment...
     [echo] Project:            jnativehook 2.1.20170609
     [echo] Debug:              false
     [echo] Java Compiler:      modern
     [echo] Java Source:        1.8
     [echo] Java Target:        1.8
     [echo] Java Include:       C:/Program Files/Java/jdk1.8.0_102/include
     [echo] Java Args:
     [echo] Native Lib:         JNativeHook.dll
     [echo] Native OS:          windows
     [echo] Native Arch:        x86_64
     [echo] Native Toolchain:   gcc
     [echo] Native CFLAGS:      -O2 -pipe
     [echo] Native LDFLAGS:
[propertyfile] Creating new property file: D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\build.properties

download-libuiohook:
     [echo] Downloading libUIOHook source...
      [get] Getting: https://github.com/kwhat/libuiohook/archive/master.zip
      [get] To: D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\bin\libuiohook-master.zip
      [get] https://github.com/kwhat/libuiohook/archive/master.zip moved to https://codeload.github.com/kwhat/libuiohook/zip/master
      [get] ....................................................
      [get] ....................................................
      [get] .....
    [unzip] Expanding: D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\bin\libuiohook-master.zip into D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\src\libuiohook

bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...
[autoreconf] autoreconf --verbose --force --install
[autoreconf] sh: autoreconf: command not found

BUILD FAILED
D:\Mitu_Auroin\Eclipse Workspace\JNativeHookTest2\build.xml:345: exec returned: 127

Total time: 15 seconds
`

Please suggest.

**Comment by kwhat** [comment]
You are not compiling using the mingw shell.  Please read through the compiling instructions for details.
