### ISSUE TITLE
JNativeHook Infinite Repeat Code

### ISSUE THREAD

**Issue by RyukCode** [kwhat/jnativehook#176]
Hey there so I would like to make it so my Autoclicker starts clicking when the mouse button is held down yet stops clicking when it is released... The issue is, it doesn't stop clicking, this is what I have got so far.
	

	public void nativeMousePressed(NativeMouseEvent e) {
			while (true){
	        	try {
					Mouse.sendLeftClick();
				} catch (AWTException e1) {
					e1.printStackTrace();
				}
				double deviation = 31;
			    double mean = 95;
			    int min = 65;
			    int max = 117;
	    	    Random r = new Random();
	    	    double randGauss = (r.nextGaussian() * deviation);
	    	    long delayPreClamp = Math.round(randGauss + mean);
	    	    long delay = (long) MathUtil.clamp(delayPreClamp, min, max);
	    	    try {
	    	        Thread.sleep(delay);
	    	    } catch (InterruptedException e2) {
	    	        e2.printStackTrace();
	    	    	}
				}
	}

	public void nativeMouseReleased(NativeMouseEvent e) {
		System.out.println("Mouse Released: " + e.getButton());
	}

	public void nativeMouseMoved(NativeMouseEvent e) {
		System.out.println("Mouse Moved: " + e.getX() + ", " + e.getY());
	}

	public void nativeMouseDragged(NativeMouseEvent e) {
		System.out.println("Mouse Dragged: " + e.getX() + ", " + e.getY());
	}

	static Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
	
	public static void main(String[] args) {
		try {
			logger.setLevel(Level.OFF);
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
			System.err.println("There was a problem registering the native hook.");
			System.err.println(ex.getMessage());

			System.exit(1);
		}

		// Construct the example object.
		Inter inter = new Inter();

		// Add the appropriate listeners.
		GlobalScreen.addNativeMouseListener(inter);
		GlobalScreen.addNativeMouseMotionListener(inter);
	}

**Comment by kwhat** [comment]
You cannot block the event callback.  Doing so will cause events to backup in the delivery queue and/or be lost.  I would suggest starting the `while(true)` loop in its own thread, and then stop that thread though some type of sentinel when the mouse is released.  This will allow dispatching of other events when the clicker is clicking, which should allow you to receive the release event.
