### ISSUE TITLE
Sysntax Error near x11

### ISSUE THREAD

**Issue by nrusingh-auroin** [kwhat/jnativehook#177]
Hi,
I am using mingw in windows7-64bit system to compile Jnative hook.
It shows the syntax error message while compiling.
Here is the full stacktrace:
`AuroIN@AuroIN-PC /c/Users/AuroIN/Downloads/jnativehook2.1/jnativehook-2.1.0/jnat
ivehook-2.1.0
$ ant all
Buildfile: c:\Users\AuroIN\Downloads\jnativehook2.1\jnativehook-2.1.0\jnativehoo
k-2.1.0\build.xml

init:
     [echo] Initializing local build environment...
     [echo] Project:            jnativehook 2.1.20170612
     [echo] Debug:              false
     [echo] Java Compiler:      modern
     [echo] Java Source:        1.8
     [echo] Java Target:        1.8
     [echo] Java Include:       c:/Java/jdk1.8.0_102/include
     [echo] Java Args:
     [echo] Native Lib:         JNativeHook.dll
     [echo] Native OS:          windows
     [echo] Native Arch:        x86_64
     [echo] Native Toolchain:   gcc
     [echo] Native CFLAGS:      -O2 -pipe
     [echo] Native LDFLAGS:
[propertyfile] Updating property file: c:\Users\AuroIN\Downloads\jnativehook2.1\
jnativehook-2.1.0\jnativehook-2.1.0\build.properties

compile-java:
     [echo] Compiling Java source...

download-libuiohook:

bootstrap-libuiohook:

configure-libuiohook:
     [echo] Configuring libUIOHook source...
[configure] c:/Users/AuroIN/Downloads/jnativehook2.1/jnativehook-2.1.0/jnativeho
ok-2.1.0/src/libuiohook/configure --prefix=c:/Users/AuroIN/Downloads/jnativehook
2.1/jnativehook-2.1.0/jnativehook-2.1.0/bin --libdir=c:/Users/AuroIN/Downloads/j
nativehook2.1/jnativehook-2.1.0/jnativehook-2.1.0/bin/lib --enable-debug --enabl
e-quiet --enable-static --disable-shared --with-pic
[configure] checking build system type... i686-pc-mingw32
[configure] checking host system type... i686-pc-mingw32
[configure] checking target system type... i686-pc-mingw32
[configure] checking for a BSD-compatible install... /usr/bin/install -c
[configure] checking whether build environment is sane... yes
[configure] checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
[configure] checking for gawk... gawk
[configure] checking whether make sets $(MAKE)... yes
[configure] checking for gcc... gcc
[configure] checking whether the C compiler works... yes
[configure] checking for C compiler default output file name... a.exe
[configure] checking for suffix of executables... .exe
[configure] checking whether we are cross compiling... no
[configure] checking for suffix of object files... o
[configure] checking whether we are using the GNU C compiler... yes
[configure] checking whether gcc accepts -g... yes
[configure] checking for gcc option to accept ISO C89... none needed
[configure] checking for style of include used by make... GNU
[configure] checking dependency style of gcc... gcc3
[configure] checking for gcc option to accept ISO C99... none needed
[configure] checking for an ANSI C-conforming const... yes
[configure] checking how to run the C preprocessor... gcc -E
[configure] checking for grep that handles long lines and -e... /usr/bin/grep
[configure] checking for egrep... /usr/bin/grep -E
[configure] checking for ANSI C header files... yes
[configure] checking for sys/types.h... yes
[configure] checking for sys/stat.h... yes
[configure] checking for stdlib.h... yes
[configure] checking for string.h... yes
[configure] checking for memory.h... yes
[configure] checking for strings.h... yes
[configure] checking for inttypes.h... yes
[configure] checking for stdint.h... yes
[configure] checking for unistd.h... yes
[configure] checking for stdbool.h that conforms to C99... yes
[configure] checking for _Bool... yes
[configure] checking for stdint.h... (cached) yes
[configure] checking for uint64_t... yes
[configure] checking how to print strings... printf
[configure] checking for a sed that does not truncate output... /usr/bin/sed
[configure] checking for fgrep... /usr/bin/grep -F
[configure] checking for ld used by gcc... c:/mingw/mingw32/bin/ld.exe
[configure] checking if the linker (c:/mingw/mingw32/bin/ld.exe) is GNU ld... ye
s
[configure] checking for BSD- or MS-compatible name lister (nm)... /mingw/bin/nm

[configure] checking the name lister (/mingw/bin/nm) interface... BSD nm
[configure] checking whether ln -s works... no, using cp -p
[configure] checking the maximum length of command line arguments... 8192
[configure] checking whether the shell understands some XSI constructs... yes
[configure] checking whether the shell understands "+="... yes
[configure] checking how to convert i686-pc-mingw32 file names to i686-pc-mingw3
2 format... func_convert_file_msys_to_w32
[configure] checking how to convert i686-pc-mingw32 file names to toolchain form
at... func_convert_file_msys_to_w32
[configure] checking for c:/mingw/mingw32/bin/ld.exe option to reload object fil
es... -r
[configure] checking for objdump... objdump
[configure] checking how to recognize dependent libraries... file_magic ^x86 arc
hive import|^x86 DLL
[configure] checking for dlltool... dlltool
[configure] checking how to associate runtime and link libraries... func_cygming
_dll_for_implib
[configure] checking for ar... ar
[configure] checking for archiver @FILE support... @
[configure] checking for strip... strip
[configure] checking for ranlib... ranlib
[configure] checking command to parse /mingw/bin/nm output from gcc object... ok

[configure] checking for sysroot... no
[configure] checking for mt... no
[configure] checking if : is a manifest tool... no
[configure] checking for dlfcn.h... yes
[configure] checking for objdir... .libs
[configure] checking if gcc supports -fno-rtti -fno-exceptions... no
[configure] checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
[configure] checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
[configure] checking if gcc static flag -static works... yes
[configure] checking if gcc supports -c -o file.o... yes
[configure] checking if gcc supports -c -o file.o... (cached) yes
[configure] checking whether the gcc linker (c:/mingw/mingw32/bin/ld.exe) suppor
ts shared libraries... yes
[configure] checking dynamic linker characteristics... Win32 ld.exe
[configure] checking how to hardcode library paths into programs... immediate
[configure] checking whether stripping libraries is possible... yes
[configure] checking if libtool supports shared libraries... yes
[configure] checking whether to build shared libraries... no
[configure] checking whether to build static libraries... yes
[configure] checking operating system... i686-pc-mingw32 (Windows Compatible)
[configure] checking for as... as
[configure] checking for dlltool... (cached) dlltool
[configure] checking for objdump... (cached) objdump
[configure] c:/Users/AuroIN/Downloads/jnativehook2.1/jnativehook-2.1.0/jnativeho
ok-2.1.0/src/libuiohook/configure: line 13291: syntax error near unexpected toke
n `X11,'
[configure] c:/Users/AuroIN/Downloads/jnativehook2.1/jnativehook-2.1.0/jnativeho
ok-2.1.0/src/libuiohook/configure: line 13291: `                PKG_CHECK_MODULE
S(X11, x11)'

BUILD FAILED
c:\Users\AuroIN\Downloads\jnativehook2.1\jnativehook-2.1.0\jnativehook-2.1.0\bui
ld.xml:355: exec returned: 2

Total time: 23 seconds
`

I followed this but unable get any idea
[https://github.com/kwhat/libuiohook/issues/43](https://github.com/kwhat/libuiohook/issues/43)

Kindly help me to build it.
Regards

**Comment by kwhat** [comment]
For some reason, your system is trying to pkg-config for X11, but it was detected as a win32 system.  My best guess right now is that mingw updated something that's working differently, nothing has changed in the autoconfig file in a while. Have you compiled on linux first and now you are trying to compile on windows?  If so, did you run `ant distclean`?

**Comment by nrusingh-auroin** [comment]
No I did not compile in Linux.

**Comment by kwhat** [comment]
I just updated my msys installation and was able to compile the native code on windows without issue.

**Comment by kwhat** [comment]
https://pastebin.com/YfZvxQ3S

**Comment by kwhat** [comment]
make sure you have all the dependencies, maybe your are missing pkg-config?  Please reopen if this is still an issue with 2.1.1 which should be out this evening.
