### ISSUE TITLE
Update Wiki Example

### ISSUE THREAD

**Issue by Sergix** [kwhat/jnativehook#178]
In the "Global Keyboard Listener" section of the "Usage" wiki page (https://github.com/kwhat/jnativehook/wiki/Usage#global-keyboard-listener), the section of code
```
if (e.getKeyCode() == NativeKeyEvent.VK_ESCAPE) {
    GlobalScreen.unregisterNativeHook();
}
```
needs to be changed to
```
if (e.getKeyCode() == NativeKeyEvent.VC_ESCAPE) {
    try {
        GlobalScreen.unregisterNativeHook();
    } catch (NativeHookException e1) {
        e1.printStackTrace();
    }
}
```

**Comment by kwhat** [comment]
Ahhh, forgot about that interrupted exception.  The docs should be up to date.  Thanks for the bug report!
