### ISSUE TITLE
Can't check if two keys are pressed.

### ISSUE THREAD

**Issue by profran** [kwhat/jnativehook#179]
Hi, I can't check if Alt key and N key are pressed at the same time. Is there any isAltDown method?

Im trying to mix JNativeHook and swing to open JFrames at any moment by pressing the key combination mentioned above. 

This is what I have tried, but it ain't working.
`
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;

public class jNativeHookExample implements NativeKeyListener {

    private boolean alt = false;
    private boolean letterN = false;

    public void nativeKeyPressed(NativeKeyEvent e) {

        System.out.println("Key Pressed: " + NativeKeyEvent.getKeyText(e.getKeyCode()));
        if (e.getKeyCode() == NativeKeyEvent.VC_ALT) {

            this.alt = true;

        } else if (e.getKeyCode() == NativeKeyEvent.VC_N) {

            this.letterN = true;

        }

        if (e.getKeyCode() == NativeKeyEvent.VC_ESCAPE) {
            try {
                GlobalScreen.unregisterNativeHook();
            } catch (NativeHookException ex) {
                Logger.getLogger(jNativeHookExample.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void nativeKeyReleased(NativeKeyEvent e) {

        System.out.println("Key Released: " + NativeKeyEvent.getKeyText(e.getKeyCode()) + this.alt + this.letterN);

        if (e.getKeyCode() == NativeKeyEvent.ALT_MASK) {

            this.alt = false;
        }

        if (e.getKeyCode() == NativeKeyEvent.VC_N) {

            this.letterN = false;

        }

        if (this.alt && this.letterN) {

            System.out.println("ALT + N Pressed");

            try {
                GlobalScreen.unregisterNativeHook();
            } catch (NativeHookException ex) {
                Logger.getLogger(jNativeHookExample.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void nativeKeyTyped(NativeKeyEvent e) {

        System.out.println("Key Typed: " + e.getKeyText(e.getKeyCode()));

    }

    public static void main(String[] args) {

        try {
            GlobalScreen.registerNativeHook();
        } catch (NativeHookException ex) {
            System.err.println("There was a problem registering the native hook.");
            System.err.println(ex.getMessage());
            System.exit(1);
        }

        GlobalScreen.addNativeKeyListener(new jNativeHookExample());
    }
}

`

**Comment by kwhat** [comment]
You need to use the bit mask associated with the getModifiers method on the event.  This works exactly the same as AWT modifiers in core Java.  See https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeInputEvent.java#L65

**Comment by cikmon** [comment]
you had to swap 
if (e.getKeyCode() == NativeKeyEvent.VC_N) 
 if (this.alt && this.letterN) {

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;

public class jNativeHookExample implements NativeKeyListener {
    static Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
    private boolean alt = false;
    private boolean letterN = false;

    public void nativeKeyPressed(NativeKeyEvent e) {

        System.out.println("Key Pressed: " + NativeKeyEvent.getKeyText(e.getKeyCode()));
        if (e.getKeyCode() == NativeKeyEvent.VC_SHIFT_L) {
            this.alt = true;
        } else if (e.getKeyCode() == NativeKeyEvent.VC_V) {
            this.letterN = true;
        }

        if (e.getKeyCode() == NativeKeyEvent.VC_ESCAPE) {
            try {
                GlobalScreen.unregisterNativeHook();
            } catch (NativeHookException ex) {
                Logger.getLogger(jNativeHookExample.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void nativeKeyReleased(NativeKeyEvent e) {

        System.out.println("Key Released: " + NativeKeyEvent.getKeyText(e.getKeyCode()) + this.alt + this.letterN);

        if (e.getKeyCode() == NativeKeyEvent.VC_SHIFT_L) {
            this.alt = false;
        }

        if (this.alt && this.letterN) { System.out.println("ALT + N Pressed"); }

        if (e.getKeyCode() == NativeKeyEvent.VC_V) {
            System.out.println(4);
            this.letterN = false;
        }

    }

    public void nativeKeyTyped(NativeKeyEvent e) {
        System.out.println("Key Typed: " + e.getKeyText(e.getKeyCode()));
    }

    public static void main(String[] args) {
        logger.setLevel(Level.WARNING);
        logger.setUseParentHandlers(false);
        try {
            GlobalScreen.registerNativeHook();
        } catch (NativeHookException ex) {
            System.err.println("There was a problem registering the native hook.");
            System.err.println(ex.getMessage());
            System.exit(1);
        }

        GlobalScreen.addNativeKeyListener(new jNativeHookExample());
    }
}
