### ISSUE TITLE
Limit to keyboard events

### ISSUE THREAD

**Issue by cwalter-cg** [kwhat/jnativehook#18]
Is it possible to disable listening to mouse events? I.e. if a program is only interested in keyboard events.

**Comment by SlightlyCyborg** [comment]
This wouldn't be a problem if jnativehook didn't mess up trackpad interactions on mac. It is producing really wonky results especially with multitouch

**Comment by kwhat** [comment]
@SlightlyCyborg Can you open a new ticket?  Please describe the issue in detail.  Debug level console output would also be helpful.
