### ISSUE TITLE
Not supported Thai language?

### ISSUE THREAD

**Issue by Porama6400** [kwhat/jnativehook#184]
JNativeHook does not supported Thai language?

**Comment by kwhat** [comment]
It should but there is a bug in the Windows version that maybe preventing language support from working.

**Comment by kwhat** [comment]
Can you please test this nightly: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20170724.060230-35.jar

**Comment by Porama6400** [comment]
2.0.2 can hook successfully but getKeyChar() always return ￿
2.1.2 NullPointerException while registerNativeHook()

java.lang.NullPointerException
	at org.jnativehook.GlobalScreen.registerNativeHook(GlobalScreen.java:402)

**Comment by kwhat** [comment]
I found the issue, i will post an updated build soon.

**Comment by kwhat** [comment]
Updated version 2.1.1 https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20170802.062507-36.jar

**Comment by kwhat** [comment]
This should be resolved in 2.2.  Please reopen if the problem persists.
