### ISSUE TITLE
Compatibility Java 8u141 MANIFEST.MF. Add "/" end of Name attribute

### ISSUE THREAD

**Issue by alexflex25** [kwhat/jnativehook#186]
http://www.oracle.com/technetwork/java/javase/8u141-relnotes-3720385.html

deploy/webstart
JAR file validation changes
After upgrading to the JDK July CPU release (8u141/7u151/6u161), when executing Java Webstart applications, customers may encounter an exception like
“java.lang.SecurityException: digest missing for …” that prevents the application from loading.

The issue is observed in signed JAR files whose manifest contains package version information[1] and does not have a trailing "/" in the name of the package (e.g.: Name: org/apache/xml/resolver). While we work towards resolving this issue, in the interim, users can work-around the issue as follows:

NOTE: We recommend use of this workaround only if the distributor of the JAR files can "re-sign" the JAR files.

1. Extract the contents of the signed JAR file (e.g.: jar xf jar-file ).
2. Modify META-INF/MANIFEST.MF file and add a trailing “/” to the name of the package ( e.g.: Name: org/apache/xml/resolver/).
3. Remove the current signature files ( e.g.: rm -f META-INF/*.SF META-INF/*.RSA META-INF/*.DSA ).
4. Recreate the JAR file ( e,g.: jar cfm jar-file META-INF/MANIFEST.MF input-file(s) ). 

NOTE: You must use the jar utility. Other jar creation tools might re-introduce the issue.

5. Re-sign the JAR file.

**Comment by kwhat** [comment]
Thanks, should be fixed in the 2.0 and 2.1 branches.

**Comment by kwhat** [comment]
Nightly for testing https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20170725.064914-38.jar

**Comment by alexflex25** [comment]
Perfect, it work, but you can compile in Java 7 to keep compatibility.

**Comment by kwhat** [comment]
Compile with Java 1.7 or compile 1.7 compatible bytecode?

**Comment by alexflex25** [comment]
To avoid any problems, never change the compiler "in the middle of a dev branch". Because of Oracle...
It just my opinion.

**Comment by kwhat** [comment]
I have done some updates to the 2.1 branch, but this does not seem to be working correctly with jre 1.8.  When I run the jar compiled for and with 1.8 I see a `WARNING:   Invalid library manifest!`.

META-INF/MANIFEST.MF:
```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.1
Created-By: 1.8.0_144-b01 (Oracle Corporation)
Main-Class: org.jnativehook.example.NativeHookDemo

Name: org/jnativehook/
Specification-Title: jnativehook Library
Specification-Version: 2.1
Specification-Vendor: Alexander Barker (alex@1stleg.com)
Implementation-Title: org.jnativehook
Implementation-Version: 20170819
Implementation-Vendor: Alexander Barker (alex@1stleg.com)
```

**Comment by kwhat** [comment]
If this is a JavaFX only issue, it may be better to do a build as part of https://github.com/kwhat/jnativehook/issues/169 for javafx.  That would also allow me to include some better JavaFX support like https://stackoverflow.com/a/45423466/773849

**Comment by kwhat** [comment]
Ahh what a disaster this was... I patched the code properly this afternoon, but it means not using the "/" in the manifest. I will add JRE8 jars to maven to address this problem as part of #169.
