### ISSUE TITLE
Question/Issue about nativeKeyPressed method

### ISSUE THREAD

**Issue by sbotev5** [kwhat/jnativehook#187]
First of all, thank you for this lib. It has been great for my beginner free-time practice project.

You can check it out and tell me if it is cool/decent, if you wish :) Input appreciated !
https://github.com/sbotev5/simpleAutomationTool

Now, as for my question ---> I am using a keylistener to record keyboard presses and I have this:
 public void nativeKeyPressed(NativeKeyEvent e) {
    System.out.println(e.getKeyCode()); 
}

So when I press **and hold** a button like "A" it constantly prints its key code.  The same doesn't happen with a button like ALT.  Meaning that it prints the key code once and that's it while holding it. What is the reason behind this ?

Thanks in advance.

**Comment by kwhat** [comment]
The key bouncing is handled by the Operating System.  The library does its best to ensure this is available on all platforms, however, it will not enforce key bouncing for keys the OS doesn't.  If I was to guess, the platform you are testing on only bounces keys that produce key typed events.  I am not sure how each OS handles this case.

**Comment by sbotev5** [comment]
Thanks. So really it is very dependent on a case-by-case basis. Too bad, really wanted to implement a key combo (ALT-TAB  ALT-F4 etc) recordings functionality in the idea of my project.

**Comment by kwhat** [comment]
You should be able to use the modifier masks and the keydown / up events to do that.

**Comment by sbotev5** [comment]
Where can I read about the modifier masks ? Didn't see them mentioned on README

**Comment by kwhat** [comment]
The work the same way as the Java modifier mask.  NativeInputEvent should have a getModifiers() function that can be used as a bit mask against the class constants at the same location.  https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeInputEvent.java#L65

**Comment by kwhat** [comment]
```if (e.getModifiers() & NativeInputEvent .ALT_MASK) {
    // Do Work.
}```

**Comment by sbotev5** [comment]
Is this .ALT_MASK just an example fora specific case ? I am not sure how these masks are implemented in the key pressed   key released functions in the KeyListener

**Comment by kwhat** [comment]
The NativeKeyEvent and all other native input events extend NativeInputEvent which provides the getModifiers() method.  So on any native event callback, you can do something similar to the following.
```
public function nativeKeyPressed(NativeKeyEvent e) {
    if (e.getKeyCode() == VK_A && e.getModifiers() & NativeInputEvent.ALT_MASK) {
        // The user was holding down either left or right ALT and then pressed the A key.
    }
}
```

You probably want to learn about bit masks to understand what is happening here: 
http://sys.cs.rice.edu/course/comp314/10/p2/javabits.html  It is basically checking the positions of bits in the numeric field returned by getModifiers().

**Comment by sbotev5** [comment]
Thanks for the link !

From the example you gave for ALT + A, it looks like I have to lay out every single possible key combo as an if check ?

**Comment by kwhat** [comment]
If you are trying to record and playback key storkes, I would skip all of the modifiers for key down / up listeners and just store the entire modifier mask.  Posting the events back __SHOULD__ unroll the modifiers for you.

**Comment by sirgyula** [comment]
I'm trying to use the code above with shift+prtscreen, but the result is a bit strange. It works sometimes, sometimes only for every 2nd keypress. And, with shift+prtsrc in the code, it sometimes fires for space+prtscr also!
Here is the if condition I'm messing around with in the nativeKeyPressed function:
`if (nativeKeyEvent.getKeyCode() == NativeKeyEvent.VC_PRINTSCREEN && nativeKeyEvent.getModifiers() == NativeInputEvent.SHIFT_L_MASK) {
    System.out.println("printscreen" + " " + nativeKeyEvent.getModifiers());
}`

**Comment by kwhat** [comment]
Thats strange and probably a bug.  You are not using the modifier mask correctly in the above instance but I am not sure if that is causing this problem.  Try something like this instead

```if (nativeKeyEvent.getKeyCode() == NativeKeyEvent.VC_PRINTSCREEN && nativeKeyEvent.getModifiers() & NativeInputEvent.SHIFT_L_MASK) {```

**Comment by sirgyula** [comment]
I've tried exactly using that, but my intellij says: 
```
Error:(70, 74) java: bad operand types for binary operator '&&'
  first type:  boolean
  second type: int
```
I'm on win10 prof 1703,  java 1.8_144

**Comment by kwhat** [comment]
if (nativeKeyEvent.getKeyCode() == NativeKeyEvent.VC_PRINTSCREEN && (nativeKeyEvent.getModifiers() & NativeInputEvent.SHIFT_L_MASK)) {

**Comment by sirgyula** [comment]
Still the same. Says that the (nativeKeyEvent.getModifiers() & NativeInputEvent.SHIFT_L_MASK) needed to be boolean, but it's an int.

**Comment by kwhat** [comment]
@sirgyula are you using the logic `&&` instead of the bit-wise `&`?

**Comment by Yakabuff** [comment]
> if (nativeKeyEvent.getKeyCode() == NativeKeyEvent.VC_PRINTSCREEN && (nativeKeyEvent.getModifiers() & NativeInputEvent.SHIFT_L_MASK)) {

I get the same error 

```The operator && is undefined for the argument type(s) boolean, int``` 

@kwhat
