### ISSUE TITLE
Fedora Core 4 'GLIBC_2.7' not found

### ISSUE THREAD

**Issue by sonerokur** [kwhat/jnativehook#188]
Hi, I am developing a project for my client and they are using Fedora Core 4 in their machines. 
I developed the project using Java 1.6 and upgraded their machine to Java 1.6. But when i try to run the project, it gives error like this "java.lang.UnsatisfiedLinkError: /tmp/libJNativeHook-1595093347821086651.so: /lib/libc.so.6: version 'GLIBC_2.7' not found (required by /tmp/libJNativeHook-1595093347821086651.so)". 
Could you help me to solve this problem ?

**Comment by kwhat** [comment]
Best guess is that you will need to recompile from source for the older version of glibc that is being used.  There are compiling instructions in the WIKI that should get you started.  let me know if you run into problems compiling.

**Comment by sonerokur** [comment]
Thanks for this great library. I managed to compile for FC4. 

If anyone needs this, i've downloaded source codes from below links and compiled them.
After compilation process is finished,  you have to add lib/pkgconfig paths to PKG_CONFIG_PATH variable. 
And then you can start to compiling this library for FC4.

ftp://ftp.x.org/pub/xorg/individual/lib/
ftp://ftp.x.org/pub/xorg/individual/proto/

<img width="466" alt="xorg-libs" src="https://user-images.githubusercontent.com/10261590/29215267-fd632e2e-7eb2-11e7-8ca9-3c24a25a1c5a.png">
