### ISSUE TITLE
getKeyChar() returning "?"

### ISSUE THREAD

**Issue by leninr0a** [kwhat/jnativehook#189]
Hi,

I have been trying to use the getKeyChar() method to get the input but its returning "?" symbol.

Is that method the only way to detect if the input key is lowercase right?

Thank you

**Comment by kwhat** [comment]
need more context, it could be unicode or it could be returning CHAR_UNDEFINED if you are calling on a non-NativeKeyTyped event.  It could also be an issue on Windows with memory corruption in 2.1.  I am still working on solving the memory issue.

**Comment by kwhat** [comment]
Please reopen if this is still an issue?  Yes it is the only way to detect lower case.

**Comment by haseeb-xd** [comment]
@kwhat  We need a solution for this, i am also getting '?' for getKeyChar. Reply will be appreciated

**Comment by robinjos333** [comment]
I am also looking for how to detect lowercase letters. Using getKeyChar method which prints like this " � " .
