### ISSUE TITLE
Native mouse event Horizontal scroll

### ISSUE THREAD

**Issue by elyz125** [kwhat/jnativehook#190]
I am trying to get a mouse listener to identify small movements on the Horizontal wheel of my mouse.

Using org.jnativehook.mouse.NativeMouseWheelListener with the vertical wheel, the parameter scrollAmount shows either 1 or -1(turning up or down) for each click.
When using the horizontal wheel, small movements are are captured but scrollAmount is 0 (no way of knowing the direction).
When making fast movements, the horizontal wheel's scrollAmount is either negative or positive, depending on the direction.

A similar issue: https://github.com/SFML/SFML/issues/95
States that this could be due to division by 120 and storing the value in an integer thus leading to loss of precision.

Any help on this will be very appreciated!

Thanks

**Comment by kwhat** [comment]
Can I get the platform information for the host experiencing issues?  Sounds like it is probably a bug in one of the native handlers.

**Comment by elyz125** [comment]
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393
The mouse is Logitech mx master
JRE libraries version 1.8.0_144
Using jnnativehook-2.1.0.jar 

tell me if I missed something

**Comment by kwhat** [comment]
Will probably need to do some digging.  The code in question is here: https://github.com/kwhat/libuiohook/blob/1.1/src/windows/input_hook.c#L492

**Comment by elyz125** [comment]
I can see that this is where the division by 120 occurs:

	 * click is defined as WHEEL_DELTA, which is 120. */
	event.data.wheel.rotation = ((int16_t) HIWORD(mshook->mouseData) / WHEEL_DELTA) * -1;

Will wait for updates! Thanks

**Comment by kwhat** [comment]
I really need a horz scroll mouse.  I tested with my Apple mouse on Windows and it seems to work fine in the trunk.  Which mouse are you using?  It could either be int division or mshook->mouseData is really zero...  There are no docs from Microsoft on horizontal rotation that I have been able to find.

**Comment by kwhat** [comment]
Should be resolved in 2.2.2.  Let me know if this is still a problem.
