### ISSUE TITLE
Key hook seems not responding while running application in background process.

### ISSUE THREAD

**Issue by bilalsafi123** [kwhat/jnativehook#191]
I have developed Parental control application which works perfect when running from eclipse or from command prompt. But when same application is run by windows registry as background process then my application's key logger stop responding.

My Observation:
Process is running and consuming ram and when i start typing it also consume processor from (start at 10% to 0.1%) but no keys are logged in file and database as well.

My question: is it possible for jnativehook to process in background?

*Please ans as soon as possible. I have spent one month to create this whole application and now time is to deploy and this happen. *

Main method code:
*******************************************************************************************************
try 
	        {
		    	 Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
		    	 logger.setLevel(Level.OFF);
		    	 logger.setUseParentHandlers(false);
		    	 GlobalScreen.registerNativeHook();
		    	 
	     	} catch (NativeHookException ex) 
	        {
	     		ex.printStackTrace();
	     			//System.exit(1);
	     	}
	     
	        try 
	        {
	            GlobalScreen.registerNativeHook();
	        }
	        catch (NativeHookException ex) 
	        {
	        	ex.printStackTrace();
	            System.err.println("There was a problem registering the native hook.");
	            System.err.println(ex.getMessage());
	        }
	        GlobalScreen.addNativeKeyListener(new Main());

**Comment by kwhat** [comment]
How are you running the application as a service?

**Comment by bilalsafi123** [comment]
By registering jar as windows service.

**Comment by bilalsafi123** [comment]
Actually I have done this task by way around.
I have registered a C# application in windows registry and that application run my application in background process so it is running perfect.

But some times it miss key strokes. I dont know when and why or key steps to reproduce this issue but it sometimes miss keys.

**Comment by kwhat** [comment]
Setup a logger to figure out what is happening.  Newer versions of windows do undocumented things with low level keyboard and mouse hooks.

**Comment by kwhat** [comment]
I could be wrong, but I don't believe you can run the jvm as a service. See: https://wrapper.tanukisoftware.com/doc/english/introduction.html

**Comment by dyorgio** [comment]
HI @bilalsafi123, sadly JNativeHook doesn't work with Windows Services, because of limitations on Windows Services (can't access user desktop, after windows vista).
You need to use windows service only as a launcher to your project run as a normal program.

**Comment by sghpjuikit** [comment]
> HI @bilalsafi123, sadly JNativeHook doesn't work with Windows Services, because of limitations on Windows Services (can't access user desktop, after windows vista).
> You need to use windows service only as a launcher to your project run as a normal program.

That's rather sad. Fortunately, users probably do not care.
