### ISSUE TITLE
Not an issue, just praise by video :)

### ISSUE THREAD

**Issue by stefan-reich** [kwhat/jnativehook#193]
I like to give good libraries the exposure they deserve :)

[Video](https://youtu.be/SAhzlPcAW6Q) - hope you like it.

The advantage of my system ([JavaX](http://javax.ai1.lol)) is the zero-installation operation. Run a [single jar file](http://tinybrain.de/x30.jar) once, and you are able to run any program in the online JavaX database after that - including those requiring native libraries. It's all downloaded and compiled on the fly with one click. Cheers

**Comment by kwhat** [comment]
Thanks for sharing!  I will see if I can add it to the readme.
