### ISSUE TITLE
" Unhandled Darwin event" on OSX Yosemite

### ISSUE THREAD

**Issue by aterjung** [kwhat/jnativehook#21]
Hi,

i have just found this project and it seems to be what i need. I have just compiled the demo-application but i only get warning messages in the console:  hook_event_proc [737]: Unhandled Darwin event! (0X1D) but no event is logged in the demo-window. What is happening here? Can it be fixed?

thanks in advance

**Comment by kwhat** [comment]
Apparently I didn't fix this correctly.

**Comment by kwhat** [comment]
Should be addressed @ cc13af6 by reducing the log level from warning to info.
