### ISSUE TITLE
Cant get the computer to press keys that are not numbers or letters

### ISSUE THREAD

**Issue by ybs007** [kwhat/jnativehook#210]
Hey , I'm consuming the key press event on one computer and trying to press the same key on another computer . 
I'm using robot.keyPress(e.rawCode)
It works fine with letters and numbers but for keys like (" ,  alt  ctrl  ]) etc' it crashes . 
Is there a solution for the problome?

**Comment by kwhat** [comment]
You should be using the post event functionality in this library.  The rawCode is the native keycode produced for the key press and is incompatible with the Robot class.  Just send the same event stream you capture to the `GlobalScreen.postNativeEvent(NativeInputEvent nativeEvent);` method.
