### ISSUE TITLE
rawCode when building NativeKeyEvents

### ISSUE THREAD

**Issue by deontologic** [kwhat/jnativehook#212]
Hello; I'm trying to map a String to a a sequence of NativeKeyEvent, that's then posted via GlobalScreen. I've tried using javafx KeyCode.getCode() (which is documented to match the platform implementation) for `rawCode` in the constructor, however I've gotten IllegalArgument exceptions for most characters.

Do you have any recommendation on constructing NativeKeyEvents on JavaFX in a platform-agnostic way?

Regards,

Deontologic

**Comment by kwhat** [comment]
The raw code can be ignored when posted.  It's really only there for low level stuff or very custom stuff.
