### ISSUE TITLE
Can't write accented letters

### ISSUE THREAD

**Issue by AlanSchaeffer** [kwhat/jnativehook#213]
While the hook is running, I can't type the accents by themselves or the related combined characters that result from typing the symbol then the letter, such as éãòû. They simply won't appear on whatever text editor or the letter will appear by itself, didn't look too much into it but I did a simple simulation and got the log from it
[jnativehook log.txt](https://github.com/kwhat/jnativehook/files/1742423/jnativehook.log.txt)

**Comment by AlanSchaeffer** [comment]
Ok it seems this has been fixed in issues #197, #183 and #184, but I can't download the snapshots provided in them (says they are not found). They seem to be for version 2.1.1, and I'm grabbing jnativehook via maven where it's latest version is 2.1.0. Any chance you could upload 2.1.1 to maven?

**Comment by kwhat** [comment]
I am doing a release really soon.  This is going to be an ongoing issue for a while, especially on linux.  Let me know if 2.1.2 works better for you.

**Comment by AlanSchaeffer** [comment]
I recently got one of the jar's from the link I mentioned not working in the other post, but it didn't work out for me. I ran the program a few times (I made no changes to it other than removing the maven repo dependency and instead using the local jar), it worked once with all the combined characters working fine, then next time the program froze, in another instance it ran but with the same old bug, and then after that I had an issue that it seemed like the hook would not happen at all, as the shortcut I made with it wasn't working. After that I kinda gave up as I was in a hurry to do something else and never touched on that again, instead I've been using the old version which has been working for me and I don't exactly _need_ the combined characters unless I'm writing something for college or such

**Comment by decimvs** [comment]
Hi, I have the same issue with version 2.1. I can't write special characters in other programs, like Firefox, when JNaviteHook is running. I rolled back to version 2.0.3 and all works good.  I've only tested in W10. Also in console it shows an error related to the locale, that is reported at #183 and #170. I get the same error message as #170, well I get many locale error codes. In my W10 I have installed three languages: spanish, catalan and english. It could be the reason for these multiple error codes?

**Comment by zeroeightysix** [comment]
Also experiencing this. AZERTY keyboard, the belgian layout. Can't type tilde (~) or other accents where you first type the accent and then the letter to apply it to (f.e. ``Alt Gr + ` `` , release, `Shift + E` would become È)
Using version `2.1.0`.

**Comment by kwhat** [comment]
I am working on trying to get a nightly out as soon as I can get the compiler working again.

**Comment by JalalSordo** [comment]
Also, the same problem for me with version 2.1.0 on WIN 10 with Dansk keyboard, I can't write ´ ^ when these lines of code are uncommented:
`GlobalScreen.registerNativeHook();
GlobalScreen.addNativeMouseListener(mouseCaptureService);
GlobalScreen.addNativeKeyListener(keyboardCaptureService);`

**Comment by jhonnatanricardo** [comment]
Same problem with version 2.1.0 on Windows 10

**Comment by atlantiscze** [comment]
Can confirm this - 2.1.0 from Maven, tested on Windows 10 and 7. Would there be any chance to get a new version out on maven that would fix this?

**Comment by kwhat** [comment]
This should be resolved in 2.2, tested with the fresh keyboard layout and it appears to work.  If this is still a problem with 2.2, please reopen.
