### ISSUE TITLE
SEVERE: Unable to extract the native library /org/jnativehook/lib/windows/x86_64/JNativeHook.dll!

### ISSUE THREAD

**Issue by NG-Bullseye** [kwhat/jnativehook#214]
It dosnt work at all. No matter which version i use it failes. Your testfile is missing a method. When exclude the Junit testfile the Error in the title comes up. If i use v1.1.5 your example code dosnt work. the method addNativeMouseListener and addNativeMouseMotionListener is just not found. I am impressed how much can go wrong.

using normal windows and intellij.

**Comment by kwhat** [comment]
You probably need to figure out how to load the JNI DLL in IntelliJ, you may need to extract it manually.  The default extractor included in the library attempts to extract the library to the system temp folder and load it manually from a static context.  You may control how and where the library is loaded from by implementing your own version of [org.jnativehook.NativeLibraryLocator](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/NativeLibraryLocator.java).  You can look at the [DefaultLibraryLocator](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/DefaultLibraryLocator.java) for an example of what needs to be done, remember to set the property descibed in the interface to use the custom loader.  If you don't want to use a custom loader, extract the lib/windows/x86_64 DLL from the JAR and tell your IDE where to find it.  Remember this is a JNI library not a JAR.
