### ISSUE TITLE
MotionListener not working in v2.1.0 (as hosted by Maven)

### ISSUE THREAD

**Issue by nanoandrew4** [kwhat/jnativehook#234]
I was working on a project involving jnativehook, and decided to update to the latest jnativehook version since I was still on one of the 1.x.x versions. After much looking around, reverting to version 2.0.3 fixed the problem for me, which seems to indicate there is a problem with the 2.1.0 version hosted by maven.

Mouse clicks registered correctly, but the motion listener was completely dead, did not fire at any point.

**Comment by martindeutschtutall** [comment]
Which OS are you using? Windows 7,8,10? MacOS X? Linux (Ubuntu 12-18)? Debian?

**Comment by nanoandrew4** [comment]
Linux Mint 19

**Comment by kwhat** [comment]
Can you test the latest version

https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20190725.024655-45.jar

**Comment by kwhat** [comment]
Please reopen if this continues with the latest version 2.2.1
