### ISSUE TITLE
Question about consuming events

### ISSUE THREAD

**Issue by stefan-reich** [kwhat/jnativehook#244]
Says [here](https://github.com/kwhat/jnativehook/wiki/ConsumingEvents):

> [Consuming events] is currently unsupported because it is impossible to implement on X11 platforms like Unix, Linux and Solaris.

My question is then: How does VirtualBox do it? It is able to grab keyboard & mouse and consume key events like Alt+Tab.

I'd love to have this in Java to implement something like a Mini-VNC.

Thanks

**Comment by kwhat** [comment]
X11 does not have a mechanism to sit in between the event delivery queue as a non-root user.  Virtualbox does it by asking for all input events when it has focus.  Take a look at xrecord vs xgrabkeyboard.

**Comment by stefan-reich** [comment]
Ah, that's why jvncviewer doesn't handle Alt+Tab...

> Take a look at xrecord vs xgrabkeyboard.

Can this be done in Java? After all, that stuff is what your project does...? :+1:

**Comment by kwhat** [comment]
Not with X11 without root.  Other options would be either wayland or
creating a kernel driver.  The latter is far beyond the scope of this
project.

**Comment by stefan-reich** [comment]
Thanks... so VirtualBox's actual trick is to have a kernel module under its command?

Just so I understand, it's am important topic for me as I make an operating system which runs as a normal program inside Linux.

**Comment by kwhat** [comment]
Virtualbox probably uses xgrabkeyboard and xgrabmouse as it isolates the
input to the VM window.  I have also tried to use these api's to consume
events, however, you cannot *not* consume events with these calls, hence
the use of XRecord.

**Comment by stefan-reich** [comment]
Sorry, what is XRecord? Google fails me there
