### ISSUE TITLE
GlobalScreen.postNativeEvent can't send right-alt, right-ctrl, and right-shift keys

### ISSUE THREAD

**Issue by Skhmt** [kwhat/jnativehook#246]
Right Alt (`GlobalScreen.postNativeEvent(new NativeKeyEvent(2401, 0, 165, 56, NativeKeyEvent.CHAR_UNDEFINED))`) produces a left alt: `KeyCode: 56 | RawCode: 164 | Key: Alt`

Right Ctrl (`GlobalScreen.postNativeEvent(new NativeKeyEvent(2401, 0, 163, 29, NativeKeyEvent.CHAR_UNDEFINED))`) produces a left ctrl: `KeyCode: 29 | RawCode: 162 | Key: Ctrl`

Right Shift (`GlobalScreen.postNativeEvent(new NativeKeyEvent(2401, 0, 161, 3638, NativeKeyEvent.CHAR_UNDEFINED))`) actually just doesn't do anything.

It looks like `postNativeEvent` is based entirely on the `keyCode` and disregards the `rawCode`. Which might be why Right Shift doesn't do anything, as it's an unknown keycode. It's probably also why right-alt gives a left-alt and right-ctrl gives a left-ctrl,  as those share the same keycodes left and right.

Is there any way to separate them to allow specifically the right keys to be pressed? Thanks.

**Comment by kwhat** [comment]
I am not sure if that will be possible, however, I will take a look and get back to you this weekend.

**Comment by Skhmt** [comment]
Any news? Also, would it be possible to add key events for numpad-specific keys like -, *, /, +, etc?

**Comment by Skhmt** [comment]
Also, there's something weird going on with the arrow keys and the numpad arrow keys (numpad 2,4,6,8). According to the demo, the regular arrow keys says their location is the numpad, while (numlock off) numpad 2/4/6/8 shows an arrow press in key_location_standard.

**Comment by ogallagher** [comment]
To start I'd at least recommend adding those key codes to NativeKeyEvent so that they're recognized by NativeKeyListener.

**Comment by kwhat** [comment]
This should be resolved in the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/1967211753).  Please reopen if the problem persists.
