### ISSUE TITLE
Capturing Ctrl + square bracket?

### ISSUE THREAD

**Issue by fgroupindonesia** [kwhat/jnativehook#247]
i use this to capture CTRL + 2,
but no idea where is SQUARE Bracket (either left or right) is CTRL + [ ?

```
 public void nativeKeyPressed(NativeKeyEvent e) {
boolean isCtrlPressed = (e.getModifiers() & NativeKeyEvent.CTRL_MASK) > 0;
 // CTRL+2
        if (e.getKeyCode() == NativeKeyEvent.VC_2 && isCtrlPressed) {
            System.out.println("CTRL + 2");
        }
}
```

**Comment by kwhat** [comment]
I do not understand, please add more information?

**Comment by gumuruhsspj** [comment]
On the example above i just wrote for capturing the `CTRL + 2` keystrokes.
But i wonder how about `CTRL + [` or even `CTRL + ]`

what is the `NativeKeyEvent.SquareBracket` code ?

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L184

**Comment by gumuruhsspj** [comment]
alright... that's perfect!

i got it now
`NativeKeyEvent.VC_CLOSE_BRACKET`
and 
`NativeKeyEvent.VC_OPEN_BRACKET`

thanks @kwhat , you're super! hehe...
