### ISSUE TITLE
Do not load statically

### ISSUE THREAD

**Issue by Xerus2000** [kwhat/jnativehook#249]
Due to a bug, initializing JNativeHook kept crashing on Linux during initialization. Well, we thought, as long as we don't register anything it should be fine. But nope, the native library is loaded in a static block in GlobalScreen.
In my opinion, this is a no-go. The library should only load when you tell it to and not as soon as it is accessed in any way.

**Comment by sghpjuikit** [comment]
I agree.

In order to avoid introducing major changes and inconveniencing developers with usage more complicated then necessary, perhaps it would be fine simply if the native resources loaded when they are first required, probably in `GlobalScreen.registerNativeHook`

**Comment by sghpjuikit** [comment]
As I understand due to native code it is necessary to load the native libraries in static block. This issue can probably be closed then.
