### ISSUE TITLE
Mouse and Keyboard events are not captured in macMojave 10.14.2

### ISSUE THREAD

**Issue by ldtung** [kwhat/jnativehook#252]
Hello

I'm using JNativeHook to capture Mouse and Keyboard events to perform some actions.

But recently when upgraded my MacOS to Mac Mojave 10.14.2 then Mouse and Keyboard events are not captured. Does it sound MacOS settings issue or JNativeHook does not support this new MacOS version?

Thanks for your help
Tung

**Comment by kwhat** [comment]
IIRC there is a bug in the current mac binary.  The bug has been fixed in git, I just have had no way of building it.  I finally got things building last night so there should be an update soon.  I will follow up when a build is posted.

**Comment by NirmanSonawane** [comment]
I am using JNativeHook to capture Mouse on Mac. But in Mac Mojave 10.14.2 the Mouse is not captured. Is it a Mac issue or JNativeHook does not support Mac Mojave version?
I am getting these errors:

**WARNING: Java_org_jnativehook_GlobalScreen_getPointerAccelerationThreshold [319]: Invalid result returned from hook_get_pointer_acceleration_threshold()!
org.jnativehook.NativeHookException: Failed to enable access for assistive devices.
at org.jnativehook.GlobalScreen$NativeHookThread.enable(Native Method)
at org.jnativehook.GlobalScreen$NativeHookThread.run(Unknown Source)
There was a problem registering the native hook.19:34:04.327 [Thread-10]
Failed to enable access for assistive devices.**

**Comment by kwhat** [comment]
org.jnativehook.NativeHookException: Failed to enable access for assistive devices is the issue.  It use to pop up a dialog and ask the user to allow access.

**Comment by kwhat** [comment]
Check this setting https://mizage.com/help/accessibility.html#10.14

You can also try the latest builds:
https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20190725.024655-45.jar

**Comment by NirmanSonawane** [comment]
> Check this setting https://mizage.com/help/accessibility.html#10.14
> 
> You can also try the latest builds:
> https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/
> https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20190725.024655-45.jar

I tried the setting you suggested, now I guess the org.jnativehook.NativeHookException is solved , but now I am getting UnsatisfiedLinkError 
These are the errors :

**Exception in thread "JNativeHook Dispatch Thread" java.lang.UnsatisfiedLinkError: Unable to load library 'user32':
dlopen(libuser32.dylib, 9): image not found
dlopen(libuser32.dylib, 9): image not found
Native library (darwin/libuser32.dylib) not found in resource path** 

Could you please tell me how to fix this?

**Comment by NirmanSonawane** [comment]
> > Check this setting https://mizage.com/help/accessibility.html#10.14
> > You can also try the latest builds:
> > https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/
> > https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20190725.024655-45.jar
> 
> I tried the setting you suggested, now I guess the org.jnativehook.NativeHookException is solved , but now I am getting UnsatisfiedLinkError
> These are the errors :
> 
> **Exception in thread "JNativeHook Dispatch Thread" java.lang.UnsatisfiedLinkError: Unable to load library 'user32': dlopen(libuser32.dylib, 9): image not found dlopen(libuser32.dylib, 9): image not found Native library (darwin/libuser32.dylib) not found in resource path**
> 
> Could you please tell me how to fix this?

Sorry actually I was using some windows functions in this, that's why these errors were occurring.
Anyways not it has been solved.

**Comment by kwhat** [comment]
The above download links shouldn't have worked.  You can find the most recent version https://oss.sonatype.org/content/groups/public/com/1stleg/jnativehook/2.1.SNAPSHOT/jnativehook-2.1.20190725.024655-45.jar

I am not going to have access to a computer that can run Mojave for the foreseeable future.

**Comment by Sabir001** [comment]
> org.jnativehook.NativeHookException: Failed to enable access for assistive devices.

Hi, is there a way around to have this fixed?
I am stuck for this issue.

**Comment by kwhat** [comment]
@Sabir001  you just need to enable support for accessibility devices.  see https://help.rescuetime.com/article/59-how-do-i-enable-accessibility-permissions-on-mac-osx
