### ISSUE TITLE
Block mouse events --- #14

### ISSUE THREAD

**Issue by gaurangpatelng** [kwhat/jnativehook#255]
Do we have any way to do in jnativehook:2.0.2? 
I want to do for Window. 

As per document, it's unsupported. 
https://github.com/kwhat/jnativehook/wiki/Usage#consuming-events-unsupported

**Comment by gaurangpatelng** [comment]
Mouse block working. Thanks. But do you have any way for release after some code execution? Like I want to do capture screen image before page navigation. Once Image capture I want to invoke block action.

**Comment by kwhat** [comment]
Hi, sorry for the delay, I have been quite busy trying to get the builds back up and running.  The magic is to set the first bit of the reserved short to 1, EX: `f.setShort(e, (short) 0x01);` If you do not set that to 1, the event will not be consumed, so simply create a conditional somewhere to check if you need to consume the events.  The only thing here is to make sure the conditional variable is synchronized.
