### ISSUE TITLE
Add jlink compatible Jigsaw module info

### ISSUE THREAD

**Issue by Sabir001** [kwhat/jnativehook#256]
I am trying to create a JavaFx desktop app. In this app, I am using JNativeHook. But, while trying to create a custom JRE for my app, it shows me following error. 

`Error: automatic module cannot be used with jlink: jnativehook `

@kwhat  ,  can you please add module info so that it can be used in Java 11 applications without any problem?

**Comment by Degubi** [comment]
Hi, I already made a pull request for this issue. See #254

**Comment by Sabir001** [comment]
@kwhat , can you take  a look at the pull request please.

**Comment by kwhat** [comment]
Hey, Sorry for the delays.  I have been working on getting a compiler toolchain together so I can get builds working again.  I take a look shortly.

**Comment by kwhat** [comment]
Which PR are we talking about?

**Comment by Sabir001** [comment]
#254 which @Degubi has mentioned in comment section

**Comment by kwhat** [comment]
Merged!  Thanks for the update.  I'll have a new build just as soon as I can get ranlib working for OSX with LLVM 8.

**Comment by Sabir001** [comment]
I can close this issue after that. Or else I have to build locally and test and then close.

**Comment by Degubi** [comment]
I just checked the PR, I didn't mark the "requires" as transitive, so everyone has to write them into their module-info.java files. Should I open a pr to make them transitive, or are they fine? If the user forgets about requiring the logging or desktop module the app will crash I think

**Comment by kwhat** [comment]
I am not very familiar with these new Java features, however, what you
describe sounds like it its probably going to be a little bit of a pain for
those implementing;  go ahead with a second PR if you feel like it would be
the better option.

**Comment by Degubi** [comment]
I think this can be closed now.

**Comment by Sabir001** [comment]
Closing the issue but am eagerly waiting for new version with mac related issues solved.
