### ISSUE TITLE
identify origin device

### ISSUE THREAD

**Issue by dragonsKnight5** [kwhat/jnativehook#261]
Hi,
Is it possible with this library to identify the device that create a keyListener event?

I have a reader device that communicates with the system in the same way as a keyboard,
so this kind of feature would be extremely useful

Best Regards 
dragonsKnight5

**Comment by tyrion9** [comment]
It's so useful when we can filter which device to be listened.

**Comment by tyrion9** [comment]
I look at the code and aware that it's hard to be filter devices.
It seems to be a simulated screen (GlobalScreen) and listen event keys and mices that interact with this.

So sad.

**Comment by kwhat** [comment]
It is not possible for technical reasons with how these OS level hooks work.  If you need the source device, you probably want HID.
