### ISSUE TITLE
Minimize jar breaks Library locating

### ISSUE THREAD

**Issue by LemmoTresto** [kwhat/jnativehook#265]
**Maven's shade plugin** has a feature in its configuration to minimize the jars file size. This means it will get rid of as much as possible that is not used.
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>false</minimizeJar>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Enabling this breaks the ``DefaultLibraryLocater`` since it is removed from the jar.

Maybe using a [filter](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html) with the minimize jar to include these classes can be used. I have not found any way of telling maven-shade to bypass a specific class from within the library itself.

To prevent others from having to get through this struggle it might be smart to note this in the readme for maven users.

**Comment by kwhat** [comment]
This is way outside of the scope of this library and falls in to the same category as my Obfuscator does not work with your library.  Because these tools are changing the jar, particularly the class paths or in this case removing classes, I would expect all kinds of things to break in all kinds of libraries.  I should also point out that bundling this jar inside of a different jar is a violation of the LGPL.  If you are concerned about the final packaged size of your application, you should be using the `java.library.path` property to specify the appropriate platforms' native library.  See https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperties()

**Comment by LemmoTresto** [comment]
It's a standard maven plugin and is not affiliated with me. The purpose of this issue is to help others.
And the maven shade plugin does not violate the LGPL license whatsoever. I recommend reading up on the maven shade plugin.

**Comment by kwhat** [comment]
Apologizes, I briefly glanced over your post and miss interpreted your goal.  I am not sure how you can avoid run-time issues from a standard plugin going in and removing classes.  The DefaultLibraryLocater is used in a static initialization block **AFTER**` java.library.path` is searched.  I don't know how maven shade works behind the scenes, but obviously it cannot handle or detect classes that are used within a static code block. It looks like there is an `<artifactSet>` [parameter](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#artifactSet) that seems like it can be used to avoid issues like these.  I am not sure what to tell you...  If this is still a problem, maybe contact the maven shade developers and ask them?

**Comment by LemmoTresto** [comment]
No worries, I’ll have a look at the link given. For now the fix is to disable the minimizejar option in the shade plugin.

**Comment by kwhat** [comment]
If you are just trying to strip the extra library locator class, use the `java.library.path` as previously mentioned. If you are unsure of how that works with Java, do some digging and if you still have issues, send me an email.  On a related note, you cannot change the class paths as they need to be looked up from native code.

**Comment by kwhat** [comment]
I should also clarify, if you are just stripping the class from the jar, this does not violate the LGPL.  If you are also putting the library classes in a different non-LGPL jar, then this is a violation.

**Comment by kwhat** [comment]
It sounds like shade is primarily used to do both things I just told you not to do so here is a little info on static linking and the LGPL.  https://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking

**Comment by LemmoTresto** [comment]
Thanks for all the info! I’ll have a look at everything.
