### ISSUE TITLE
How to deactivate mouse listener

### ISSUE THREAD

**Issue by murad-alm** [kwhat/jnativehook#266]
Hello,
I only want to use the NativeKeyListener, but the mouse listener is working the whole time in the background. Is there a way to deactivate it?

thanks!

**Comment by NirmanSonawane** [comment]
You can remove it by :
GlobalScreen.unregisterNativeHook();
GlobalScreen.removeNativeMouseListener(Name of MouseListener Object);

**Comment by murad-alm** [comment]
> 
> 
> You can remove it by :
> GlobalScreen.unregisterNativeHook();
> GlobalScreen.removeNativeMouseListener(Name of MouseListener object);

I don't want to remove the KeyListener, i only want to remove the **mouseListener**

**Comment by NirmanSonawane** [comment]
> I don't want to remove the KeyListener, i only want to remove the **mouseListener**

GlobalScreen.unregisterNativeHook();
GlobalScreen.removeNativeMouseListener(Name of MouseListener object);

**Comment by murad-alm** [comment]
> 
> 
> > I don't want to remove the KeyListener, i only want to remove the **mouseListener**
> 
> GlobalScreen.unregisterNativeHook();
> GlobalScreen.removeNativeMouseListener(Name of MouseListener object);

i need the registerNativeHook() to activate the KeyListener.
and i don't have an instance of the MouseListener. :(

**Comment by LemmoTresto** [comment]
He means disable all events for the listener so that it is purely focussed on key listeners.

**Comment by kwhat** [comment]
I am going to ask the Why question.  The reason that you cannot disable mouse listeners is because some platforms cannot distinguish between the two and there are side-effects with modifier tracking.  If this question is motivated by premature optimization, the performance impact of not listening to these events vs simply not registering a listener for mouse events in Java is marginal at best.  This was profiled as part of issue #77 using VisualVM.

**Comment by robinjos333** [comment]
```
Sep 24, 2019 12:24:35 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_event_proc [782]: Mouse dragged to 921, 729. (0X2000)

Sep 24, 2019 12:24:35 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_event_proc [782]: Mouse dragged to 920, 731. (0X2000)

Sep 24, 2019 12:24:35 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_event_proc [782]: Mouse dragged to 918, 732. (0X2000)
```

It will be great help if you explain the way to disable these mouse event logs. Thanks.
