### ISSUE TITLE
Delete JNativeHooks From Inside Code?

### ISSUE THREAD

**Issue by ghost** [kwhat/jnativehook#268]
After I have finished using it in my program. The code goes to the temp folder and attempts to delete the JNativeHook. This is after I unregister the native hook. Any ideas on how I can delete it in the program?

**Comment by kwhat** [comment]
There is a known issue on Windows where the native library doesn't clean itself up because the file is "in use" by the jvm.  There maybe a way to work around the issue using a custom class loader, but its going to be complicated and I have not had an opportunity to try and fix it.
