### ISSUE TITLE
If press keys on command prompt window then nativeKeyTyped event not receive

### ISSUE THREAD

**Issue by gaurangpatelng** [kwhat/jnativehook#270]
Hi,

Issue: nativeKeyTyped event does not receive if I press keys on command prompt.

I can receive KeyPress and KeyRelease.  But in that case very hard to identify CAPSLock status. Please let me know how I can do with minimum code. 

OS: Window10
Application: Command Prompt (without Administrator)

Thanks 
Gaurang Patel

**Comment by kwhat** [comment]
This should be resolved in the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/1967211753).  Please reopen if the problem persists.
