### ISSUE TITLE
Extend the scope to gamepads and joysticks

### ISSUE THREAD

**Issue by xinyingho** [kwhat/jnativehook#272]
I'm requesting a new feature: is it possible to extend the scope to gamepads and joysticks? Right now, there aren't any updated Java libraries to handle this kind of devices despite being an incredibly important kind of devices for everything about gaming.

**Comment by kwhat** [comment]
Gamepads and Joysticks should be handled by HID, I believe there are currently two HID libraries for Java that should be able to handle this.
