### ISSUE TITLE
Cross-Compiling Fails

### ISSUE THREAD

**Issue by peslys** [kwhat/jnativehook#276]
I tried to use [Cross-Compiling (All Platforms)](https://github.com/kwhat/jnativehook/wiki/Compiling#cross-compiling-all-platforms) instructions. 

Docker image build ends with this error:
```
Step 21/63 : RUN binutils-config --linker ld.gold
 ---> Running in c2f87d004a48
 * binutils-config: invalid switch!  Try '--help'.
The command '/bin/sh -c binutils-config --linker ld.gold' returned a non-zero code: 1
```

It worked before, but started fail when I tried make new build image. Most likely it is because Docker image build is using latest Gentoo version. Some update incompatibility appeared.

**Comment by fabmars** [comment]
Just bumped into this one too, willing to try and solve it, but the error happened after the docker was running for 10 hours or so. I'm a bit scared now :)

**Comment by fabmars** [comment]
https://forums.gentoo.org/viewtopic-t-1106116-start-0.html
Dockerfile, line 36 needs to be changed.
Trying now.... tbc

**Comment by fabmars** [comment]
line 36, `ENV LD=ld.gold` seems to do the job but the cross compiler build fails quickly after:
```
Step 31/63 : RUN emerge -vu ant
...
>>> Emerging (18 of 46) dev-java/oracle-javamail-1.5.6::gentoo
ESC[91mUnable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
ESC[0m * oracle-javamail-1.5.6.zip BLAKE2B SHA512 size ;-) ...                 [ ok ]
Unable to unshare: EPERM (for FEATURES="pid-sandbox")
 * Using: icedtea-bin-8
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
>>> Unpacking source...
>>> Unpacking oracle-javamail-1.5.6.zip to /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work
>>> Source unpacked in /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
>>> Preparing source in /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work ...
>>> Source prepared.
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
>>> Configuring source in /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work ...
Rewriting attributes
Rewriting ./build.xml
>>> Source configured.
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
>>> Compiling source in /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work ...
 * Disabling all optional ANT_TASKS
Buildfile: /var/tmp/portage/dev-java/oracle-javamail-1.5.6/work/build.xml

BUILD FAILED
Target "-push-to-maven-init" does not exist in the project "JavaMail". It is used from target "push-to-maven-prepare".
```

Probably ant-common.xml in the javamail source that isn't copied over the workdir or something like that. This is kind of dangerous to build from the build.xml ant file of those java packages now maven is used. And I'm not even sure why ant is rebuilt from the sources in the first place. The way gentoo does probably.
tbc...

**Comment by peslys** [comment]
There is my fix of Crooss-Compiling failure https://github.com/peslys/jnativehook/commit/167fb73002dcd00473e103bdb25dad65fef8a4bf

``binutils-config --linker ld.gold`` replacement tip is from 
https://bugs.gentoo.org/658054#c5

``ant`` was replaced with ``ant-core``.  JNativeHook build wasn't needed full ``ant`` with all dependencies.  ``ant-core`` was enough and it worked perfectly on my machine.

Building Docker image took a lot of hours. I published docker image (https://hub.docker.com/r/peslys/jnativehook-builder). You can use 
```
docker run -v $(pwd):/tmp/build -w /tmp/build peslys/jnativehook-builder:latest ant -buildfile cross.build.xml
``` 
to build JNativeHook. I hope downloading of 2.8G image is faster and less error prone way to build JNativeHook (I wasn't optimizing docker image size yet).

**Comment by kwhat** [comment]
All building should now happen via Github actions.  Hopefully that will make things a bit easier going forward.
