### ISSUE TITLE
eventExecutor isn't instantiated by default anymore

### ISSUE THREAD

**Issue by fabmars** [kwhat/jnativehook#277]
We're using jnativehook on another project and got issues with accents (yeah, we're french) using v2.1.0. Turns out accents are supposed to be supported in recent jnativehook builds. Though after building on the latest source code, our listener wasn't called anymore.

I checked the jnativehook source code and saw that [one executor is supposed to be instantiated by default](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/GlobalScreen.java#L669)

And just below is also written that [no listener would be called if no executor service was registered](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/GlobalScreen.java#L674).

Which is exactly what's happening since [eventExecutor isn't instanciated by default anymore](https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/GlobalScreen.java#L63).
Rather it's renewed upon GlobalScreen.registerNativeHook..provided one was already present.
https://github.com/kwhat/jnativehook/blob/2.1/src/java/org/jnativehook/GlobalScreen.java#L416

The change in the source code happened on 2017-07-30, commit 32fcd1f1ff760d1d22355a33ed07b22897954b03

At first I didn't want to believe it, but fact is, v2.1.0 the latest jnativehook build we were using when we got the accents issue, is from 2017-01-25 as both the jar and [mvnrepository](https://mvnrepository.com/artifact/com.1stleg/jnativehook/2.1.0) tell.

Quick fix for us:
```
            GlobalScreen.registerNativeHook();
            GlobalScreen.setEventDispatcher(new DefaultDispatchService()); // forcibly instantiatin eventExecutor
            GlobalScreen.addNativeKeyListener(...);
```

But I think we have a (very obvious) bug here. I'll submit a PR soon.

**Comment by kwhat** [comment]
This should be released with 2.2.0, let me know if it is still a problem.

**Comment by fabmars** [comment]
Hi,
Thanks very much to keep this project alive!

There's still one small issue. We're using gradle to build and it says:
```
* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve com.github.kwhat:jnativehook:2.2.0.
     Required by:
         project :
      > Could not resolve com.github.kwhat:jnativehook:2.2.0.
         > inconsistent module metadata found. Descriptor: com.github.kwhat:jnativehook:2.2-SNAPSHOT Errors: bad version: expected='2.2.0' found='2.2-SNAPSHOT'
```

And indeed, if you look inside the binary here: https://repo1.maven.org/maven2/com/github/kwhat/jnativehook/2.2.0/jnativehook-2.2.0.jar
you see
```
<properties>
    <revision>2.2-SNAPSHOT</revision>
```
in the META-INF/maven/com.github.kwhat/jnativehook/pom.xml file

**Comment by fabmars** [comment]
By the way, I see the jar is built with JDK 11 now (instead of the JDK 8 in the past). We'll have to drop one (very old) supported system in our project because of that, not a big deal, but I just wanted to say in case this wasn't intended.

**Comment by kwhat** [comment]
It should be a

**Comment by kwhat** [comment]
@fabmars  The jar should be JDK 8 compatible because it was suppose to be a multi-release jar.  Is that not the case?

Also have a mentioned how much I love maven?

**Comment by kwhat** [comment]
Alright, the `<revision>2.2-SNAPSHOT</revision>` in the pom is because I am not using maven's convoluted pom rewriting to version the library.  I really don't want maven making auto-magic commits back to vcs just to add a version number so it was done via the revision property which I guess is causing issues with gradel because why one earth would anything play nice together in a Java eco-system.  Maven sucks, it sucks so much it is one of the major reasons I really don't want to use Java anymore.  I've spent 100s for hours trying to get it to do something useful and it has all really just been a waste of time.  It cases issues with IDE's it cannot do normal jar versioning, everything is auto-magic and very little works out of the box.  I am open for pull requests to fix this problems, but I've really had enough of all things java.

**Comment by kwhat** [comment]
As far as the JDK 11, that looks correct.  All the normal classes are major version: 52, and there is a versions/11/ folder in the manifest for the modules jdk 11+ junk.  Unfortunately that junk looks like it was also compiled with JDK 8 because maven cannot do anything right.  JDK 1.5 had to be dropped because the language has changed so much that maintaining backward compatibility that far back with a multi-release jar is really impossible.

**Comment by fabmars** [comment]
All right, I'll do a PR :)

The JDK8 compatible thing was for our modest project to still support some x86 systems. But who cares anymore ?
https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html

**Comment by fabmars** [comment]
Right, this is incredibly crappy.
https://maven.apache.org/maven-ci-friendly.html does say that one has to use the **flatten-maven-plugin** for this ${revision} thing to work but the sentence is drowned in the middle of other things (see the "Install/Deploy" §). IOW it's not out of the box. Damn.
```
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>flatten-maven-plugin</artifactId>
            <version>1.2.2</version>
            <configuration>
              <updatePomFile>true</updatePomFile>
              <flattenMode>resolveCiFriendliesOnly</flattenMode>
            </configuration>
            <executions>
              <execution>
                <id>flatten</id>
                <phase>process-resources</phase>
                <goals>
                  <goal>flatten</goal>
                </goals>
              </execution>
              <execution>
                <id>flatten.clean</id>
                <phase>clean</phase>
                <goals>
                  <goal>clean</goal>
                </goals>
              </execution>
            </executions>
            <inherited>true</inherited>
          </plugin>
```
Once you add it to your project, it works straight away with 
`mvn -Drevision="2.2" -B --no-transfer-progress compile package`


Another solution I found is to ditch ${revision} and to use this kind of line in your continuous integration file
`mvn versions:set -DnewVersion="${GITHUB_REF#refs/tags/}" -B --no-transfer-progress compile`
(+ a second time at package time I suppose)

Would you still like a PR?

**Comment by kwhat** [comment]
Thanks for the info, I am pretty slammed this weekend but hopefully Ill have a little time to play around with it next week.

**Comment by fabmars** [comment]
There you go: https://github.com/kwhat/jnativehook/pull/367
Enjoy your week-end :)

**Comment by kwhat** [comment]
Everything looks like it is working correctly.  I left some comments in the PR, as soon as you update I'll merge it in and probably make a new release soon.

**Comment by kwhat** [comment]
Ok this should be resolved. :+1:  Thanks!

**Comment by fabmars** [comment]
GREAT!
So I don't have to update my PR do I?
Now all I need is a release on mvnrepository ;)
Thanks for your time.

**Comment by kwhat** [comment]
Yah, no need to update.  I am working on a few more things and then releasing to central hopefully this weekend?
