### ISSUE TITLE
How to distinguish typed number ?

### ISSUE THREAD

**Issue by PASTJL** [kwhat/jnativehook#279]
how to distinguish a zero typed on the left part of the keyboard from a zero typed with keyboard numeric keypad ( right part)  ?

**Comment by Aspire0ne** [comment]
I don't think there's a way right now.
After all, aren't the signals sent by a keyboard the exact same for both keys?

**Comment by AspireOne** [comment]
keyEvent.getKeyCode(), keyEvent.getKeyChar() and keyEvent.getID() returns the same value for both keys. You will get different codes for the keys using **keyEvent.getRawCode()**.

The codes for 0 (at least for me):
numpad = 96;
the left side of the keyboard = 48;

**Comment by PASTJL** [comment]
hey Matěj Pešl :

I tested also of my French Keyboard (AZERTY) /numpad .
For the 0 (Zero) :
rawcode left side => 48 modifier => 1 (Numeric are raised by shift in French keyboard)
rawcode numpad => 96  modifier => 0 ( and numpad locked for numeric) 
The same thing as you.
It does the stuff.
Certainly , i have to deal with file mapping depending on local keyboard.
So many thanks for your help...

**Comment by kwhat** [comment]
There is a location constant for number pad keys at https://github.com/kwhat/jnativehook/blob/e8337e2a9bf3faf5180215aafc0049510ba8e01b/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L103 that can be used in conjunction with `getKeyLocation()` to determine if the key pressed is in the number pad area of the keyboard.  I make no claims that this works on all configurations, so if you do get incorrect results for `getKeyLocation()` I will need more information about your operating system and version, locale and keyboard.  Debug level log output would also be useful.

I noticed you may have solved this with `keyEvent.getRawCode()` which may indeed work, but it will not be portable, possibly not even between systems of the same type.  The raw code is the code delivered by the OS for the key.  It is different between OS and could be different between keyboards or versions of this library.  If you are just hacking on stuff or working on something "vendor specific" it will be fine.

**Comment by PASTJL** [comment]
OK that is the solution, because on my keyboard ( Logitech/French / Windows 10) the two Enter keys have the same rawcode , i go back to keycode and  the getKeyLocation removes the ambiguity. I have misunderstood the meaning of getKeyLocation : I have understood java Locale ;(
I use your API to learn informatics to seniors (very beginners !!)  that begin with a PC, so we have to explain how keyboard / mouse run and your tool combined with Java FX allow to do that. 
When the project will be completed i will upload it on github. Two years ago,  I have yet upload a version without handling the numpad :
https://github.com/PASTJL/whatido3
Thanks kwhat for your API and help.
