### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by renemeuselwitz** [kwhat/jnativehook#28]
after immediate 

	    	GlobalScreen.unregisterNativeHook();
	    	GlobalScreen.registerNativeHook();

sometimes (around one in three times) there occures following exception

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/jnativehook/NativeHookException.<init>(SLjava/lang/String;)V

a workaround is to wait a little bit after the unregister.

	    	GlobalScreen.unregisterNativeHook();
	    	Thread.sleep(200);
	    	GlobalScreen.registerNativeHook();

**Comment by tomtarrot** [comment]
Looks like this issue is back on version 2.0.2

**Comment by kwhat** [comment]
@tomtarrot What platform? Can you get me a stacktrace?  Debug level log output would also be useful.

Thanks

**Comment by tomtarrot** [comment]
hey @kwhat, I am very sorry, looks like netbeans playing tricks on me, i closed netbeans and opened it again the NoclassDefError is gone though am stuck up with another error. 

Exception in thread "main" java.lang.IncompatibleClassChangeError: Expected static method org.jnativehook.GlobalScreen.addNativeKeyListener(Lorg/jnativehook/keyboard/NativeKeyListener;)V

**Comment by kwhat** [comment]
It sounds like you have a version mismatch between the (lib)?JNativeHook.[so|dll|dylib]{1} and the jar file.  Double check the jar on the classpath and make sure its a 2.0 jar and not a 1.X jar.

**Comment by tomtarrot** [comment]
Thanks very much, I just had to clean and build with netbeans. On more thing am any hint for me to disable JNativeHook logs? they are flogging my  console.

**Comment by kwhat** [comment]
Np, check the wiki.  You can turn off everything except the license notice.
