### ISSUE TITLE
Native events has wrong timestamp (property when) value 

### ISSUE THREAD

**Issue by peslys** [kwhat/jnativehook#281]
If you run demo application NativeHookDemo you should shortly mention that events timestamp/ when value oscillates (macOS and Linux OS) or always has value zero (Windows OS) (see picture bellow).

<img width="761" alt="screenshot_186" src="https://user-images.githubusercontent.com/1827054/74052355-612d0b80-49e2-11ea-839f-e3c998a177ca.png">

My fix Pull Request(s) is pending shortly.

**Comment by kwhat** [comment]
I am guessing this has been resolved with 2.2.  Please reopen if I am mistaken.
