### ISSUE TITLE
Nightly Builds are broken.

### ISSUE THREAD

**Issue by mysticdrew** [kwhat/jnativehook#283]
There has not been a nightly build since November '19. 

Also there have been a bunch of fixes/changes since 2.1.0 release. Can we get an updated release? 

I am also have an issue with getting snapshots from maven. 

I have in my build.gradle. 
```
subprojects {
    group project.group_id
    apply plugin: 'java'
    apply plugin: 'maven'
    sourceCompatibility = 1.8

    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }

    dependencies {
        compile "com.1stleg:jnativehook:2.1.SNAPSHOT"
    }
}

```

**Comment by kwhat** [comment]
As soon as sonatype gets back to me regarding my long standing bug about
the links to those nightlies not working (404), I will create a
nightlies again and get a release out the door.  Unfortunately, this
process is a metaphor for what software development inevitably becomes... A
relatively simple process of putting a file on a server and having it
served up has turned into a rube goldberg machine of scripts and services
that no one can fully understand let alone debug so we just keep making
more software to fix the current software that didn't even work right to
begin with; but someone pushed out to production in favor of money and a
"fix it later" attitude.  This is why I am leaving software development in
search of a career that can provide long term sanity and stability.  I am
tired of going to work every day and explain to my boss why something is
taking so long or why some process is so broken to just have a bunch of
blank faces stare back at me with absolutely zero comprehension of any of
the words that are coming out of my mouth and then order me to continue the
behavior that has lead to the eternal shitfire they are currently fighting.

**Comment by mysticdrew** [comment]
Sounds like you need a new job for sure! 

Though you are correct, that is pretty much how the corporate software development environment works.  Some companies worse than others.

**Comment by deinhofer** [comment]
Hey,
I am sorry for not being happy with your job. Does this mean you will also stop working on this great project??
This would really be a pity as it is a great library. We are using it for our framework of Assistive Technology (https://www.asterics.eu/).
But we need to update jnativehook in order to fix the mac hang issue (#225 ).
So I am hoping that you will still find time to improve the lib and make a new release.

If you are looking for a recent 2.1 build, I have built one today with the cross-compile docker file:
[jnativehook-2.1.20200224.zip](https://github.com/kwhat/jnativehook/files/4244908/jnativehook-2.1.20200224.zip)

**Comment by sghpjuikit** [comment]
I concur about maintaining the project. @kwhat this is a great project and it should not die. If you are thinking or planning to no longer maintain it, perhaps you could put up a notice for someone to take over?

Anyways gl with job hunting, I feel ya.

**Comment by kwhat** [comment]
I am still working on it. If you know how to use maven, check the maven branch.  That should become 2.2 as soon as action builds are working.

**Comment by kwhat** [comment]
Alright, things are back up under the actions tab.  Githubs having stability issues right now but its working and should be pushing snapshots to com.github.kwhat/jnativehook.

**Comment by kwhat** [comment]
The namespace for the project will be changing for 2.2.
