### ISSUE TITLE
Accented characters do not work 

### ISSUE THREAD

**Issue by edsonqr** [kwhat/jnativehook#288]
While the jnativehook is running, accented characters and quotation marks before words do not work. Example: ú ã "test"

**Comment by dtsw** [comment]
i can confirm, as soon as i do GlobalScreen.registerNativeHook(), the ¨ or ` etc. keys are "ignored".

**Comment by blueglyph** [comment]
Works for me, maybe you want to give a little more information, it is very vague.

**Comment by kwhat** [comment]
There was a fix for this in 2.2.0 that was just released.  If this is still and issue, please reopen and be sure to specify your OS and version.
