### ISSUE TITLE
Excessive Console Output

### ISSUE THREAD

**Issue by gamerchamper** [kwhat/jnativehook#291]
Anywhere to stop all these console lines? I tried using this code from the logger page.
`    	Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
    	logger.setLevel(Level.OFF);
    	logger.setUseParentHandlers(false);`
Doesnt work at all this is what I keep getting 
![image](https://user-images.githubusercontent.com/39221871/84580538-c2f0ee00-ada5-11ea-82d4-4fdc0f5cfbbd.png)
Its super annoying to see thousands of messages in my console pop up every second and how do i fix this?

**Comment by davidpanic** [comment]
```
Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
logger.setLevel(Level.WARNING);
logger.setUseParentHandlers(false);
```

that worked for me

**Comment by kwhat** [comment]
I've update the logger to be less verbose in 2.2, release shortly.
