### ISSUE TITLE
jnativehook doesn't capture keyboard events while working inside a VM

### ISSUE THREAD

**Issue by gce84** [kwhat/jnativehook#30]
JNativeHook doesn't catch keystrokes when working inside a virtual machine (in full-screen and windowed mode either).
In 1.2.0-RC4 demo it logs "keyCode=69 keyText=Num Lock" when switching between VM and local desktop.

Checked with VMware Horizon View Client and JNativeHook 1.1.4 and 1.2.0-RC4.
Probably related to https://code.google.com/p/jnativehook/issues/detail?id=35

**Comment by gce84** [comment]
I've tested the latest jar and it works just fine! I wasn't able to notice any significant delay, keystroke tracking works immediately (previous jar had a ~1 second delay). So I think the issue might be considered as closed.

Many thanks for your efforts!

**Comment by kwhat** [comment]
Perfect, I'll merge it today and hopefully ill have a new RC up shortly and thanks for all you help testing.  @antogerva If you discovery how to reproduce the bug, please open a new report.  If it is related to debugging, I maybe able to detect something in the native code to pause the hook while the debugger is attached.
