### ISSUE TITLE
Example code on the project page lead to 404

### ISSUE THREAD

**Issue by blueglyph** [kwhat/jnativehook#306]
In the `readme.md` file, most example and demo links lead to a '404 - Not Found' response:

> ## Demo Applicaiton
> The graphical example application was created to provided a real-time
> demonstration of raw output for all available native events.  To run the
> application simply execute the jar file provided. Source code available at 
> [src/java/com/github/kwhat/jnativehook/example/NativeHookDemo.java](src/java/com/github/kwhat/jnativehook/example/NativeHookDemo.java).
> 
> ## Example Code
> * [Global Keyboard Listener](wiki/Keyboard)
> * [Global Mouse Listener](wiki/Mouse)
> * [Global Mouse Wheel Listener](wiki/MouseWheel)
> * [Thread Safety for AWT, Swing and JavaFX](wiki/ThreadSafety)
> * [Logging and Console Output](wiki/ConsoleOutput)
> * [Advanced Library Loading](wiki/LibraryLoading)
> * [Consuming Events (Unsupported)](wiki/ConsumingEvents)

**Comment by blueglyph** [comment]
The links in "Example Code" point to a wiki that seems empty.
For the "Demo Application", that points to an "./example" subdirectory, no idea where this should lead.

**Comment by blueglyph** [comment]
Compiling Instructions also lead to the wrong URL... has all the documentation moved to another place?

**Comment by kwhat** [comment]
its on the 2.2 branch

**Comment by kwhat** [comment]
Forgot the main/ path.  Should be fixed

**Comment by kwhat** [comment]
Fixed the rest of the broken links.
