### ISSUE TITLE
App terminated on unregister

### ISSUE THREAD

**Issue by DivByO** [kwhat/jnativehook#311]
I need to register global hotkey for short period of time. I register it, it works, but when i call `GlobalScreen.unregisterNativeHook();` my app trminates without errors. What am i doing wrong?

**Comment by DivByO** [comment]
Sorry this seems fixed in jnativehook-2.2-20200831.215448-14

**Comment by kwhat** [comment]
Yah, there is a lot fixed in 2.2... I just need to roll it out officially.
