### ISSUE TITLE
Setting listeners priority?

### ISSUE THREAD

**Issue by leandrocm86** [kwhat/jnativehook#314]
Hi! I'm trying to make a key "remapper" for games (like inputting Arrow_UP when pressing W). Problem is that it seems the game receives the key event before my java app (the app isn't even listening the events when the game is running). Is there a way to tell Windows that my app (or any JNativeHook listener) should receive the event first?

**Comment by kwhat** [comment]
The native hook is already installed at the highest level available from the OS.  The game is probably using direct/raw input which is beyond the scope of this library at the moment.  Is in short, not really and probably not in the immediate future.
