### ISSUE TITLE
can add  read and write local file hook?

### ISSUE THREAD

**Issue by zengfr** [kwhat/jnativehook#315]

**Comment by kwhat** [comment]
I don't quite understand your question.  Can you add more details?

**Comment by zengfr** [comment]
> I don't quite understand your question. Can you add more details?

how  to hook windows system api "writefile" "writefileex" ? only see keyboard and  mouse hook  exaple case.
https://docs.microsoft.com/zh-cn/windows/win32/api/fileapi/nf-fileapi-writefileex
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile

**Comment by kwhat** [comment]
Only mouse and keyboard hooks are supported via SetWindowsHookEx at this time.
