### ISSUE TITLE
How to prevent the shortcut to be triggered again by other apps?

### ISSUE THREAD

**Issue by hp7hao** [kwhat/jnativehook#318]
Hi there, I'm working on a clipboard management tool and I'm very excited about this cool library.
But I'm stuck somewhere.

I'm listening to a key combination to show main window, let's say the combination is ctrl+shift+v.
For this combination is defined in some other apps, like konsole a terminal emulator under KDE.

If my current active window is konsole, when the shortcut is triggered, the action defined in konsole will be triggered first and then my own code.

What should I do if I want the shortcut to be triggered first in my own code and prevent it to be triggered again in other apps?

Any advice is welcomed!

**Comment by kwhat** [comment]
In short, you can't.  The hook sits as low as it can in the dispatch queue on Windows and OS X but there is no way to guarantee that it is first.  On X11 we only get a copy of the event sent out so there is even less control.  There is probably no easy way around this problem without getting down into the kernel level with a custom driver or something like that.

**Comment by hp7hao** [comment]
Thanks for replying. I seem to be heading in the wrong direction to implement the behavior. Actually it's more like a system level problem, maybe I should make my app a daemon and turn to some system facilities like window manager to call my own functionalities.

**Comment by kwhat** [comment]
You may want to look into dbus.  I don't know a whole lot about it but it does sit lower in the chain of things and maybe able to do what you need.  If it does work out for you, let me know. It could be useful for this library.

**Comment by hp7hao** [comment]
I just read some documents about DBus and did some test in my toy project.
By using the DBus, I do get the expected behavior, but I must do some system-wide setups.
e.g. I register Ctrl+Shift+v to trigger a dbus action to call the functions defined in my own code.
If I want to make the shortcut registration work out of box,  I may need some other libraries to do the trick

**Comment by kwhat** [comment]
Ah I see, so the dbus shortcut must be specified up front to get it to trigger a callback.  There is no way to listen for all incoming events?  If your toy project is open source, let me know I would be interested in taking a look at how it ends up working.  Thanks for the update.

**Comment by hp7hao** [comment]
I don't have much off work time on this these days, but as far as I can tell, the dbus as a RPC framework, it's probably not a place where we can listen to all the system events.
The dbus code in my project is pretty simple (please don't mind my poor starter open source project :)

https://github.com/youkabeng/pastehero/blob/master/src/main/kotlin/me/phph/app/pastehero/dbus/DBus.kt
https://github.com/youkabeng/pastehero/blob/master/src/main/kotlin/me/phph/app/pastehero/dbus/DBusImpl.kt
https://github.com/youkabeng/pastehero/blob/master/src/main/kotlin/me/phph/app/pastehero/gui/JFXApp.kt

And call the "show" method by issuing the following command
`
qdbus me.phph.app.pastehero /pastehero show
`

When connected to dbus, the app is supposed to be callable and the triggers are transparent to my code.
But the mechanism works pretty well in my app.

I may revisit it later.
