### ISSUE TITLE
NativeMouseEvent when is always 0 since 2.1.0

### ISSUE THREAD

**Issue by scheilch** [kwhat/jnativehook#331]
Hello,

I used your library to build an open source project from the scratch. I am sorry to say, that there are some bugs in it.
The first one is that there is no timestamp any more in the events. So there is no chance to replay the user interaction in the same speed as recorded.
The next I'v found is that the key typed event has no valid key in it. Only the press and release event ech have the pressed key.

**Comment by kwhat** [comment]
I think this was resolved by a [pull/282](https://github.com/kwhat/jnativehook/pull/282), please reopen if this is still a problem with 2.2.
