### ISSUE TITLE
UnsatisfiedLinkError: I get this error on running the compiled code.

### ISSUE THREAD

**Issue by KeithBrown39423** [kwhat/jnativehook#338]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jnativehook.DefaultLibraryLocator
        at org.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:96)
        at AutoClicker.main(AutoClicker.java:32)

Can anyone help me?

**Comment by kwhat** [comment]
Probably couldn't find a native code for your architecture and operating
system

**Comment by KeithBrown39423** [comment]
how do I fix that?

**Comment by kwhat** [comment]
Let's start with what is your operating system and its architecture

**Comment by KeithBrown39423** [comment]
windows 10 but i have no clue what you mean by its architecture

**Comment by kwhat** [comment]
Is it 32 bit or 64 bit and is it arm or intel?

**Comment by KeithBrown39423** [comment]
amd athlon silver 64 bit

**Comment by kwhat** [comment]
And there should be more console output with that failure about what failed.  What version of the library are you using?

**Comment by KeithBrown39423** [comment]
2.1.0

**Comment by kwhat** [comment]
run the jar from the command line and see what the output is.  There should be a message associated with that exception.

**Comment by KeithBrown39423** [comment]
what jar?

**Comment by kwhat** [comment]
`java -jar jnativehook-2.1.0.jar`

**Comment by KeithBrown39423** [comment]
Error: Unable to access jarfile jnativehook-2.1.0.jar

**Comment by kwhat** [comment]
cmon dude, read the error.  where is jnativehook-2.1.0.jar?  not in the directory you ran that from...

**Comment by KeithBrown39423** [comment]
JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2016 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


gives me this plus a window that updates every mouse movement

**Comment by kwhat** [comment]
The library is working by itself, so something about the way you are using it is causing a problem. How are you using it with your project?  The short answer is you need to setup an appropriate java.library.path.

**Comment by KeithBrown39423** [comment]
https://pastebin.com/ZJYX72YG

**Comment by KeithBrown39423** [comment]
that is how im using it
