### ISSUE TITLE
Cant Detect Extra Mouse Buttons 8 and 9 as a Key.

### ISSUE THREAD

**Issue by MahdeenSky** [kwhat/jnativehook#341]
I'm trying to bind it to mouse buttons 8 and 9, which is easily detected by firefox, but not by the application.
I found they are buttons 8 and 9 through xev.

**Comment by xplatform-dev** [comment]
There is not support for mouse buttons above 5. Your mouse might be registering the scroll wheel as 6 and 7 but those are mouse wheel events. See `jni.include.org_jnativehook_mouse_NativeMouseEvent.h`, `libuiohook.include.uiohook.h`, and `java.org.jnativehook.mouse.NativeMouseEvents.java`. All 3 of these files would need to be updated to suit your needs.

These are also most likely programmable macros which are usually broken up into their own events - and looking at the other comments here, I would try disabling the logger to reduce the performance impact that it has in attempt to capture the macros. I have personally played games not be able to register the inputs from a pre-configured macro that came with the mouse's software.

**Comment by kwhat** [comment]
Just to shed a little light on this, the reason that mouse buttons above 5 are not supported is because OSX barely supports 4 & 5.  I don't think windows does either, at least without some helper software.  X11 will support 10 IIRC, but who cares about Linux.

**Comment by kwhat** [comment]
We maybe able to resolve this with a small patch [here](https://github.com/kwhat/libuiohook/blob/d8e405072043702cf6577f5115ae95fa4116cc14/src/x11/input_hook.c#L593) and [here](https://github.com/kwhat/libuiohook/blob/d8e405072043702cf6577f5115ae95fa4116cc14/src/x11/input_hook.c#L688).  I think we can just do something like `button = map_button;` in the default case but there isn't anyway I am going to be able to test this.  

@MahdeenSky What mouse do you have that can generate mouse button 8 & 9?

**Comment by MahdeenSky** [comment]
> We maybe able to resolve this with a small patch [here](https://github.com/kwhat/libuiohook/blob/d8e405072043702cf6577f5115ae95fa4116cc14/src/x11/input_hook.c#L593) and [here](https://github.com/kwhat/libuiohook/blob/d8e405072043702cf6577f5115ae95fa4116cc14/src/x11/input_hook.c#L688). I think we can just do something like `button = map_button;` in the default case but there isn't anyway I am going to be able to test this.
> 
> @MahdeenSky What mouse do you have that can generate mouse button 8 & 9?

the razer essential mouse

**Comment by kwhat** [comment]
Alright I looked into this and 8 & 9 should be the side buttons on the Razer and should be handled by XButton1 & XButton2.  I made some changes to the way buttons were translated recently and these appear to working for me in the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/2000883897). 

Let me know if you are still having an issue and I can look into this further.
