### ISSUE TITLE
How can i force compiling for all supported os?

### ISSUE THREAD

**Issue by VanFanelia** [kwhat/jnativehook#35]
Hi,
can you tell me how i can force ant to compile the native libraries for all supported operation systems instead of just my local one? 

After running the build succesfully i have only compiled the native hooks for /lib/linux/x86_64/ . 

Thx for you help and your useful library,

Van

**Comment by kwhat** [comment]
Hi Van,

You will need to install a cross compiler tool-chain for each of the target platforms you would like to compile for.  That will be an interesting challenge depending on your Linux distribution.  I know Ubuntu has some 3rd party packages for the Apple linker and assembler and probably has mingw packages as well.  I don't know how to set them up for that platform so you will need to consult their documentation.  I personally use a custom fork of Gentoo's crossdev I created that includes support for Apple tool-chains to compile the distribution library.  You can find the portage overlay here: https://github.com/kwhat/crossdev-apple-overlay

If you just need to Apple tool-chains you can try compiling the bintuilts-apple project from source.  It requires that you build with LLVM's clang but should compile on _any_ GNU Linux.  See project page: https://github.com/kwhat/binutils-apple  Note that you will need to get a copy of your own headers for the SDK you want to target.  Its a pain, but you can extract them from the XCode dmg or the cli tools depending on the version.  Let me know if you need more info on that.

There is a cross_compile branch in the JNativeHook project that contains all of the properties and scripts for building with cross compilers.  You should just be able to run `ant -buildfile package.xml` to compile full version for all the property files in that branch.

**Comment by kwhat** [comment]
Please re-open if you have any other questions.

-Alex
