### ISSUE TITLE
[feature request] Is it possible to allow separate keyboard / mouse detectors in the native layer?

### ISSUE THREAD

**Issue by tactoth** [kwhat/jnativehook#360]
Reason being that I find the mouse detector causes mouse movements on my Mac laptop to fail (i.e. fail to click, dragging get abandoned).

However, when I enable the hook, keyboard use is not affected.

So I want to just enable the keyboard support. (In the native layer, not by just not adding the listeners). I could use other ways to detect mouse movements (i.e. PointerInfo)

**Comment by kwhat** [comment]
I've thought about this, but my benchmarks didn't show any measurable performance benefit over just ignoring the events.  Additionally, some platforms do not allow ignoring these events.  If you can make a compelling case for why this should be a feature, I will look into it.  

> Reason being that I find the mouse detector causes mouse movements on my Mac laptop to fail (i.e. fail to click, dragging get abandoned).

Can you elaborate on this?  The library shouldn't have an effect on dragging or clicking unless you are trying to consume events or botched something on the dispatch loop.

**Comment by kwhat** [comment]
Please reopen with more information if you are still interested in working though this issue.
