### ISSUE TITLE
why can't work on game

### ISSUE THREAD

**Issue by lastthing** [kwhat/jnativehook#361]
I make java a exe And I start it, but it can't work on the game.

**Comment by lastthing** [comment]
it can work when mouse and key not in the scope of the game window

**Comment by ghost** [comment]
@lastthing please see:

- https://www.qamadness.com/how-to-write-a-bug-report-a-brief-guideline/
- https://www.wrike.com/blog/how-write-a-bug-report/
- http://sscce.org/

The more information you give, the more likely the problem can be solved.
