### ISSUE TITLE
JNativeHook crashes on runtime when exported from Eclipse

### ISSUE THREAD

**Issue by JakePaustian** [kwhat/jnativehook#371]
Sorry, I know this isn't likely a bug as much as it is a problem with my own code, but I wanted to try reaching out anyways. My issue is that I have a perfectly functioning program within Eclipse that throws this error when ran in command prompt as a runnable jar:
___________________________________________________________________________
Oct 13, 2021 1:12:03 AM com.github.kwhat.jnativehook.GlobalScreen <clinit>
SEVERE: Illegal char <:> at index 19: C:\Users\jakep\rsrc:jnativehook-2.2.0.jar!\/com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.UnsatisfiedLinkError: Illegal char <:> at index 19: C:\Users\jakep\rsrc:jnativehook-2.2.0.jar!\/com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll
        at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:91)
        at GlobalKeyListenerExample.main(GlobalKeyListenerExample.java:29)
        ... 5 more
___________________________________________________________________________

MY CODE:

import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;
import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;

public class Main implements NativeKeyListener {
	public static void main(String[] args) {
		try {
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
			System.err.println("There was a problem registering the native hook.");
			System.err.println(ex.getMessage());

			System.exit(1);
		}
		GlobalScreen.addNativeKeyListener(new Main());
	}
	
	public void nativeKeyReleased(NativeKeyEvent e) {
		if (e.getKeyCode() == NativeKeyEvent.VC_ENTER) {
			try {@SuppressWarnings("unused")
			Thingy thingy = new Thingy();} catch (Exception e1) {}
		}
	}
}
________________________________________________________________________________
I'm nearly certain this is just an issue with the GlobalScreen.registerNativeHook();, but I haven't the foggiest what I would need to change in order to address this? Am I missing something? Thanks again.

**Comment by kwhat** [comment]
I am pretty sure this is related to issue #369.  Use the latest snapshot from that ticket and see if your problem goes away.

**Comment by JakePaustian** [comment]
Hi, thanks for the quick reply. That was not the problem unfortunately. I'm running the runnable jar from my Desktop, a file path with no spaces in it. I tried moving around to various locations and I got the same error every time I'm afraid.

**Comment by kwhat** [comment]
I cannot seem to duplicate this issue and I suspect it is an eclipse is doing something clever problem.

`Illegal char <:> at index 19: C:\Users\jakep\rsrc:jnativehook-2.2.0.jar!/com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll`

Why does this path `C:\Users\jakep\rsrc` end in a `:`?

Something in the try block [here](https://github.com/kwhat/jnativehook/blob/2.2/src/main/java/com/github/kwhat/jnativehook/GlobalScreen.java#L76) is throwing an exception.  It would probably be helpful if that did a `e.printStackTrace()` in the catch block or at least `setStrackTrace` on the new object.

**Comment by kwhat** [comment]
Zip me up an eclipse test project and tell me what to do in order to produce the error.

**Comment by JakePaustian** [comment]
[TheGreatestRickRoll.zip](https://github.com/kwhat/jnativehook/files/7340473/TheGreatestRickRoll.zip)

As stupid as this sounds, my test project is just me trying make it so when someone hit the Enter key it rick rolls them haha. Because of the filesize, I just removed the music files. All you should have to do is get the project into eclipse, have it's build path find the jnativehook-2.2.0.jar, and export it as a runnable jar with "Package Required Libraries into generated JAR" checked.

**Comment by JakePaustian** [comment]
"Why does this path C:\Users\jakep\rsrc end in a :?"
I have positively no clue what this line is talking about either.

**Comment by kwhat** [comment]
Works for me, I cannot duplicate the issue.

**Comment by JakePaustian** [comment]
Ugh, alright then. I don't even know what to try next because the code must be fine and something must be up elsewhere. Sorry for taking up your time.

**Comment by kwhat** [comment]
Its fine, try running the jar directly.  `java -jar JNativeHook-2.2.0.jar`

**Comment by kwhat** [comment]
You can probably work around the problem by manually extracting the appropriate DLL from the jar and putting it in the same folder as the jar.  Look in `com/github/kwhat/jnativehook/lib/windows/x86_64`

**Comment by JakePaustian** [comment]
You mean like this? I'm not having any luck if so. I am able to run "JNativeHook-2.2.0.jar" however.
![image](https://user-images.githubusercontent.com/87162217/137199137-466ba3f5-cca6-47f2-8909-580397d0d90c.png)

**Comment by kwhat** [comment]
> You mean like this? 

No more running the JNativeHook.jar and the dll should go with it.  I think it was just in your home directory.

**Comment by JakePaustian** [comment]
Ah, I got it working finally haha. I had to totally switch gears and I just imported the entire source code into my project. Not a great fix but it works atleast. Thanks again for all the help!

**Comment by yichen88** [comment]
Same issue happens in command-line application with spring-boot.

For snapshot versions : 2.2-20210323.163306-38 it works without problem.
But for non-snapshot version(2.2.0, 2.2.1), same issue.

--------------not work log-------------------
23:02:10.020 [main] INFO com.frienmo.iopt.AutoPlayApp - STARTING THE APPLICATION
23:02:10.653 [main] INFO  com.frienmo.iopt.AutoPlayApp - Starting AutoPlayApp v0.1.4-SNAPSHOT using Java 11.0.10 on DESKTOP-8HDOUAL with PID 19424 (C:\Users\tang\IdeaProjects\iopt-auto-play\auto-play-core\target\auto-play-core-0.1.4-SNAPSHOT.jar started by tang in C:\windows\system32)
23:02:10.653 [main] DEBUG com.frienmo.iopt.AutoPlayApp - Running with Spring Boot v2.4.0, Spring v5.3.1
23:02:10.654 [main] INFO  com.frienmo.iopt.AutoPlayApp - No active profile set, falling back to default profiles: default
23:02:11.272 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFERRED mode.
23:02:11.353 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 74 ms. Found 2 JPA repository interfaces.
23:02:11.798 [main] ERROR com.github.kwhat.jnativehook - Illegal char <:> at index 24: C:\windows\system32\file:\C:\Users\tang\IdeaProjects\iopt-auto-play\auto-play-core\target\auto-play-core-0.1.4-SNAPSHOT.jar!\BOOT-INF\lib\jnativehook-2.2.0.jar!\/com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll
23:02:11.799 [main] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'robotPlayer' defined in URL [jar:file:/C:/Users/tang/IdeaProjects/iopt-auto-play/auto-play-core/target/auto-play-core-0.1.4-SNAPSHOT.jar!/BOOT-INF/classes!/com/frienmo/iopt/RobotPlayer.class]: Instantiation of bean failed



-------- work log --------
23:09:40.868 [main] INFO  com.github.kwhat.jnativehook - Found existing library: C:\Users\tang\AppData\Local\Temp\JNativeHook-2.2.0-SNAPSHOT.x86_64.dll (2.2.0-SNAPSHOT).

23:09:40.874 [main] INFO  com.github.kwhat.jnativehook - hook_get_auto_repeat_rate [129]: SPI_GETKEYBOARDSPEED: 31.



THANK YOU

**Comment by kwhat** [comment]
>  23:02:11.798 [main] ERROR com.github.kwhat.jnativehook - Illegal char <:> at index 24: C:\windows\system32\file:\C:\Users\tang\IdeaProjects\iopt-auto-play\auto-play-core\target\auto-play-core-0.1.4-SNAPSHOT.jar!\BOOT-INF\lib\jnativehook-2.2.0.jar!/com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll

I am just guessing, but it's probably something in or around [here](https://github.com/kwhat/jnativehook/blob/2.2/src/main/java/com/github/kwhat/jnativehook/DefaultLibraryLocator.java#L88).  I need detailed instructions on how to reproduce this, not it doesn't work with my IDE.  IDE's do a lot of automatic junk that could be causing this.  Set it up to work with JNI and it wont be an issue.
