### ISSUE TITLE
Make path to extracted dll / so configurable

### ISSUE THREAD

**Issue by MichaelEnke** [kwhat/jnativehook#377]
Hello,
I would like to propose a simple change to make the location of the extracted library configurable.
Reason: In our application the jar file resides in a read-only share.
In file _DefaultLibraryLocator.java_, change:
`String libPath = classFile.getParentFile().getPath();`
to
`String libPath = System.getProperty("jnativehook.lib.extractPath", classFile.getParentFile().getPath());`

Thank you,
Michael

**Comment by kwhat** [comment]
Well, the good news is I am currently making some enhancements to this right now.  How does a property like jnativehook.lib.path sound?  Ex: `java -Djnativehook.lib.path=/home/user/lib`?

**Comment by kwhat** [comment]
Ah you beat me to it, sure ill put it in right now.

**Comment by kwhat** [comment]
Resolved, should be in the [latest snapshot](https://github.com/kwhat/jnativehook/actions/runs/1386753123) as soon as it builds.

**Comment by MichaelEnke** [comment]
That was fast ... :-) 👍
