### ISSUE TITLE
Extraction of dll fails if path to jar contains space

### ISSUE THREAD

**Issue by MichaelEnke** [kwhat/jnativehook#386]
Hi,
in DefaultLibraryLocator there is the following line:
File classFile = new File(classLocation.getPath());
If the path contains space(s), the classLocation.getPath() returns something like /C:/Program%20Files/...
To replace the %20 with a space, change to:
File classFile = new File(URLDecoder.decode(classLocation.getPath(), StandardCharsets.UTF_8));

Thanks.

**Comment by kwhat** [comment]
It has already been resolved.  I am working on a large OS X bug then I'll do a release.
