### ISSUE TITLE
"Key Typed: Undefined", but the pressed and release events are properly detected.

### ISSUE THREAD

**Issue by QazCetelic** [kwhat/jnativehook#387]
When using the `GlobalKeyListenerExample`, and typing `hello`, these are the results. I'm guessing something isn't working right that detects the typed keys.
```
Key Pressed: H
Key Typed: Undefined
Key Pressed: E
Key Typed: Undefined
Key Released: H
Key Released: E
Key Pressed: L
Key Typed: Undefined
Key Released: L
Key Pressed: L
Key Typed: Undefined
Key Released: L
Key Pressed: O
Key Typed: Undefined
Key Released: O
```

**Comment by kwhat** [comment]
What code is producing this and on what operating system?  I am guessing you are doing something like `NativeKeyEvent.getKeyText(e.getKeyCode())` which is working as intended for key typed events because they produce a keycode of VC_UNDEFINED.  This is the same behavior as AWT.

**Comment by QazCetelic** [comment]
I misunderstood how key events work.

**Comment by kwhat** [comment]
You probably want e.getKeyChar(); for key typed events.
