### ISSUE TITLE
Does not run on jre 1.8

### ISSUE THREAD

**Issue by MichaelEnke** [kwhat/jnativehook#389]
In DefaultLibraryLocator the method URLDecoder.decode(String, Charset) is used which is not available in 1.8.
Instead please use URLDecoder.decode(String, String) (with catching UnsupportedEncodingException).
Thank you.

**Comment by kwhat** [comment]
Can you give me a line number, I'm not seeing it in https://github.com/kwhat/jnativehook/blob/2.2/src/main/java/com/github/kwhat/jnativehook/DefaultLibraryLocator.java

**Comment by MichaelEnke** [comment]
Oh, that report has wrong subject, sorry. Was about a change I did locally.
The problem is with Windows and space(s) in the path:
classLocation.toURI() returns file:/C:/Program%20Files/...
classLocation.getPath() returns /C:/Program%20Files/...
To fix it, please add a URLDecoder.decode(String, String) (and not URLDecoder.decode(String, Charset).

**Comment by kwhat** [comment]
That should have been fixed in 2.2.1, is it still a problem?

**Comment by MichaelEnke** [comment]
Oh yes, sorry, I was on 2.2 branch ...
