### ISSUE TITLE
Caps Lock not implemented

### ISSUE THREAD

**Issue by himion0** [kwhat/jnativehook#39]
Hi its Harry! I've noticed that you haven't implemented Caps lock

**Comment by kwhat** [comment]
So I have gone though the problem and it maybe be a little more involved than I originally thought.  Adding the caps lock key events to Darwin is relatively simple, but it got me thinking about that caps lock toggle state and that this library provides no way to access that info so I am experimenting with 3 new masks for caps, num and scroll locks.

Add these masks to Windows and X11 is straightforward enough, but I am a little confused about how Darwin uses these keys.  My Apple keyboard has NumLock printed on the clear key, but I don't know if the platform can toggle.  Same story with the scroll lock except I don't have a key for that.  Do you happen to know if Apple uses the num lock or has a scroll lock key?

**Comment by himion0** [comment]
God I'm sorry for all this trouble I've caused you :) I'm not sure if all
of them do but this is the standard keyboard. I don't think that they do
use scroll or num lock at all.

​

Regards,

Harry

**Comment by kwhat** [comment]
Hehe, don't worry about it.  I would rather find the bugs sooner than later ;)  I think I will fake a mask for the platform so it will be compatible across the network.  I just need to find what key apple uses to emulate scroll lock and pause/break. F12/F14/15?

**Comment by himion0** [comment]
yes I think so


Regards,

Harry

**Comment by kwhat** [comment]
I created a branch on this project and libuiohook called toggle masks that should handle part of the problem.  All of the know issues with this branch are on OSX and capslock is kind of getting delivered but only down and up when the mask is turn on or off.  Some creative event delivery will be required to fabricate events to match other platforms.  Feel free to tinker with it and make improvements.  I will probably finish up the changes later tonight or tomorrow.

**Comment by himion0** [comment]
Great I'll take a look :)

Regards,

Harry

**Comment by kwhat** [comment]
Hey, I just pushed a small updated that fixed some issues on linux.  On the mac side, I remembered why this wasn't implemented.  They dont provided key events for caps lock or num lock!  I can get a modifier change event that can double as a key down event, but I have no way to know when the key is release... via the documented api.  Via the undocumented api I do get a NX_SYSDEFINED event when its pressed and released (if you listen for it).  I was going to test that as a possible event src next.  See http://unix.superglobalmegacorp.com/xnu/newsrc/iokit/IOKit/hidsystem/IOLLEvent.h.html

**Comment by kwhat** [comment]
I did a little more reverse engineering on the undocumented NX api and pushed a new branch for libuiohook called mac_capslock that tires to send key release events for the caps-lock key.  Its kind of works, but there is a small issue if you press and hold the capslock key and then press the num-lock, it will trigger a release even if you are still holding it.  The good news is that the other keys that produce NX_SYSDEFINED events also produce their own key up/down events so some extra tracking __should__ be able to resolve that issue.  I have no idea what kind of coverage the NX_SYSDEFINED event has and its not really documented.  Some testing will be needed especially on later versions of OS X (>10.7).  I will post some builds of both when the latter is ready, any testing on Darwin would be appreciated as I don't have access to modern hardware at this time.

**Comment by himion0** [comment]
Ok great sounds good. I've noticed with the caps lock key on mac that there
is a weird delay such that if you've turned it on and off and try to to
turn on it on immediately after, it won't come on even though you've
pressed it. I'm not sure if this is related to any of the problems that
you've been encountering. I'm guessing this is to prevent accidental caps
lock usage. Apparently you can turn it off and on by:


   1. Open *System Preferences*
   2. Click *Keyboard*
   3. Click *Modifier Keys...*
   4. Select your keyboard from the *Select keyboard:* list.
   5. Set the *Caps Lock Key:* to *No Action*.
   6. Press *OK*.
   7. Ensure your Caps Lock no longer works on your keyboard.
   8. Click *Modifier Keys...* again.
   9. Set the *Caps Lock Key:* to *Caps Lock*.
   10. Press *OK*.

(Source
<http://superuser.com/questions/317900/eliminate-macbook-capslock-delay>)

However this has to be done every single time the computer is turned off or
on. If your tracking the state of the caps lock key being activated or not,
then this shouldn't be an issue.

Regards,

Harry

**Comment by kwhat** [comment]
Here is the hack that will probably go into production:  [JNativeHook-2.0.20150110_osxhack.jar](http://public.callutheran.edu/~abarker/JNativeHook/JNativeHook-2.0.20150110_osxhack.jar)

Here is the fallback to mimic the Darwin behavior on all platfoms:  [JNativeHook-2.0.20150110_lcd.jar](http://public.callutheran.edu/~abarker/JNativeHook/JNativeHook-2.0.20150110_lcd.jar)

**Comment by himion0** [comment]
I'm using a mid 2012  - 2.9 ghz running Yosemite

**Comment by kwhat** [comment]
Give the _osxhack.jar a try, it should produce key up events for the capslock key when it is released.  If it does not, we will need to use the toggle approach based on the caps-lock state which has been implemented in the _lcd.jar for all platforms.  I will try to test on a 10.10 machine as soon as I can, but that probably wont happen for another week.

**Comment by kwhat** [comment]
Hey Harry, This appears to be working for me on 10.10 but the release codes are incorrect.  I don't think its related so I am going to merge it ;)

**Comment by himion0** [comment]
Cool great I've been too busy with stupid threads hahaha I'll check its
working on mine and let you know ASAP. Thanks for talking to me by the way!
:)

Regards,

Harry

**Comment by kwhat** [comment]
NP, I just made a small change to fix that key-up code being incorrect.  I'll do the merge tonight.

**Comment by kwhat** [comment]
Well that didn't go as smoothly as I thought.  It doesn't look like there is an easy way to get the caps-lock key state at hook start on mac.  The best I could find is the following but I have no idea what kinds of requirements this stuff needs.

http://svn.netlabs.org/repos/vbox/trunk/src/VBox/Frontends/VirtualBox/src/darwin/DarwinKeyboard.cpp

Particularly these two:
static UInt32 darwinQueryHIDModifiers(void);
static void darwinHIDKeyboardCacheDoUpdate(void);

**Comment by kwhat** [comment]
Just merged the working part of the changes to the trunk.  Ill probably create a feature request for the modifier masks part that is being difficult on a mac.

**Comment by kwhat** [comment]
There is finally a full solution to this issue upstream @ https://github.com/kwhat/libuiohook/issues/28 It should make it into the next release.

**Comment by kwhat** [comment]
This should be resolved at in the latest nightly.  See https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/  

Thanks for the bug report.
