### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by VanFanelia** [kwhat/jnativehook#40]
Hi,
how can i supress the debug information of the library? 
Every mouse move and every keystroke spams the console like this:

Jan 11, 2015 5:21:14 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFORMATION: hook_event_proc [598]: Mouse moved to 108, 497. (0)

Can i deactive this information log?

Greetings,
Van

**Comment by kwhat** [comment]
Did you follow the guide at https://github.com/kwhat/jnativehook/wiki/Usage#logging-and-console-output

**Comment by VanFanelia** [comment]
Hi Alex,
thanks for you fast support :)
I still have the console logs. I used your logger information : 
final Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
logger.setLevel(Level.OFF);

and also checked, that i use the right version (2.0.0RC5),
but the console log still appears.

**Comment by kwhat** [comment]
Hey Van,

No problem,  I just reopened the issue.  Can you provide a small example that illustrates the problem?  I suspect the problem is probably the console handler but I won't know for sure until I get to a computer.  Thanks!

**Comment by kwhat** [comment]
Something lime this may work....

    Handler[] handlers = Logger.getLogger("").getHandlers();
    for (int i = 0; i < handlers.length; i++) { 
        handlers[i].setLevel(Level.ALL);
    }
 Sorry for the format, on my phone.

**Comment by kwhat** [comment]
That should be Level.OFF ;)

**Comment by VanFanelia** [comment]
Thx, that worked for me :)
I set the log level of the handler to warn. 
If i get the logger with with Logger.getLogger(String) the change of the log level has no effect.

Again, thanks for your fast support.

Greetings, 
Van
