### ISSUE TITLE
NativeKeyEvent.getKeyCode() mismatch

### ISSUE THREAD

**Issue by Nvreformat** [kwhat/jnativehook#41]
[v2.0.0-RC5]
The java event nativeKeyReleased gives the wrong key code (usually the correct one + 8). nativeKeyPressed works fine though. 

I'm running Xubuntu 14.10 x64

**Comment by kwhat** [comment]
Hi, Thank you for the bug report.  I think I may have already fixed that in the trunk, but just in case its still an issue, can you provide a few example keys so I can confirm?  A, S, D keys?  What keyboard are you using and what language 104 key US English?

**Comment by Nvreformat** [comment]
For example:
nativeKeyPressed for key A gives keycode 30
nativeKeyReleased for key A gives keycode 38
nativeKeyPressed for key Space gives keycode 57
nativeKeyReleased for key Space gives keycode 65

and so on. However, this does not happen with all keys, arrow keys for example have the following behavior:
nativeKeyPressed for key Arrow Up gives keycode 57416
nativeKeyReleased for key Arrow Up gives keycode 111

About my keyboard, I don't know how to describe it but the one in the following image has the same key layout http://www.ceratech.co.uk/product_images/language/lrg/KYBAC260-USBBLKSP-spanish.jpg
I guess it's just a standard spanish keyboard.

**Comment by kwhat** [comment]
Hey sorry for the delay.  I did some testing with RC5 and the trunk and it looks like I fixed whatever the oversight was that caused the issue in RC5 although I cant remember what it was for the life of me.  2.0 final should be ready this weekend ;)
