### ISSUE TITLE
NativeSystem locale bug

### ISSUE THREAD

**Issue by norecha** [kwhat/jnativehook#42]
NativeSystem class has a bug. Turkish I problem. Your toString() method inside the Family should call lowercase with Locale.ROOT argument. Otherwise Turkish Locale users will get  
"Unable to extract the native library /org/jnativehook/lib/**wındows**/x86/JNativeHook.dll!" 
for `private static void loadNativeLibrary()` method.

Notice the lowercase Turkish I, which is "ı" instead of "i".

See the javadoc of String.lowercase():
>This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, "TITLE".toLowerCase() in a Turkish locale returns "tıtle", where 'ı' is the LATIN SMALL LETTER DOTLESS I character. To obtain correct results for locale insensitive strings, use toLowerCase(Locale.ROOT).

**Comment by kwhat** [comment]
Should be resolved in master and branch 2.0.  There should be a maintenance release by the end of February.  If you need to work around the issue, take a look at the library locator API.
