### ISSUE TITLE
keyTyped vs keyReleased

### ISSUE THREAD

**Issue by fuh-Q** [kwhat/jnativehook#433]
What exactly does it mean for a key to be "typed" versus just using keyRelease? Are there use cases where I should be using specifically one or the other?

**Comment by kwhat** [comment]
Key down is when the key is install depressed and will "bounce" if held.

Key types events are produced directly after key up and will also bounce.
Key types events are for looking at the char produced by the key down
event.  For example, lower or upper A was produced by the OS.  This is how
languages and all kinds of things are supposed to work.

Key up events are just like key down events but they do not bounce.

Unless your interested in the char typed you probably want key up/ down.

**Comment by fuh-Q** [comment]
Ah okay, thanks 👍
