### ISSUE TITLE
Avoid ""non-static method cannot be referenced from a static....."

### ISSUE THREAD

**Issue by ofirattia** [kwhat/jnativehook#44]
If you are facing with this issue with the examples.
for example:
        GlobalScreen.addNativeKeyListener(new GlobalKeyListenerExample());
become
        GlobalScreen.getInstance().addNativeKeyListener(new GlobalKeyListenerExample());

**Comment by kwhat** [comment]
The API changed with 2.0 final to remove the singleton, which is basically useless at this point.
