### ISSUE TITLE
How can  i get the keyboard scan code，it does not change with the input method？

### ISSUE THREAD

**Issue by torjan** [kwhat/jnativehook#45]
I press the Q key on my US keyboard. The scan code is 0x10 with chinese input method，while i get 0x1E with french  input method.
How can i get the keyboard scan code which does not change with the input method?

**Comment by kwhat** [comment]
What value are you using for the scancode?  What operating system?

**Comment by torjan** [comment]
My operating system is windows 7.  The same happend on linux.

The Q scancode is 0x10,
![win7_ch](https://cloud.githubusercontent.com/assets/11289185/6476221/3e53093c-c24e-11e4-8d7c-4b8e4ab94ecf.png)

but i get 0x1E as follow picture when i switch the input method to french.
![win7_fr](https://cloud.githubusercontent.com/assets/11289185/6476225/51aaf8be-c24e-11e4-8685-d9a6563a9c25.PNG)

**Comment by kwhat** [comment]
You need to enable accessibility devices on the Mac.  I still need to look into the Windows side.

**Comment by kwhat** [comment]
So the keyCode for the Windows side is directly tied to the vkCode returned by the OS for the key pressed. The vkCode also doubles as the raw code for the platform.  I can see what the rawCode is in your screenshot, but I suspect it is different for each input method, leading me to believe that the keyboard layout is also different.  I tested with simplified Chinese on Windows 8.1 and it appears to function correctly when using a US 104 keyboard.

**Comment by kwhat** [comment]
Please provide additional info on raw codes and reopen.

**Comment by torjan** [comment]
when keyCode is 16，raw codes is 81 in chinese.
when keyCode is 30，raw codes is 65 in french.

![image](https://cloud.githubusercontent.com/assets/11289185/6959174/85ca1e20-d948-11e4-9696-453c29976c00.png)




and I have another issue, when i run JNativeHook.jar on SUSE linux, it don't capture any event as follow.
![image](https://cloud.githubusercontent.com/assets/11289185/6959244/383ea1ca-d949-11e4-8f7d-164b69d6395f.png)
