### ISSUE TITLE
Unable to extract the native library /com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll!

### ISSUE THREAD

**Issue by andrew121410** [kwhat/jnativehook#454]
So I was using a old version of jnativehook version 2.1.0 it works perfectly still, but I've been using it for years, so It's finally time to upgrade to a newer version of jnativehook so I tried to use version 2.2.2 on maven central I just had to change a few import statement lines and compiled but when I try to run my program it throws now

```
Dec 08, 2023 4:00:33 PM com.github.kwhat.jnativehook.GlobalScreen <clinit>
SEVERE: Unable to extract the native library /com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll!

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to extract the native library /com/github/kwhat/jnativehook/lib/windows/x86_64/JNativeHook.dll!

        at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:91)
        at etc...
```

**Comment by andrew121410** [comment]
Never mind I fixed it

**Comment by FelipeAumannRS** [comment]
> Never mind I fixed it

how though?
