### ISSUE TITLE
Keyboard hook notwork

### ISSUE THREAD

**Issue by Junnyjun** [kwhat/jnativehook#456]
KeyboardHook does not work with some viewer programs.

I'm averaging reading speed with page turn speed and the keyhook doesn't work.

**Comment by kwhat** [comment]
Please provide more details, what programs, what platform, how do I reproduce the problem?

**Comment by Junnyjun** [comment]
> Please provide more details, what programs, what platform, how do I reproduce the problem?

Processed, thank you!
