### ISSUE TITLE
Wrong mouse events on some computers

### ISSUE THREAD

**Issue by vasiukai** [kwhat/jnativehook#46]
JNativeHook starting from version 1.2.0rc5 sometimes returns wrong Mouse Drag event instead Mouse Click and Mouse Move. JNativeHook sometimes "swallows" Mouse Release or Mouse Press event.

There is link to video explaining the bug https://www.dropbox.com/s/ypv4a2d31qppc9d/BUG.%20JNativeHook%20D%26D.mov?dl=0

First time I saw this bug on virtual Windows 8.1 running on Mac OS X 10.10.1 using Parallels Desktop 10. It was hard to repeat on real (not virtual) Windows machines. I was able repeat it using Cpukiller3 (http://cpukiller3.software.informer.com/) with value near 100% on Windows XP on Pentium 4, Windows 7 64-Bits on Pentium i5. Exception was Windows 8.1 running on Intel Core i7 2 GHz.

**Comment by vasiukai** [comment]
Picture bellow shows Mouse Released "swallowing" situation.

![screensnapz223](https://cloud.githubusercontent.com/assets/1827054/6831749/fc2ce6ca-d32a-11e4-8e4a-c7c1ee15a798.png)

**Comment by kwhat** [comment]
So button click counts and drags are tracked manually on some platforms.  Ill do a code review and see if I can spot where its getting reset what its not suppose to.  Does this only happen on windows platforms?

**Comment by vasiukai** [comment]
I found it only on Windows machines. Mac OS X do not showed it. I do not tested it on other OS'es yet.

**Comment by vasiukai** [comment]
On Mac OS X > 10.9 Maverick running on Mac OS X 10.10 using Parallels Desktop 10 I started to get 
mouse pressed, dragged, released, moved instead of mouse click (see picture bellow).

![screensnapz228](https://cloud.githubusercontent.com/assets/1827054/6854177/44ec56a2-d3f8-11e4-965f-94bc9cd99812.png)

It is probably because of huge CPU usage. This strange result appeared using JNativeHook 1.14 and up including last release 2.0.0.

**Comment by kwhat** [comment]
For OS X Parallels, that looks like the mouse was moved during the click, and is expected behavior.  Mouse clicks are not produced if a drag event occurred.

I was able to re-produce the mouse released "swallowing" situation but only while using [synergy](http://synergy-project.org/) on OS X.  The mouse release events are directly triggered by the OS on all platforms so it is more likely an input bug with the VM or in my case [synergy](http://synergy-project.org/).

I did make a small change to the click count on mouse release in the attached build.  It may address part of this issue.

[JNativeHook-2.0.20150329.1.zip | uploaded via ZenHub](https://files.zenhub.io/551851c9f922d6ce3de525b7)

**Comment by vasiukai** [comment]
> For OS X Parallels, that looks like the mouse was moved during the click, and is expected behavior. Mouse clicks are not produced if a drag event occurred.

Do not looks like. Using the same computer and running JNativeHook Demo < 1.2.0rc5 I am getting right results. Staring from >= 1.2.0rc5 I am getting wrong results. 

JNativeHook-2.0.20150329.1.zip made this bug happen less frequently, but after few clicks I was getting mouse events swallowing too.

**Comment by kwhat** [comment]
Interesting, what log level are you at?  Try log level debug and see if you get any "Consuming the current event." messages when the mouse up disappears.

**Comment by vasiukai** [comment]
Screenshot bellow illustrates Mouse Click with "swallowed" Mouse Released event using virtual Windows 8.1 running on Mac OS X 10.10.1 using Parallels Desktop 10. These log lines looks like can help in fixing bug. 

```
<...>
Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: process_button_pressed [326]: Button 1  pressed 1 time(s). (178, 634)

Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
FINE: dispatch_event [67]: Dispatching event type 7.

Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_get_multi_click_time [113]: GetDoubleClickTime: 500.

Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: win_hook_event_proc [588]: Restarting Windows input hook on window event: 0X800C.

Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: win_hook_event_proc [588]: Restarting Windows input hook on window event: 0X800C.

Apr 02, 2015 7:37:26 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: win_hook_event_proc [588]: Restarting Windows input hook on window event: 0X800C.

Apr 02, 2015 7:37:30 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: hook_get_multi_click_time [113]: GetDoubleClickTime: 500.

Apr 02, 2015 7:37:30 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: process_mouse_moved [411]: Mouse dragged to 179, 634.

Apr 02, 2015 7:37:30 PM org.jnativehook.GlobalScreen$NativeHookThread enable
FINE: dispatch_event [67]: Dispatching event type 10.
<...>
```

![screensnapz241](https://cloud.githubusercontent.com/assets/1827054/6968613/b66286e4-d970-11e4-8a20-c9341633eb81.png)

**Comment by vasiukai** [comment]
I was using JNativeHook-2.0.20150329.1.zip.

**Comment by kwhat** [comment]
Ahhhhh I see.  It looks like when the hook is restarting it is loosing the event.  It may also be also causing issue #48 if it looses a release event.  Ill have a look this weekend.

**Comment by kwhat** [comment]
See the update to issue #47, it includes a modifier tracking fix.  You still wont get a release event, but it should recover.

**Comment by vasiukai** [comment]
Update to issue https://github.com/kwhat/jnativehook/issues/47#issuecomment-89832193 do not fixed this bug yet. I am getting the same hook restart messages without recovery https://github.com/kwhat/jnativehook/issues/46#issuecomment-88971634.

**Comment by kwhat** [comment]
I think I botched updating the submodule so none of the changes made it into that build ;(  I have included an update that should have the updates this time.  

[JNativeHook-2.0.20150406.zip | uploaded via ZenHub](https://files.zenhub.io/55229fd80d9b1bad730e8601)

**Comment by vasiukai** [comment]
Unfortunately JNativeHook-2.0.20150406.zip do not fixed bug yet.

**Comment by vasiukai** [comment]
I was able repeat it on Windows 7 64-Bits on Pentium i5 using Cpukiller3 with 100% value too.

**Comment by kwhat** [comment]
Give this nightly a try, I fixed a few problems.

[JNativeHook-2.0.20150420.jar | uploaded via ZenHub](https://files.zenhub.io/55360188a1841561262f76e4)

**Comment by vasiukai** [comment]
Using JNativeHook-2.0.20150420.jar I was unable repeat bug using Windows on Parallels. It is computers on which I was always getting buggy results. I will try repeat bug on another computers in few days.

**Comment by vasiukai** [comment]
I do not get mouse events "swallowing" on computers I tested before. Looks this bug fixed. 

I am getting a lot of 
```
Apr 30, 2015 1:38:52 PM org.jnativehook.GlobalScreen$NativeHookThread enable
INFO: win_hook_event_proc [615]: Restarting Windows input hook on window event:
0X800C.
``` 
using Windows virtual machine on Parallels. Is it Ok?
Anyway if it bug it should be another issue.

**Comment by kwhat** [comment]
Awesome, the restart is normal behavior that helps support some special windows like VMware and RDP.  Those windows do not receive events unless the hook is restarted.   You can read about more about it in issue #30.  Thanks again for testing.
