### ISSUE TITLE
Event clock gets out of sync on long run

### ISSUE THREAD

**Issue by vasiukai** [kwhat/jnativehook#47]
I changed line (https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/example/NativeHookDemo.java#L346) from
```txtEventInfo.append("\n" + e.paramString());```
to
```txtEventInfo.append("\n" + (System.currentTimeMillis() - e.getWhen())
				+ "\t" + e.paramString());```
to see how fast event listeners get notified about event.

I started demo program on Mac OS X. Everything looked good at start, but after longer run I found difference between ```e.getWhen()``` and  Java system time ```System.currentTimeMillis()``` started to grow. Not only grow but became negative what should not happen. After few hours run difference becomes > 1 second. Log screen is showing about immediately reaction on mouse move or key press. Screenshot bellow shows result after really long run.
![screensnapz225](https://cloud.githubusercontent.com/assets/1827054/6841930/399c4da6-d39a-11e4-94ed-a7d4a9aff03a.png)

This strange result appeared on Mac OS X 10.10.2 on Intel i7, Mac OS X 10.9.5 on Intel i5,  Virtual Windows 8.1 64-bits on Mac OS X 10.10.2 using Parallels Desktop 10 (see picture bellow), real (not virtual) Windows XP 32-bits on Pentium 4.

![screensnapz226](https://cloud.githubusercontent.com/assets/1827054/6842109/a23de39a-d39c-11e4-9a8b-feffc2f9c84c.png)

Virtual Ubuntu 14.05 32-bits on Mac OS X 10.10.2 using Parallels Desktop 10 showed time difference immediately (see picture bellow)

![screensnapz227](https://cloud.githubusercontent.com/assets/1827054/6842236/2bbbd702-d39e-11e4-9618-9f620de2be8c.png)

I do not get time difference grow on real (not virtual) Windows 7 64-bits on i5 and Windows 8.1 64-bits on i5.

I do not tested on other OS'es yet.

**Comment by vasiukai** [comment]
As quick workaround (not fix) I added lines
```
	void setWhen(long when) {
		this.when = when;
	}
```
after line https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/NativeInputEvent.java#L167
and 
```
	e.setWhen(System.currentTimeMillis());
```
before 
```
eventExecutor.execute(new EventDispatchTask(e));
``` 
at https://github.com/kwhat/jnativehook/blob/master/src/java/org/jnativehook/GlobalScreen.java#L560

It makes things look less worse. Assumption is ```dispatchEvent(NativeInputEvent e)``` usually is called almost immediately. Difference between real event time and Java system time is not big. We can accept this small time difference.

**Comment by kwhat** [comment]
IIRC all the supported operating systems do not deliver timestamps with their native events.  The instead provide a "sequence" number that is suppose to be pegged to the CPU.  The current event time uses that sequence number as a system time offset and does a small calculation on each event.  The time should synchronize to prevent drift, but clearly something is wrong.  The code that needs fixing is located in the following functions:

https://github.com/kwhat/libuiohook/blob/master/src/windows/input_hook.c#L130
https://github.com/kwhat/libuiohook/blob/master/src/darwin/input_hook.c#L115
https://github.com/kwhat/libuiohook/blob/master/src/x11/input_hook.c#L138

**Comment by kwhat** [comment]
I confirmed the bug on Linux (bare metal).  Does suspend to ram cause this to happen?  Ex:  Start the hook then sleep the computer for 5 min and see if the skew shows up.

**Comment by kwhat** [comment]
Also confirmed on OS X, are you seeing any `WARNING:	hook_event_proc [883]: CGEventTap timeout!` messages?

**Comment by kwhat** [comment]
I have attached a nightly that includes a fix from ca86470.  I just removed all of the over engineering stupidity and just went back to plain old timestamps.  Please re-open if its still a problem.

[JNativeHook-2.0.20150329.zip | uploaded via ZenHub](https://files.zenhub.io/55184881f922d6ce3de52599)

**Comment by vasiukai** [comment]
I do not getting big difference ```System.currentTimeMillis() - e.getWhen()``` on Mac OS X using  ```JNativeHook-2.0.20150329.zip```. Maximal delay value was < 500 ms. I am always are getting big difference on Windows and Linux (virtual and not virtual) now.

> Also confirmed on OS X, are you seeing any WARNING: hook_event_proc [883]: CGEventTap timeout! messages?

I am not getting this warning, but I am always getting another on Mac
```WARNING:	hook_event_proc [855]: Unhandled Darwin event! (0X1D)```

**Comment by kwhat** [comment]
I forgot to convert windows epoch (1601) to unix epoch (1970) so that is why the timestamp is way off on windows.

For OS X, I am seeing a delay of 0 to about 25 ms, which is a bit higher than I would have expected.  It doesn't appear to be consistent, so I guess its probably related to system load.

Linux seems to be working fine for me, the only thing I can think of is a time zone discrepancy.

[JNativeHook-2.0.20150405.zip | uploaded via ZenHub](https://files.zenhub.io/552186cb0d9b1bad730e805f)

**Comment by kwhat** [comment]
I can no longer reproduce this issue with the latest build.  Is the event timestamp drift still a problem on your end?

**Comment by vasiukai** [comment]
I can not repeat this bug too. You can close it.

**Comment by kwhat** [comment]
Awesome, thanks!
