### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Skieransa** [kwhat/jnativehook#472]
is there a way to make it so when using nativemouseinputlistener  nativemouseclicked so the click count doesnt get reset after some time

**Comment by kwhat** [comment]
No. It resets after the double click interval `jnativehook.button.multiclick.iterval` so that you can detect double / triple clicking. If you want to track the number of clicks, just increment a variable on the listener in your program.

**Comment by Skieransa** [comment]
> No. It resets after the double click interval `jnativehook.button.multiclick.iterval` so that you can detect double / triple clicking. If you want to track the number of clicks, just increment a variable on the listener in your program.

Okay
