### ISSUE TITLE
No built version

### ISSUE THREAD

**Issue by amiga** [kwhat/jnativehook#50]
Is there no way to simplify this by giving us a jar? do we need to build, I was all fired up but its too much

**Comment by kwhat** [comment]
Binaries for Linux (x86, amd64, armv6), OSX (x86, amd64) and Windows (x86, amd64) are provided in the JNativeHook-X.Y.Z.zip file under releases.

**Comment by amiga** [comment]
Oh yes, thanks very much, missed that
