### ISSUE TITLE
Input tags with type="password"

### ISSUE THREAD

**Issue by himion0** [kwhat/jnativehook#52]
When typing into an input tag on any website, the native hook doesn't pick up anything at all.

**Comment by kwhat** [comment]
Is this on OS X?

**Comment by himion0** [comment]
Yes Yosemite

On Sunday, 31 May 2015, Alex Barker <notifications@github.com> wrote:

> Is this on OS X?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kwhat/jnativehook/issues/52#issuecomment-107225558>.
>


-- 
Regards,

Harry

**Comment by kwhat** [comment]
As far as I know this is intentional on OS X to prevent key logging though the accessibility api.  It wont work on any password input.
