### ISSUE TITLE
Compilation Error? 

### ISSUE THREAD

**Issue by nonlin** [kwhat/jnativehook#54]
Windows 8.1 64 bit. 

I've done everything asked for in the compilation instructions however when running msys2 shell to compile with ant all I get as far as 

configure:3580: checking whether the C compiler works
with results with no. 
ultimately with 
configure:3651: error: C compiler cannot create executables

config.log states this was because 

configure:3602: clang -march=armv6j -mfpu=vfp -mfloat-abi=hard -Os -g -pipe -fomit-frame-pointer -flto -ffat-lto-objects -fno-stack-protector  -Wl,--as-needed,-O1 -flto conftest.c  >&5
clang.exe: warning: optimization flag '-ffat-lto-objects' is not supported
clang.exe: error: 'i686-pc-windows-gnu': unable to pass LLVM bit-code files to linker

using latest LLVM, 3.6.1

**Comment by kwhat** [comment]
I think its related to LTO in your case.  Take the `-flto -ffat-lto-objects` and possibly `-fno-stack-protector` out of your CFLAGS and `-flto` out of the LDFLAGS.  IIRC you need to use ld.gold with clang lto and I am not sure its available on Windows.  Let me know if that helps.

**Comment by nonlin** [comment]
So I tried with your recommendations. 

I get the following now. 

configure:3580: checking whether the C compiler works
configure:3602: clang -march=armv6j -mfpu=vfp -mfloat-abi=hard -Os -g -pipe -fomit-frame-pointer -fno-stack-protector  -Wl,--as-needed,-O1 conftest.c  >&5
error: unknown target CPU 'armv6j'
configure:3606: $? = 1
configure:3644: result: no

**Comment by kwhat** [comment]
What are you trying to compile for?  Windows RT?  Are you compiling on an arm computer?  Do you have binutils that targets arm installed? It sounds like you are trying to cross compile with LLVM, but you forgot to install the assembler and linker for that target.  If you did install them, you need to tell clang where they are, I think its the -b command but I don't remember off the top of my head.

**Comment by nonlin** [comment]
Windows 8.1 64 bit. 
I didn't realize I had to customize that part, wasn't mentioned in the Windows section of the compile instructions and I've never had to do this before so I have no past experiences to guide me.

So for Windows 8.1 64 bit what target do I choose and are their any links to instructions for getting the assembler and linker for said target?

**Comment by kwhat** [comment]
Huh, how did you get the build.property file?

**Comment by nonlin** [comment]
I downloaded the Release for the jnativeHook and I believe it had the build.property already.

**Comment by kwhat** [comment]
Setting the JAVA_HOME or JDK_HOME env variable should help ant find the rt.jar file.

**Comment by nonlin** [comment]
I have which is the odd part. I get no other errors related to java except for java.lang which was solved by manually putting in the rt.jar.

**Comment by kwhat** [comment]
Hmm, ant should check to see if rt.jar exists relative to JAVA_HOME and produce an error like "Could not determine ant.build.javac.bootclasspath location."  Can you paste the output with the error and let me know where JAVA_HOME is pointing to and what JDK you are using.

**Comment by nonlin** [comment]
http://puu.sh/ioQzq/cb0b5cd551.png 
JDK 1.8.0_45

I would get 

[javac] Fatal Error: Unable to find package java.lang in classpath or bootcl
asspath

BUILD FAILED
C:\Users\George\Downloads\sounds\JNativeHook-2.0.1\JNativeHook\build.xml:394: Co
mpile failed; see the compiler error output for details.

Total time: 0 seconds
