### ISSUE TITLE
JNativeHook Infinite Loop

### ISSUE THREAD

**Issue by Sourish1997** [kwhat/jnativehook#55]
Hey there. I had written an auto fill in jnativehook 1.1.4 sometime ago. As you know, the hook would not work anymore after some executions. That is why, I upgraded to version 1.2.1 and made the necessary changes in the code. Basically, the program is written to make a Robot perform a set of actions when the space key is pressed. However, it seems to me that whenever I press the space key, the NativeKeyReleased function is executed infinitely in turn causing the Robot to carry out the set of actions in an infinite loop! Below is the code that I have written. What am I doing wrong? I would like to point out that the program worked fine with version 1.1.4. Also, is there any way to not display the message that pops up about jnativehook during runtime. Lastly, I'd like to use Ctrl instead of space, but if I write VC_CONTROL, it gives me an error saying that no such constant exists. Thanks in advance for your help.

```
package org.jnativehook.example;

import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.keyboard.NativeKeyEvent;
import org.jnativehook.keyboard.NativeKeyListener;

public class AutoFill extends JPanel implements ActionListener, NativeKeyListener {
	Robot robot;
	JLabel a[];
	JTextField b[];
	JComboBox c[];
	String d[][];
	JButton e;

	public AutoFill() {
		a = new JLabel[8];
		d = new String[3][];
		d[0] = new String[]{"Visa/Master Card(Powered By ICICI Bank)", "Visa/Master Card(Powered By CITI Bank)", "Visa/Master Card(Powered By HDFC Bank)"};
		d[1] = new String[]{"VISA", "MASTER"};
		d[2] = new String[]{"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
		b = new JTextField[4];
		c = new JComboBox[3];
		a[0] = new JLabel("Select A Payment Gateway: ");
		a[1] = new JLabel("Credit Card Type: ");
		a[2] = new JLabel("Credit Card Number: ");
		a[3] = new JLabel("Card Expiry Date: ");
		a[4] = new JLabel("Month:");
		a[5] = new JLabel("Year(yyyy):");
		a[6] = new JLabel("CVV Number: ");
		a[7] = new JLabel("Name on Card: ");
		b[0] = new JTextField("Please enter you credit card number", 19);
		b[1] = new JTextField(4);
		b[2] = new JTextField(4);
		b[3] = new JTextField("Please enter your name specified on the card", 24);
		c[0] = new JComboBox(d[0]);
		c[1] = new JComboBox(d[1]);
		c[2] = new JComboBox(d[2]);
		e = new JButton(" Save ");
		setLayout(new FlowLayout());
		add(a[0]);
		add(c[0]);
		add(a[1]);
		add(c[1]);
		add(new JLabel(" "));
		add(a[2]);
		add(b[0]);
		add(new JLabel(" "));
		add(a[3]);
		add(a[4]);
		add(c[2]);
		add(a[5]);
		add(b[1]);
		add(new JLabel(" "));
		add(a[6]);
		add(b[2]);
		add(new JLabel(" "));
		add(a[7]);
		add(b[3]);
		add(new JLabel(" "));
		add(new JLabel(" "));
		add(e);
		e.addActionListener(this);
		c[0].addActionListener(this);
		try {
			GlobalScreen.unregisterNativeHook();
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
			System.err.println("There was a problem registering the native hook.");
			System.err.println(ex.getMessage());
			System.exit(1);
		}
		GlobalScreen.addNativeKeyListener(this);
		try {
			BufferedReader obj = new BufferedReader(new FileReader("info.txt"));
			for (int y = 0; y < 3; y++) {
				int t = Integer.parseInt(obj.readLine());
				c[y].setSelectedIndex(t);
			}
			for (int x = 0; x < 4; x++) {
				b[x].setText(obj.readLine());
			}
			robot = new Robot();
			robot.setAutoDelay(10);
			robot.setAutoWaitForIdle(true);
		}
		catch (Exception e) {
		}
	}

	public static void main(String args[]) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				JFrame obj = new JFrame("Autofill");
				AutoFill obj2 = new AutoFill();
				obj.setSize(600, 300);
				obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				obj.setLocationRelativeTo(null);
				obj.setResizable(false);
				obj.add(obj2);
				obj.setVisible(true);
			}
		});
	}

	public void actionPerformed(ActionEvent ef) {
		if (ef.getSource() == e) {
			try {
				BufferedWriter obj = new BufferedWriter(new FileWriter("info.txt"));
				if (b[0].getText().equals("Please enter you credit card number") || b[1].getText().equals("") || b[2].getText().equals("") || b[3].getText().equals("Please enter your name specified on the card") || b[0].getText().equals("") || b[3].getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Please fill in all details before saving!");
				}
				else {
					for (int y = 0; y < 3; y++) {
						obj.write(Integer.toString(c[y].getSelectedIndex()) + "\r\n");
					}
					for (int x = 0; x < 4; x++) {
						obj.write(b[x].getText() + "\r\n");
					}
					obj.close();
					JOptionPane.showMessageDialog(null, "File saved successfully!");
				}
			}
			catch (IOException e) {
			}
		}
	}

	public void nativeKeyPressed(NativeKeyEvent ef) {
	}

	public void nativeKeyReleased(NativeKeyEvent ef) {
		if (ef.getKeyCode() == NativeKeyEvent.VC_SPACE) {
			try {
				int temp;
				temp = c[0].getSelectedIndex() + 1;
				clickTab();
				clickDown(temp);
				robot.delay(50);
				clickTab();
				temp = c[1].getSelectedIndex();
				clickDown(temp);
				clickTab();
				type(b[0].getText());
				clickTab();
				temp = c[2].getSelectedIndex();
				clickDown(temp + 1);
				clickTab();
				type(b[1].getText());
				clickTab();
				type(b[2].getText());
				clickTab();
				type(b[3].getText());
			}
			catch (Exception e) {
			}
		}
	}

	public void nativeKeyTyped(NativeKeyEvent ef) {
	}

	public void clickTab() {
		robot.keyPress(KeyEvent.VK_TAB);
		robot.keyRelease(KeyEvent.VK_TAB);
	}

	public void type(String str) {
		byte[] bytes = str.getBytes();
		for (byte b : bytes) {
			int code = b;
			boolean decider = false;
			if (code > 96 && code < 123) {
				code = code - 32;
				decider = true;
			}
			if (decider == false) {
				robot.keyPress(KeyEvent.VK_CAPS_LOCK);
				robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
			}
			robot.keyPress(code);
			robot.keyRelease(code);
			if (decider == false) {
				robot.keyPress(KeyEvent.VK_CAPS_LOCK);
				robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
			}
		}
	}

	public void clickDown(int no) {
		for (int x = 1; x <= no; x++) {
			robot.keyPress(KeyEvent.VK_DOWN);
			robot.keyRelease(KeyEvent.VK_DOWN);
		}
	}
}
```

**Comment by kwhat** [comment]
Hi,

First by version 1.2.1 do you mean 2.0.1? If not, I would recommend upgrading to the latest version.  I did noticed one problem in your code, nativeKeyReleased(NativeKeyEvent ef) does not operate on Swings event dispatch thread by default.  If you are indeed using the 2.0.X branch, you can call `GlobalScreen.setEventDispatcher(new SwingDispatchService());` before registering the hook to run on the Event Dispatch Thread.  Take a look at the [working with swing](https://github.com/kwhat/jnativehook/wiki/Usage#working-with-swing) section of the wiki for more information.  I'm not sure why that would be causing the issue you are experiencing, but its a good place to start.  If the problem persists, try setting the log level to Level.FINEST using the following:

    Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
    logger.setLevel(Level.FINEST);
    
    // Change the level for all handlers attached to the default logger.
    Handler[] handlers = Logger.getLogger("").getHandlers();
    for (int i = 0; i < handlers.length; i++) {
        handlers[i].setLevel(Level.FINEST);
    }

Note that similar code can be used to disable the logging using Level.OFF in place of Level.FINEST.  You cannot disable the copyright notice without recompiling the library.  Please see the [Logging and Console Output](https://github.com/kwhat/jnativehook/wiki/Usage#logging-and-console-output) section of the wiki for more information about logging.

Let me know if any of that helps.
-Alex

**Comment by Sourish1997** [comment]
Hey there,

First of all, by 1.2.1, I did mean 2.0.1.Just messed up the name. Secondly, I am really sorry to bother you with this issue. Turns out that it was a flaw in my logic after all. I made the hook run on the swings event dispatch thread. Got an illegalThreadStateException and fixed that by running my Robot methods on a separate thread. Really, the reason my code is running in an infinite loop is because I make the Robot print spaces which in turn again satisfies the condition in the nativeKeyReleased function.

I just need a little more information. You said that i cannot disable the copyright notice without recompiling the library. Can you be a bit more specific? I don't really know how  to do that. 

And I also need to know the replacement for VK_CONTROL in version 2.0.1. When I use VC_CONTROL, it gives me an error saying that there is no such constant in NativeKeyEvent.

Thanks a lot,
Sourish

**Comment by kwhat** [comment]
Don't worry about it ;)  You should checkout the robot functionality built-in to the jnativehook library.  It takes the same NativeInputEvents and tries to reproduce them on the host system.  For VK_CONTROL, you can use the NativeKeyEvent VC_CONTROL_R or VC_CONTROL_L.  If you want either control key, check the mask against NativeInputEvent CTRL_MASK.

Recompiling the library is going to a little complicated, but all the information is available.  I use a number of cross compilers built on Gentoo Linux to target all platforms.  The easier approach would be to build on each platform you want to target.  There are instructions in the wiki about how to get setup and how to compile.  Linux would be the easiest and windows the hardest to get setup.  If you try to build 2.0.1 from src, run `ant distclean` first as it shipped with configuration it shouldn't have.  Version 2.0.2 will be out as soon as I stop fighting with GPG.

**Comment by Sourish1997** [comment]
Thanks a lot!! I think I'll keep the copyright notice displayed for the moment though :P. You were of great help to me.

Regards,
Sourish.

**Comment by MohnishSingla** [comment]
HI Alex,
I am facing a similar issue with respect to VK_CONTROL and new VC_CONTROL_R  or VC_CONTROL_L. can you please explain what do u mean when you have mentioned "check the mask against NativeInputEvent CTRL_MASK"?

Regards,
Mohnish

**Comment by kwhat** [comment]
Hi Mohnish,

All NativeInputEvents have a bit-mask associated with them that can be used to check the state of a modifer key.  Each bit of data represents the state of a modifier key and by using bit wise operators, you can check to see if any combination of the keys are depressed.  Something like `e.getModifierMask() & NativeInputEvent.CTRL_MASK` should do the trick. This is a fairly common concept you can read more about: 
https://en.m.wikipedia.org/wiki/Mask_(computing)

Best,
Alex

**Comment by MohnishSingla** [comment]
Hi Alex,

How can we get alphabet key which is pressed along with the combination of CONTROL or ALT or SHIFT?

Regards
Kanika

**Comment by kwhat** [comment]
Add the mask check code to either a keydown keytyped or keyup listener.  You can check the key you need and the mask in the same conditional.
