### ISSUE TITLE
Pre-Built?

### ISSUE THREAD

**Issue by Spedwards** [kwhat/jnativehook#56]
So it was suggested to me that I use jnativehook so I came here hoping to find a .jar I could just download. Unfortunately, this is not available.

I am trying to build it but ran into problems where jnitasks is apparently required. I was fine with building it until I realised I had to build something else. No. Just no. I have no idea what I'm doing here...

Please just provide a bloody jar file so I can be done with this... Preferably one with docs.

**EDIT:** I just found through some long-tail Google searches. I'd suggest making an edit to the README telling people where to find them as not everyone is an expert with Github.

**Comment by munsuri** [comment]
Man, you just had to click on <a href="https://github.com/kwhat/jnativehook/releases">releases</a> and pick the version you want :)
Although maybe a link in the readme called <a href="https://github.com/kwhat/jnativehook/releases">Download</a> would be not bad idea.

**Comment by Spedwards** [comment]
I didn't know there was a thing called "releases". That's my point.

I pushed a commit adding what you mentioned to the README so hopefully it gets added.

**Comment by kwhat** [comment]
Yah, I should add that to the readme and you can also get nightly builds from [maven](https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/)

**Comment by kwhat** [comment]
Updated, thanks!
