### ISSUE TITLE
Compilation Problem on RedHat 5.5

### ISSUE THREAD

**Issue by bnssnake1985** [kwhat/jnativehook#58]
Hi,
I have some problem in compiling the library under Red Hat 5.5. I checked all the dependencies and they are ok but the ant script fails at line 351 (libuiohook bootstrap). Could you please help me? I've also tried to download libuiohook standalone but I've similar error in the bootsrap phase.

Thanks in advance

**Comment by bnssnake1985** [comment]
I solved it adding on libuiohook configure.ac the AM_PROG_CC_C_O flag

**Comment by kwhat** [comment]
RedHat 5.5, just a little legacy? ;) Thanks for the patch, I will put it in tonight.

**Comment by kwhat** [comment]
I think the problem is with https://github.com/kwhat/libuiohook/commit/675f775d50776a359fb658c80e5241149112b6d8#diff-67e997bcfdac55191033d57a16d1408a.  Please pull 2.0 and try building again.

**Comment by bnssnake1985** [comment]
Unfortunately we still use this release in our production environment :(. 
I tried to pull the updated version (it's still tagged as 1.0 but it has modification in configure.ac) but the error still persist. Please let me know if you need further information. 
Thanks again for your support

**Comment by kwhat** [comment]
Huh, that is really strange.  According to the [docs](https://www.gnu.org/software/automake/manual/html_node/Public-Macros.html), "this is an obsolescent macro that checks that the C compiler supports the -c and -o options together. Note that, since Automake 1.14, the AC_PROG_CC is rewritten to implement such checks itself, and thus the explicit use of AM_PROG_CC_C_O should no longer be required."  What version of Automake does RHEL 5.5 ship with?  Is it RHEL 5.5 or Old, really OLD Redhat 5? Try putting AM_PROG_CC_C_O in right after AM_PROG_CC.  You're welcome ;)

**Comment by kwhat** [comment]
Can you also paste an error message?

**Comment by kwhat** [comment]
Hey, So I tried to test on CentOS 5.5 but it only comes with autotools 2.59 and the build process fails for autoconf version.  If I change the version, I get a lot of errors related to missing macros.  Please let me know what version of autoconfig you are using and the error you receive.  Thanks.

**Comment by bnssnake1985** [comment]
Sorry for the late reply. I'm using autoconf 2.64.
These are the last lines prompted by bootstrap.sh

configure.ac:76: warning: AC_CACHE_VAL(lt_prog_compiler_static_works_GCJ, ...): suspicious cache-id, must contain _cv_ to be cached
configure.ac:102: warning: AC_LIBTOOL_SETUP was called before AC_LIBTOOL_WIN32_DLL
aclocal.m4:1925: AC_LIBTOOL_WIN32_DLL is expanded from...
../../lib/m4sugar/m4sh.m4:534: AS_CASE is expanded from...
configure.ac:102: the top level
Makefile.am: C objects in subdir but `AM_PROG_CC_C_O' not in `configure.ac'
autoreconf: automake failed with exit status: 1

**Comment by bnssnake1985** [comment]
I lost your comment about adding the AM_PROG_CC_C_O. 
+# Checks for programs.
AC_PROG_CC
AM_PROG_CC_C_O
m4_ifdef([AM_PROG_AR], [AM_PROG_AR])

Now everything works :)

**Comment by kwhat** [comment]
I was never able to fully reproduce this, but I do believe the version specified was incorrect.  Autotools should have been  2.65, not  2.64.
