### ISSUE TITLE
Problem in KeyBoard Listener on method nativeKeyTyped

### ISSUE THREAD

**Issue by firster8** [kwhat/jnativehook#59]
When you try to get the KeyCode with e.getKeyCode() he gives me always 0 as answer.
He says it is undefined only the RawCode works.

**Comment by kwhat** [comment]
Are you using get getKeyCode() on a key down or up events?  That functionality behaves the same way as the java key listener, "`getKeyChar()` for events of type `NATIVE_KEY_PRESSED` and `NATIVE_KEY_RELEASED` will always return
`CHAR_UNDEFINED`."

See: https://github.com/kwhat/jnativehook/blob/7a4879eb84f8f43abbc935c7e7f34660d624fe52/src/java/org/jnativehook/keyboard/NativeKeyEvent.java#L41

**Comment by firster8** [comment]
I get UNDEFINED on key typed when I want to get the Key Code.

**Comment by kwhat** [comment]
What Operating system and which key?

**Comment by CorpWar** [comment]
I have the same problem, in public void nativeKeyTyped(NativeKeyEvent nativeKeyEvent) the nativeKeyEvent.getKeyCode() always return 0. It is working on nativeKeyPressed and on nativeKeyReleased. I run Win 7. I get this an all keys.

**Comment by kwhat** [comment]
Ahh yes, that is not a bug.  For some reason I read getKeyCode and thought getKeyChar.  Key down and up events produce "codes" and key typed events produce "chars."  Key down/up events will always have a char of CHAR_UNDEFINED and key typed events will always have a code of VK_UNDEFINED.  This should match the behavior of Java's [KeyEvent](http://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html).

**Comment by CorpWar** [comment]
I thought it was something like that. So work as intended. It would be good to add this in the documentation in NativeKeyEvent that only some information are used in some method and you can't use all the method from this class. 
Thanks for explaining, I'm good so you can close for me.

**Comment by kwhat** [comment]
I will update the docs this weekend and close.  You are welcome.
