### ISSUE TITLE
Disable Logging?

### ISSUE THREAD

**Issue by krheinwald** [kwhat/jnativehook#6]
I can not get rid of the detailed logging messages for every event like

Jun 20, 2014 3:43:31 PM java.lang.ClassLoader$NativeLibrary load
INFORMATION: hook_get_auto_repeat_delay [53]: SPI_GETKEYBOARDDELAY: 1.

Tried 

java.util.logging.Logger.getLogger("org.jnativehook").setLevel(Level.OFF);

at several steps during initialization to no avail.

**Comment by speeddown** [comment]
Dunno if native is dead but setting the logger level does nothing unless I'm missing something.

**Comment by kwhat** [comment]
@speeddown There is a wiki entry that should work.  Try the following:

```
// Get the logger for "org.jnativehook" and set the level to warning.
Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
logger.setLevel(Level.WARNING);

// Don't forget to disable the parent handlers.
logger.setUseParentHandlers(false);
```

**Comment by speeddown** [comment]
Man I'm really sorry I missed this but I will try it next time I do get a chance.

**Comment by MarkJeronimus** [comment]
`Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());` works, but it conflicts with the project's logger implementation of slf4j+log4j. Let alone suppressing superfluous messages, I can't even log warnings through our logger.
