### ISSUE TITLE
License agreement overkill

### ISSUE THREAD

**Issue by mirraj2** [kwhat/jnativehook#60]
I'm not sure whose idea it was to print out the entire license agreement to the console every time I run my program.  It is very annoying. The license is already printed in every file. No other library that I've used has done this. Please remove it.

Here is what it outputs every time:

```stupid
JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by kwhat** [comment]
Try reading the source code, you may learn something.

**Comment by mirraj2** [comment]
Lol, the file where you are printing it out is right here: https://github.com/kwhat/jnativehook/blob/master/src/jni/jni_Load.c

Despite my reading, there was not a valid explanation in the code as to why such a silly thing is being force-outputted to the consoles of all users of this library.

Since it's so important that people read and follow this license, would you like me to make a pull request that will require users to type "I accept" in their terminal before the program will proceed?

**Comment by kwhat** [comment]
Well I cant make you understand what a preprocessor directive is, how to compile the program or that it has already been removed from the 2.0 src that is staged for release... and honestly I may put it back in after dealing with you.
