### ISSUE TITLE
How does a touch screen get registered - as clicks or key strokes?

### ISSUE THREAD

**Issue by malafeev** [kwhat/jnativehook#61]
I didn't find info about support of touch screens.
Are they supported?
If yes, how does a touch screen get registered - as clicks or key strokes?

**Comment by kwhat** [comment]
Touch screens are not officially supported, however, several people have reported that they do in fact work on some platforms.  I believe most devices will register clicks for taps and keystrokes for keyboard input, but you will have to do your own testing.  If you find problems, please file a bug report.

**Comment by malafeev** [comment]
Thanks, I will test myself.
