### ISSUE TITLE
Converting from VK_ codes to VC_ codes

### ISSUE THREAD

**Issue by jbzdarkid** [kwhat/jnativehook#63]
With regards to NativeKeyEvents, and in particular the change made by [this commit.](https://github.com/kwhat/jnativehook/commit/ed0d5afc190f6e8dc2b3948c69ca7e77961a2e36#diff-3fa682501a0a58b00ce9e96841b3ff0e)

I have a program which is using the older version, and saves configuration files with key binds from the older version. I'm upgrading to the newer version of JNativeHook, but all the key binds break. How could I make a function to facilitate this switchover?

**Comment by kwhat** [comment]
I would use a 2 dimensional array as a bi-directional lookup table.  To save on space, you should be able to split the lookup table into an upper and lower half and put all the virtual codes that are > 0xFF in the upper half.  Take a look at [input_helper.c](https://github.com/kwhat/libuiohook/blob/1.0/src/windows/input_helper.c).  The keycode_scancode_table is basically what you need. The left column are the 2.0 VC codes from the class file.  Please note that you will need to change the order of these virtual codes to match an index produced by the VK_codes from the v1.x API. On the right you will need to replace all of the windows "scancodes" with the VK_codes from 1.x, ordered by the VC_codes from the 2.0 API.  You can see how the table works by looking at keycode_to_scancode() and scancode_to_keycode() functions in the same file.

**Comment by jbzdarkid** [comment]
Can't I just use keycode_to_scancode()?

**Comment by kwhat** [comment]
its not exposed to Java and it doesn't do exactly what you want .  It only translates native key codes to their virtual representation.  You will need to implement something in Java.
