### ISSUE TITLE
JNativeHook library does not follow currently selected OS language on Linux

### ISSUE THREAD

**Issue by andriy-samson** [kwhat/jnativehook#64]
**Description**
On Linux I change the keyboard layout language from default En to the second system language (example: Bulgarian). In text editor I type Bulgarian text, JNativeHookDemo continue to log all key events in English.

**Step-by-step:**
1. Start the NativeHookDemo application on Linux. The default OS language is En. 
2. Open text editor, type text in English. 
3. NativeHookDemo logs the key events in English. (OK)
4. Change the OS keyboard layout from En to another available language, in my case it is Bulgarian.
5. Type the text in Bulgarian in text editor.
6. NativeHookDemo logs all key event in English instead of Bulgarian. (ERROR)

**Tested on:**
1) --------------------------------------------------------------------------------------------------------------
OS Linux Suse:	openSUSE 13.2 (Harlequin) (x86_64) kernel 3.16.7-7-desktop
java version:	openjdk version "1.8.0_40"

2) --------------------------------------------------------------------------------------------------------------
OS Linux Mint:	Linux Mint 17.1 Rebecca Kernel: 3.13.0-37-generic x86_64 (64 bit, gcc: 4.8.2)
java version:	"1.7.0_79"

**Comment by kwhat** [comment]
Please paste the output of `locale -a`.  Thanks.

**Comment by andriy-samson** [comment]
Output on Linux Mint 17.1 Rebecca Kernel:
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```
Output on Arch-Linux 4.2.2-1-ARCH #1 SMP PREEMPT
```
C
POSIX
en_US.utf8
```

**Comment by andriy-samson** [comment]
![screenshot from 2015-10-16 22-02-36](https://cloud.githubusercontent.com/assets/3363757/10556613/3d1708ce-7456-11e5-9980-299b1ec29e5e.png)

**Comment by kwhat** [comment]
So I have a solution for this, but it is going to take a rewrite of the X11 code base and probably a dependency signature change.  Because of that change, I am going to defer this bug to 2.1.0.  I should be able to post a test build soon-ish.

**Comment by kwhat** [comment]
There is some beta code for this in the trunk but I cant seem to compile it because of a bug in xcb on arm.  I will post a beta when I can get it to build.

**Comment by kwhat** [comment]
This should be fixed in the trunk.

**Comment by andriy-samson** [comment]
Is the fix is present in one of available build? to avoid compiling process...

**Comment by kwhat** [comment]
Soon, I just updated the cross-compiler I use so I hope to make a beta build by this weekend.

**Comment by kwhat** [comment]
Should be fixed here: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/
