### ISSUE TITLE
Can't find in Maven

### ISSUE THREAD

**Issue by aequasi** [kwhat/jnativehook#65]
As the title says, can't find in maven

**Comment by kwhat** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cjnativehook ?

**Comment by aequasi** [comment]
searching for it in the intellij maven piece nets no results, and i couldnt
get it to work bypasing that either.

A. Scherer

**Comment by kwhat** [comment]
I wonder if it's related to the package / domain name mismatch.  Do you know if I can duplicate the issue with the Community edition?

**Comment by aequasi** [comment]
I am not sure... If you can't get it to duplicate, feel free to close, wouldnt be surprised if i was just doing it wrong.

**Comment by pepperonas** [comment]
Yeah, I had issues in IntelliJ using maven build, too. The package process run quite nice, I didn't get an error, but launching the .exe brought a dialog and Windows10 says "could not find Main /class".. The same happened with the .jar-file (but there was no error dialog)..
However, after modifying the "default" artifact-build in the IntelliJ-GUI the build files were working. 
To get an idea see here:
![pathintellib](https://cloud.githubusercontent.com/assets/4479946/9868699/617463f8-5b7c-11e5-9302-3e27c67ec69f.png)

**Comment by s17t** [comment]
For what is worth I am using this library from maven and intellij in they work just fine.

**Comment by himourfasy** [comment]
hi, I've a question related. when will 2.0.3 be available in maven's central repository? thanks.

**Comment by kwhat** [comment]
It should already be there...  if it isn't ill have to do an investigation this weekend.

**Comment by kwhat** [comment]
IDK What happened, the logs all look fine but the jar never made it to maven central.  2.0.3 has some potentially serious issues on windows so I may try for 2.0.4 today.

**Comment by r0s** [comment]
For anyone else stuck here, the artifact id listed in the readme is wrong, this worked for me:

    <groupId>com.1stleg</groupId>
    <artifactId>jnativehook</artifactId>

**Comment by kwhat** [comment]
Thanks I'll update it. Is the latest version up?

**Comment by r0s** [comment]
I tried 2.0.3 in the dependency version but no luck. 2.0.2 works.

**Comment by kwhat** [comment]
2.0.3 is now in maven as part of #107.  This should be resolved.
