### ISSUE TITLE
Failed to create low level event hook - Error code #48

### ISSUE THREAD

**Issue by Zetxus** [kwhat/jnativehook#66]
So the bug is that the JNativeHook can't seem to create a hook after working fine for a while. I had it integrated in my app for 3-4 days. Until today it worked perfectly but now it gets an error. I am working on a 64 bit windows 7. And I have java 1.80_60-b27. I talked with the creator (Alex Barker) about this and he told me to put an issue up so he can look it up. The problem was solved by a simple system restart but I will be trying to replicate the problem in the next days so we can finally but this bug to rest.

**Comment by kwhat** [comment]
Were you able to reproduce the problem?  Was a debugger involved?

**Comment by Zetxus** [comment]
Sorry for the late answer I just got up. So I was able to replicate this problem simply by running my app and closing it again immediately. What it does is - it registers a hook to the GlobalScreen on startup and it unregisters it on shutdown. I ran it like 20-30 times and it started giving me the error again. I didn't even have to try the debug with a breakpoint test that you wanted me to test.

**Comment by kwhat** [comment]
Does the app fully terminate each time, or does it leave a Java process running in the background?

**Comment by Zetxus** [comment]
No it actually continues to run. It has a Swing GUI and everything else works fine. It just doesn't listen for keys from the hook. I have an error dialog that pops up on a NativeException. Sometimes it pops up and sometimes it doesn't but the bug is always there until I restart the OS.

**Comment by kwhat** [comment]
If you set the log level of you app to debug we can see if the hook stops.  Just add this somewhere near the entry point.  The constructor of your primary window would be a good place.

		// Disable parent logger and set the desired level.
		logger.setUseParentHandlers(false);
		logger.setLevel(Level.ALL);

		// Add our custom formatter to a console handler.
		ConsoleHandler handler = new ConsoleHandler();
		handler.setFormatter(new LogFormatter());
		handler.setLevel(Level.ALL);
		logger.addHandler(handler);

**Comment by kwhat** [comment]
If it keeps running, how are you stopping the hook?

Can you give me an example program that and produce the problem?

**Comment by Zetxus** [comment]
If you mean how am I unregistering the hook I am doing it with a shutdown hook from java. It just unregisters it on shutdown of the program. And about that code you sent what is LogFormatter supposed to be? Did you mean Formatter? Like in the one from java.util?

**Comment by kwhat** [comment]
Sorry, I have it defined as:

	private final class LogFormatter extends Formatter {
		@Override
		public String format(LogRecord record) {
			StringBuilder line = new StringBuilder();

			line.append(new Date(record.getMillis()))
				.append(" ")
				.append(record.getLevel().getLocalizedName())
				.append(":\t")
				.append(formatMessage(record));

			if (record.getThrown() != null) {
				try {
					StringWriter sw = new StringWriter();
					PrintWriter pw = new PrintWriter(sw);
					record.getThrown().printStackTrace(pw);
					pw.close();
					line.append(sw.toString());
					sw.close();
				}
				catch (Exception ex) { /* Do Nothing */ }
			}

			return line.toString();
		}
	}

**Comment by kwhat** [comment]
This should have been enough to clean up, is that close to what you are doing?

	public void windowClosed(WindowEvent e) {
		// Clean up the native hook.
		/*
		try {
			GlobalScreen.unregisterNativeHook();
		}
		catch (NativeHookException ex) {
			ex.printStackTrace();
		}
		*/
		System.runFinalization();
		System.exit(0);
	}

**Comment by Zetxus** [comment]
Pretty much what I am doing but I don't make the System class calls because it runs when the program stops anyway so java takes care of the shutdown itself. Here's the class I'm using http://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)

**Comment by Zetxus** [comment]
This is what the logger spit out by the way sorry for the delay I didn't realize I had to add static to make the inner class work:

```
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_auto_repeat_rate [40]: SPI_GETKEYBOARDSPEED: 31.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [33]: hook_get_auto_repeat_rate(): successful. (31)
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_auto_repeat_delay [54]: SPI_GETKEYBOARDDELAY: 1.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [63]: hook_get_auto_repeat_delay(): successful. (1)
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_pointer_acceleration_multiplier [68]: SPI_GETMOUSE[2]: 1.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [93]: hook_get_pointer_acceleration_multiplier(): successful. (1)
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_pointer_acceleration_threshold [82]: SPI_GETMOUSE[0]: 6.
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_pointer_acceleration_threshold [84]: SPI_GETMOUSE[1]: 10.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [123]: hook_get_pointer_acceleration_threshold(): successful. (8)
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_pointer_sensitivity [99]: SPI_GETMOUSESPEED: 10.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [153]: hook_get_pointer_sensitivity(): successful. (10)
Sat Sep 12 20:33:57 EEST 2015 INFO:	hook_get_multi_click_time [113]: GetDoubleClickTime: 500.
Sat Sep 12 20:33:57 EEST 2015 FINE:	jni_SetProperties [183]: hook_get_multi_click_time(): successful. (500)
Sat Sep 12 20:33:57 EEST 2015 FINE:	hook_set_dispatch_proc [58]: Setting new dispatch callback to 0X0000000065E438F0.
Sat Sep 12 20:33:57 EEST 2015 SEVERE:	hook_run [724]: SetWindowsHookEx() failed! (0X7E)
Sat Sep 12 20:33:57 EEST 2015 FINE:	dispatch_event [67]: Dispatching event type 2.

```

**Comment by kwhat** [comment]
I am not sure if this will stop the error once its starts (please let me know if it does), but I *think* it will stop it from happening in the first place.  Please test.

[jnativehook-2.0.20150912.jar | uploaded via ZenHub](https://files.zenhub.io/55f465a5f1083aa3756e64ec)

**Comment by Zetxus** [comment]
This is what I get:
```
Sat Sep 12 20:52:14 EEST 2015 INFO:	Library extracted successfully: C:\Users\Zetxus\AppData\Local\Temp\JNativeHook-2.0.20150912.dll (0xD3442E3FA7435C1EE99FF64A66B57967008930C4).
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_auto_repeat_rate [39]: SPI_GETKEYBOARDSPEED: 31.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [33]: hook_get_auto_repeat_rate(): successful. (31)
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_auto_repeat_delay [53]: SPI_GETKEYBOARDDELAY: 1.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [63]: hook_get_auto_repeat_delay(): successful. (1)
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_pointer_acceleration_multiplier [67]: SPI_GETMOUSE[2]: 1.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [93]: hook_get_pointer_acceleration_multiplier(): successful. (1)
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_pointer_acceleration_threshold [81]: SPI_GETMOUSE[0]: 6.
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_pointer_acceleration_threshold [83]: SPI_GETMOUSE[1]: 10.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [123]: hook_get_pointer_acceleration_threshold(): successful. (8)
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_pointer_sensitivity [98]: SPI_GETMOUSESPEED: 10.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [153]: hook_get_pointer_sensitivity(): successful. (10)
Sat Sep 12 20:52:14 EEST 2015 INFO:	hook_get_multi_click_time [112]: GetDoubleClickTime: 500.
Sat Sep 12 20:52:14 EEST 2015 FINE:	jni_SetProperties [183]: hook_get_multi_click_time(): successful. (500)
Sat Sep 12 20:52:14 EEST 2015 FINE:	hook_set_dispatch_proc [60]: Setting new dispatch callback to 0X000000006A4C16A0.
Sat Sep 12 20:52:14 EEST 2015 SEVERE:	hook_run [771]: SetWindowsHookEx() failed! (0X7E)
Sat Sep 12 20:52:14 EEST 2015 FINE:	dispatch_event [69]: Dispatching event type 2.

```

Do you want me to restart and try replicating the problem again with this library?

**Comment by kwhat** [comment]
yes please

**Comment by Zetxus** [comment]
Ok I spent 5 minutes doing the thing I needed to do for 1 minute to bug it the last time. I am either really lucky or this bug is fixed. Thanks for reacting so quickly! If if pops up again I will contact you! Have a nice day :)

**Comment by kwhat** [comment]
Awesome, Thanks for testing.
