### ISSUE TITLE
Class implementing "NativeKeyListener" does not exit

### ISSUE THREAD

**Issue by st599** [kwhat/jnativehook#70]
I'm having issues using the library.

I have a class called TestRunner that implements NativeKeyListener. I can run the class:
`TestRunner tr = new TestRunner("test_images\\test1.png", image_filenames, image_filenames.length-1);`
`System.out.println("TEST RESULT");`

and the class does exactly what I want, but TEST RESULT is never displayed on the CLI.

What do I need to add to the following to get the class to exit?
`if(NativeKeyEvent.getKeyText(e.getKeyCode()) == "Enter")  {`
`            System.out.println("Victim has chosen index: " + currentIndex); `            
`            resultProvided = true;`
`            try {`
`                GlobalScreen.removeNativeKeyListener(this);`
`                GlobalScreen.unregisterNativeHook();`
`            } catch (NativeHookException ex) {`
`                Logger.getLogger(TestRunner.class.getName()).log(Level.SEVERE, null, ex);`
`            }`
`}`

**Comment by st599** [comment]
Also, If I call:
`TestRunner tr = new TestRunner("test_images\\test1.png", image_filenames, image_filenames.length-1);`
`tr = new TestRunner("test_images\\test1.png", image_filenames, image_filenames.length-1);`

The second call immediately exits with the same key press logged as the first.

**Comment by kwhat** [comment]
What platform are you on?

**Comment by st599** [comment]
Currently on Windows 8.

**Comment by kwhat** [comment]
I *think* this might be solved in the nightly.  Plamsa 5 has currently rendered much of my workstation useless, but when if I cant get something built, I'll post it here.

**Comment by kwhat** [comment]
See if this fixes it: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20151009.045322-17.jar

**Comment by st599** [comment]
Hi,

Still showing the same issue with the new jar file.

**Comment by kwhat** [comment]
I need more info like a complete example.
