### ISSUE TITLE
JAR creation fails

### ISSUE THREAD

**Issue by zuppiZ** [kwhat/jnativehook#71]
Hihi
I get the following error running ant:

BUILD FAILED
C:\jnativehook-master\build.xml:361: exec returned: 77

And the following output>
$ ant
\\Buildfile: C:\jnativehook-master\build.xml

init:
     [echo] Initializing local build environment...
     [echo] Project:            JNativeHook 2.0.20151010
     [echo] Debug:              false
     [echo] Java Compiler:      modern
     [echo] Java Source:        1.8
     [echo] Java Target:        1.8
     [echo] Java Include:       C:\Java\jdk1.8.0_20/include
     [echo] Java Args:
     [echo] Native Lib:         JNativeHook.dll
     [echo] Native OS:          windows
     [echo] Native Arch:        x86_64
     [echo] Native Toolchain:   gcc
     [echo] Native CFLAGS:      -O2 -pipe
     [echo] Native LDFLAGS:
[propertyfile] Creating new property file: C:\jnativehook-master\build.propertie     s

compile-java:
     [echo] Compiling Java source...
    [mkdir] Created dir: C:\jnativehook-master\bin\class\java
    [javac] Compiling 17 source files to C:\jnativehook-master\bin\class\java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\DefaultDispatchServic     e.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\DefaultLibraryLocator     .java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\GlobalScreen.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\NativeHookException.j     ava
    [javac] C:\jnativehook-master\src\java\org\jnativehook\NativeInputEvent.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\NativeLibraryLocator.     java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\NativeSystem.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\SwingDispatchService.     java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\example\NativeHookDem     o.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\keyboard\NativeKeyEve     nt.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\keyboard\NativeKeyLis     tener.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseEven     t.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseInpu     tListener.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseList     ener.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseMoti     onListener.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseWhee     lEvent.java
    [javac] C:\jnativehook-master\src\java\org\jnativehook\mouse\NativeMouseWhee     lListener.java

download-libuiohook:
     [echo] Downloading libUIOHook source...
      [get] Getting: https://github.com/kwhat/libuiohook/archive/1.0.zip
      [get] To: C:\jnativehook-master\bin\libuiohook-1.0.zip
      [get] https://github.com/kwhat/libuiohook/archive/1.0.zip moved to https:/     /codeload.github.com/kwhat/libuiohook/zip/1.0
      [get] ....................................................
      [get] ...................................................
    [unzip] Expanding: C:\jnativehook-master\bin\libuiohook-1.0.zip into C:\jnat     ivehook-master\src\libuiohook

bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...
[autoreconf] autoreconf --verbose --force --install
[autoreconf] autoreconf: Entering directory `.'
[autoreconf] autoreconf: configure.ac: not using Gettext
[autoreconf] autoreconf: running: aclocal --force -I m4
[autoreconf] autoreconf: configure.ac: tracing
[autoreconf] autoreconf: configure.ac: creating directory config
[autoreconf] autoreconf: running: libtoolize --copy --force
[autoreconf] libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
[autoreconf] libtoolize: copying file 'config/ltmain.sh'
[autoreconf] libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
[autoreconf] libtoolize: copying file 'm4/libtool.m4'
[autoreconf] libtoolize: copying file 'm4/ltoptions.m4'
[autoreconf] libtoolize: copying file 'm4/ltsugar.m4'
[autoreconf] libtoolize: copying file 'm4/ltversion.m4'
[autoreconf] libtoolize: copying file 'm4/lt~obsolete.m4'
[autoreconf] autoreconf: running: /usr/bin/autoconf --force
[autoreconf] autoreconf: running: /usr/bin/autoheader --force
[autoreconf] autoreconf: running: automake --add-missing --copy --force-missing
[autoreconf] configure.ac:63: installing 'config/ar-lib'
[autoreconf] configure.ac:62: installing 'config/compile'
[autoreconf] configure.ac:54: installing 'config/config.guess'
[autoreconf] configure.ac:54: installing 'config/config.sub'
[autoreconf] configure.ac:59: installing 'config/install-sh'
[autoreconf] configure.ac:59: installing 'config/missing'
[autoreconf] Makefile.am: installing 'config/depcomp'
[autoreconf] autoreconf: Leaving directory `.'

configure-libuiohook:
     [echo] Configuring libUIOHook source...
    [mkdir] Created dir: C:\jnativehook-master\bin\libuiohook
[configure] C:/jnativehook-master/src/libuiohook/configure --prefix=C:/jnativeho     ok-master/bin --enable-debug --enable-quiet --enable-static --disable-shared --w     ith-pic
[configure] checking build system type... x86_64-pc-msys
[configure] checking host system type... x86_64-pc-msys
[configure] checking target system type... x86_64-pc-msys
[configure] checking for a BSD-compatible install... /usr/bin/install -c
[configure] checking whether build environment is sane... yes
[configure] checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
[configure] checking for gawk... gawk
[configure] checking whether make sets $(MAKE)... yes
[configure] checking whether make supports nested variables... yes
[configure] checking for gcc... gcc
[configure] checking whether the C compiler works... no
[configure] configure: error: in `/c/jnativehook-master/bin/libuiohook':
[configure] configure: error: C compiler cannot create executables
[configure] See `config.log' for more details

BUILD FAILED
C:\jnativehook-master\build.xml:361: exec returned: 77

Total time: 35 seconds

Do you happen to know why tha's happening?
Tks & regards

**Comment by kwhat** [comment]
There is something wrong with your GCC installation.  Follow the wiki guide to install

**Comment by zuppiZ** [comment]
GCC was not installed, works now. Tks vm!
