### ISSUE TITLE
too much informaction?

### ISSUE THREAD

**Issue by SkymaxPlay** [kwhat/jnativehook#72]
Hello,
I have problem. This is my code:
try {
                //System.out.println("hooking...");
                GlobalScreen.registerNativeHook();
            } catch (NativeHookException ex) {
            }
            // Construct the example object and initialze native hook.
            GlobalScreen.addNativeKeyListener(new KeyListener());

I registering only key listener but I see too much informaction, screenshot: 
http://screenshooter.net/102522772/lhjqqbc
Why I see logs from mouse listener. This is erroes or what?
Please help.

**Comment by kwhat** [comment]
You need to setup the logger.  See the Usage section in the wiki.

**Comment by kwhat** [comment]
https://github.com/kwhat/jnativehook/blob/2.0/wiki/usage.md#logging-and-console-output

**Comment by Frankensteinn** [comment]
Hi, I have similar question... Why listeners are running without being requested? I want to use KeyListener only but every other listener(like MouseMotion) is working in background too. I turned logging off but I know that MouseMotion is still working because i can notice higher CPU usage by process with my program when I'm moving mouse.

Excuse my poor English :c

**Comment by kwhat** [comment]
Registering the native hook currently inserts a hook for all even types.  Ignoring the events will reduce load, however, they will still be delivered by the native code.  Currently, there is no way to only listen to a specific event type.  If you would like to file a new bug report, I maybe able to add a mask to the hook registration for particular event types.

**Comment by Frankensteinn** [comment]
That would be great. It's bad when unused things slow down computer :c
I'm not sure if i understood you... You want me to make new bug report about this problem?

**Comment by kwhat** [comment]
Correct
