### ISSUE TITLE
Identify source keyboard

### ISSUE THREAD

**Issue by paradoxalan** [kwhat/jnativehook#73]
This is not actually an issue, but I'm currently using jnativehook to capture keyboard input with the application in the background. Working fine. The problem is that the pc that the application is running have 2 usb keyboards and I need to to know from which one the NativeKeyEvent event is comming from. I'm digging the docs but can't find out. Can this be acomplished with jnativehook? Or I need some other library like usb4java. Or I need to use both combined? What do you think?

**Comment by kwhat** [comment]
Currently, JNativeHook does not have a way to differentiate between input sources.  That kind of functionality is a little outside of the scope of this library.  I don't think usb4java/libusb is really what you are looking for.  Try looking for a Java wrapper for hidapi or libhid like https://code.google.com/p/javahidapi/.  If one doesn't exist, it shouldn't be very hard to write as the backing libraries already exist.
