### ISSUE TITLE
the coordinate is not applied when posting native mouse event.

### ISSUE THREAD

**Issue by himourfasy** [kwhat/jnativehook#74]
hi with the coordinates for mouse event is specified, but they're not applied for dispatching.
following is the sample code. the output is different to the coordinates specified of posting.

```java
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jnativehook.GlobalScreen;
import org.jnativehook.NativeHookException;
import org.jnativehook.mouse.NativeMouseEvent;
import org.jnativehook.mouse.NativeMouseListener;

public class Test implements NativeMouseListener {

    public static void main(String[] args) {
        Logger logger = Logger.getLogger(GlobalScreen.class.getPackage().getName());
        logger.setLevel(Level.OFF);
        try {
            GlobalScreen.registerNativeHook();
        } catch (NativeHookException ex) {
            System.err.println(ex.getMessage());

            System.exit(1);
        }

        GlobalScreen.addNativeMouseListener(new Test());

        NativeMouseEvent me = new  NativeMouseEvent(
               NativeMouseEvent.NATIVE_MOUSE_PRESSED, 
               System.currentTimeMillis(), 
               0, 
               80, 900, 
               1, NativeMouseEvent.BUTTON1);
        GlobalScreen.postNativeEvent(me);
    }

    @Override
    public void nativeMouseClicked(NativeMouseEvent arg0) {

    }

    @Override
    public void nativeMousePressed(NativeMouseEvent e) {
        System.out.println(e.getX());
        System.out.println(e.getY());
    }

    @Override
    public void nativeMouseReleased(NativeMouseEvent arg0) {
    }
}
```

BTW, when will 2.0.3 be released?  thanks.

**Comment by kwhat** [comment]
What operating system are you seeing the problem on?  I was working on issue #64, but I'm not sure it is going to make it to 2.0.3 because of a dependency change.  I may push up 2.0.3 after fixing this bug and shoot for 2.1 in the coming month.

**Comment by kwhat** [comment]
So what exactly is the issue with the code above?  You get different coordinates when it clicks?

**Comment by kwhat** [comment]
Alright this should be fixed in the 2.0 branch.

**Comment by kwhat** [comment]
Give this jar a try, https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20151028.044132-23.jar

If it solves this issue, I will push 2.0.3.

**Comment by himourfasy** [comment]
your combo attack is fast :)   yes the coordinate output in listener is different from event posting. I'm using ubuntu.
I will try that nightly. and when will 2.0.3 be released?  thanks.

**Comment by himourfasy** [comment]
that doesn't work for me.
one I forgot to mention, that the position which it really clicks at is the current cursor/mouse position.
position in event posting is A, current cursor position is B, then it emulates clicking at B and gets event notification with B.


and sometimes I got this warning:
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 20 requests (20 known processed) with 0 events remaining.
what's wrong with it?

**Comment by kwhat** [comment]
Alright well that nightly only fixed the same issue on Windows ;)  As far as the XIO error, I have no idea. When does it occur?  Is there any useful debug logging output?

**Comment by kwhat** [comment]
What version of libxcb is installed?

**Comment by himourfasy** [comment]
I'm using suse  too, which is also reproducable for this posting issue.
Repository: openSUSE-13.2-Oss
Name: libxcb-devel
Version: 1.11-2.1.2
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date

**Comment by kwhat** [comment]
So the xcb issue looks like it maybe a bug in libxcb < 1.11.1, see https://bugs.freedesktop.org/show_bug.cgi?id=71338

I will look into the Linux coordinates and get back to you with a new build as soon as I have a few min.

**Comment by himourfasy** [comment]
do you how could this happen sometimes? it's not vm crash since no log output but just exit with following warning when posting native mouse event:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

**Comment by kwhat** [comment]
oh interesting... what version of java?  I may have a fix.  Can u duplicate the problem?

**Comment by himourfasy** [comment]
"1.8.0_51"
I can't stably reproduce that warning and exit issue. but will validate if better to work with latest libxcb.  thank you.

**Comment by kwhat** [comment]
Please test this nightly:  https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20151102.011322-26.jar

It should address both the button coordinates and the xcb stuff.

**Comment by himourfasy** [comment]
yes, this build works correctly for me. thank you.

**Comment by kwhat** [comment]
Awesome, thanks for testing.  I am going to do a little testing on osx and hopefully release tonight.
