### ISSUE TITLE
Mouse wheel event, coordinate issue on Windows

### ISSUE THREAD

**Issue by Bluezen** [kwhat/jnativehook#76]
I encountered an issue with posting a mouse wheel event on Windows; the mouse cursor jumps at the top of the screen and my coordinates seem to be ignored. 

Could it be that libuiohook is not looking at the right place for the mouse coordinate of a wheel event? 
```c
case EVENT_MOUSE_WHEEL:
        /* ... */
	events[events_size].mi.dx = event->data.mouse.x * (MAX_WINDOWS_COORD_VALUE / screen_width) + 1;
	events[events_size].mi.dy = event->data.mouse.y * (MAX_WINDOWS_COORD_VALUE / screen_height) + 1;
```
[ libuiohook/src/windows/post_event.c L.244](https://github.com/kwhat/libuiohook/blob/master/src/windows/post_event.c#L244)

or that jnativehook should set the coordinate on the mouse data structure instead of wheel?
```c
case org_jnativehook_mouse_NativeMouseEvent_NATIVE_MOUSE_WHEEL:
			/* ... */
	virtualEvent.data.wheel.x = (*env)->CallIntMethod(env, NativeInputEvent_obj, org_jnativehook_mouse_NativeMouseWheelEvent->parent->getX);
	virtualEvent.data.wheel.y = (*env)->CallIntMethod(env, NativeInputEvent_obj, org_jnativehook_mouse_NativeMouseWheelEvent->parent->getY);
```
[  jnativehook/src/jni/org_jnativehook_GlobalScreen.c L.173](https://github.com/kwhat/jnativehook/blob/master/src/jni/org_jnativehook_GlobalScreen.c#L173)

Or am I simply doing something wrong?

**Comment by kwhat** [comment]
I did change the way that works on Windows in 2.0.3.  You could try 2.0.2 and see if it works in that version.  Its the change around 240: https://github.com/kwhat/libuiohook/commit/7979e219ba1b22ff4ee77f475836dd8b774164d8#diff-247e84f32b1fdd36785f4afeb84f8e33R240

**Comment by Bluezen** [comment]
I am going to try 2.0.2 but one question before, at line 240 of your link, why doing :
```c
events[events_size].mi.dx = event->data.mouse.x * (65536 / GetSystemMetrics(SM_CXSCREEN)) + 1;
```
instead of
```c
events[events_size].mi.dx = event->data.wheel.x * (65536 / GetSystemMetrics(SM_CXSCREEN)) + 1;
```
It looks to me that **data.mouse.x** is not set in our *EVENT_MOUSE_WHEEL* situation and that we should check **data.wheel.x** instead, no?

**Comment by Bluezen** [comment]
With 2.0.2 the cursor doesn't jump anymore on a wheel event. However "mouse move" events are limited to a simple square at the top left edge of the screen...

**Comment by kwhat** [comment]
I didnt even notice the difference until your second post.  This should take care of it and a potential segfault that I don't think is happening.

https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20151106.044736-29.jar

**Comment by kwhat** [comment]
Thanks for the bug report!

**Comment by Bluezen** [comment]
That was it, thank you for the quick fix!
