### ISSUE TITLE
Unused events working in background

### ISSUE THREAD

**Issue by Frankensteinn** [kwhat/jnativehook#77]
Hi, excuse me my poor english :c

Like in the title. If you want to use only nativeKeyListener, your program will still use every other listener (nativeMouseMotionListener etc).
Actually, it's bad, because registering listeners, slows down your pc, mostly nativeMouseMotionListener, because it is performed very many times per second.
Who want to slow down his pc by useless actions?! :c

**Comment by kwhat** [comment]
The register native hook function should take an event mask to register for.  I am not sure how granular this can be on individual platforms.

**Comment by kwhat** [comment]
I just profiled with a native object pool and there was no measurable difference.  Ill try again with event limiting.

**Comment by kwhat** [comment]
Unfortunately, this feature does not appear to be feasible.  Most of the events listeners need to run in order to track things like modifier state.  There would be very little savings if any by trying to disable the java delivery of native events.
