### ISSUE TITLE
Capslock

### ISSUE THREAD

**Issue by neutt22** [kwhat/jnativehook#78]
How should I know if the key typed is on caps lock?

Seems like everything is caps locked already and when I output the key codes, looks like the 'a' and 'A' both = 30. It should be different right?

Thanks

**Comment by kwhat** [comment]
Use the key typed events and the key char.  The library does not support 
modifier masks yet.  It may come with 2.1.

**Comment by neutt22** [comment]
Problem solved. Thanks.
