### ISSUE TITLE
Examples out of date?

### ISSUE THREAD

**Issue by Jarzka** [kwhat/jnativehook#80]
Hi

I was trying to use the GlobalScreen class with the given examples. In the examples the class was used by calling a static method addNativeKeyListener but I noticed that in the JAR that I downloaded from Clojars the class is implemented using Singleton pattern. Are the example files out of date?

**Comment by kwhat** [comment]
They could be, but I have a feeling You maybe reading the old docs.  What URL are you using?

**Comment by Jarzka** [comment]
I was looking this example file: https://github.com/kwhat/jnativehook/blob/master/wiki/examples/Keyboard.md

**Comment by kwhat** [comment]
Those docs are correct, where are you seeing the singleton?

**Comment by Jarzka** [comment]
I used Leiningen to automatically download the compiled JAR file from using the package name shown here: https://clojars.org/org.clojars.nakkaya/jnativehook

Probably the downloaded JAR is not 100% the same version which is hosted here?

**Comment by kwhat** [comment]
It sounds like you are serving the 1.0 version.  Grab 2.0.3 from github or 2.0.2 from maven.  I'll see if I can get the site to update.

**Comment by Jarzka** [comment]
I see, my mistake. Thanks for help. :)

**Comment by AKTheKnight** [comment]
Examples are still using VK even though system has changed to VC

**Comment by kwhat** [comment]
Thanks for the bug report. Should be resolved.
