### ISSUE TITLE
Not working on different desktop where app is running

### ISSUE THREAD

**Issue by ozkr2805** [kwhat/jnativehook#86]
I use a function (user_32_wrapper.OpenDesktopA - W32API) to change between desktops on a kiosk mode app, i need to get the keyboard events on a desktop different  to the desktop where i am launching my app but the events are not arriving, if there is a way would be great to know, thanks.

**Comment by kwhat** [comment]
How are you calling OpenDesktop?  Are you using JNI or JNA and what arguments are you using?

**Comment by ozkr2805** [comment]
Hi thanks for your help, I'm using this lines:

// user_32_wrapper extends W32API 
// W32API extends StdCallLibrary
//StdCallLibrary is on jna-3.0.5.jar

----------------------------------------------------------------------------------------

user_32_wrapper user = user_32_wrapper.INSTANCE;
W32API.HANDLE hDesktop1 = user.OpenDesktopA(desktop_name, 0, true, 511); 
user.SwitchDesktop(hDesktop1);

**Comment by kwhat** [comment]
My only suggestion would be to run registerHook after user.SwitchDesktop(hDesktop1);  I can do a little more digging this weekend, but I am not holding my breath.

**Comment by kwhat** [comment]
Any luck with this?  I think what you are trying to do is prohibited by the API.

**Comment by ozkr2805** [comment]
I finally did something different, with this line: kernel_32.INSTANCE.CreateProcessA 
I can launch a process in my new desktop, so i make a little app that only listen the keyboard events and send them to the main app using sockets, not so clean but it works. thanks for your help anyway.
