### ISSUE TITLE
Arrow Keys

### ISSUE THREAD

**Issue by Flaflo** [kwhat/jnativehook#87]
The Arrow Keys are not recognized when they are pressed.

**Comment by kwhat** [comment]
Which OS and what version of the library?

**Comment by Flaflo** [comment]
Running on Windows 10 at the latest Version of your lib

**Comment by kwhat** [comment]
I cannot duplicate the problem you are describing.  Please set the [log level to debug](https://github.com/kwhat/jnativehook/wiki/ConsoleOutput) and provide the console output you are seeing when pressing the arrow keys.  Keyboard model, system language and the exact key being pressed would also help.

**Comment by Flaflo** [comment]
Any of the arrow keys are not Working, there is no console output, my keyboard is cherry MX-Board 3.0. and it doesnt matter which arrow key. btw the one one the numpad are working.

**Comment by kwhat** [comment]
Sorry for the delay, I have been experiencing trouble with my Windows installation.  I have tested the arrow keys and cannot reproduce the issue you are experiencing.  If you are not seeing "Unknown" key events with JNativeHook when you press the arrow keys, it means the library is not receiving any input events from the OS.  I suspect this keyboard isn't fully supported by Windows and requires extra software to function properly.

**Comment by kwhat** [comment]
Any luck with this issue?

**Comment by Flaflo** [comment]
nope

**Comment by TheRealSimJoo** [comment]
Same issue. Using my laptop keyboard of my Lenovo Z50 on Windows 10.

**Comment by kwhat** [comment]
@TheRealSimJoo Can you set the log level to DEBUG and see if you get any console output for the arrow keys?  I cant duplicate this issue on any system I own.

**Comment by kwhat** [comment]
@SimonBaars Any luck with a log for this bug?

**Comment by Flaflo** [comment]
@kwhat Was this issue ever reported again or can we close this?

**Comment by kwhat** [comment]
I could never duplice it.
