### ISSUE TITLE
Couldn't compile the code

### ISSUE THREAD

**Issue by KacperSiedlecki** [kwhat/jnativehook#88]
Hi
I was trying to compile current build on Windows using  MSYS, however I am getting the following error: 
"C:\Java_Native\JNativeHook\build.xml:173: Could not load definitions from resource org/jnitasks/antlib.xml. It could not be found."
I was trying to find this file on the current build but couldn't find. Is this problem with my system (ant, mysys, mingw etc. ) or did I just forgot to download something?

Greetings

**Comment by kwhat** [comment]
Hi,

You forgot the JNITasks jar for the extra ant tasks required for compiling.  See the Wiki article about compiling in the intro section:  https://github.com/kwhat/jnativehook/wiki/Compiling#introduction
