### ISSUE TITLE
Couldn't compile the code

### ISSUE THREAD

**Issue by KacperSiedlecki** [kwhat/jnativehook#89]
Hi
I was trying to compile current build on Windows using MSYS, however I am getting the following error:
[autoreconf] aclocal-1.15: error: aclocal: file '/msys64/usr/share/aclocal/xsize.m4' does not exist
[autoreconf] autoreconf: aclocal failed with exit status: 1

I found this topic: http://stackoverflow.com/questions/30814837/compilation-failure-in-jnativehook but the answers there didn't work. Did I forget some dependencies?

**Comment by kwhat** [comment]
Something is missing but I'm not sure what.  Which version of windows?

**Comment by KacperSiedlecki** [comment]
Windows 7.

**Comment by kwhat** [comment]
What shell did you compile from?

**Comment by KacperSiedlecki** [comment]
mingw64_shell.bat

**Comment by kwhat** [comment]
So /c/msys64/usr/share/aclocal/xsize.m4 should be installed by Msys2 right out of the box.  Verify that the file exists at that location.  If it does, some path got messed up somewhere in the build process.  If it does not exist, something is wrong with your installation.  Please provide the full console output for more info.

**Comment by KacperSiedlecki** [comment]
Buildfile: C:\Java_Native\JNativeHook\build.xml

init:
     [echo] Initializing local build environment...
     [echo] Project:            JNativeHook 2.0.20160207
     [echo] Debug:              false
     [echo] Java Compiler:      modern
     [echo] Java Source:        1.8
     [echo] Java Target:        1.8
     [echo] Java Include:       c:/Program Files/Java/jre1.8.0_72/include
     [echo] Java Args:          
     [echo] Native Lib:         JNativeHook.dll
     [echo] Native OS:          windows
     [echo] Native Arch:        x86_64
     [echo] Native Toolchain:   gcc
     [echo] Native CFLAGS:      -O2 -pipe
     [echo] Native LDFLAGS:     
[propertyfile] Updating property file: C:\Java_Native\JNativeHook\build.properties

compile-java:
     [echo] Compiling Java source...

download-libuiohook:

bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...
[autoreconf] autoreconf --verbose --force --install
[autoreconf] autoreconf: Entering directory `.'
[autoreconf] autoreconf: configure.ac: not using Gettext
[autoreconf] autoreconf: running: aclocal --force -I m4
[autoreconf] aclocal-1.15: error: aclocal: file '/msys64/usr/share/aclocal/xsize.m4' does not exist
[autoreconf] autoreconf: aclocal failed with exit status: 1

I typed in ant all > test.txt and this was the content of test.txt.
[link](http://i.imgur.com/E0prsXN.png) as you can see file is there.

**Comment by kwhat** [comment]
It seems like something is messed up with your mingw env but I am not sure what.  I just went through the https://github.com/kwhat/jnativehook/wiki/Compiling#windows instructions and was able to build without issue.  The best I can suggest would be running the following in the mingw64_shell.bat console:
```
pacman -Sy
pacman -Su
pacman -S autoconf automake make pkg-config libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-pkg-config
```

If that doesn't work, try reinstalling msys2 from scratch.  Delete the old folder download and reinstall.  Follow the compiling instructions in the wiki.
