### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by suewonjp** [kwhat/jnativehook#90]
Good job.

I'm currently testing JNativehook...  
I have the following error during build.

* * *

```
20:04:JNativeHook$ant all
Buildfile: /Users/bsw/test/trysomething/jnativehook-hello/JNativeHook/build.xml

init:
     [echo] Initializing local build environment...

BUILD FAILED
/Users/bsw/test/trysomething/jnativehook-hello/JNativeHook/build.xml:173: Could not load definitions from resource org/jnitasks/antlib.xml. It could not be found.
```

Where is the file _org/jnitasks/antlib.xml_ supposed to exist?

**Comment by kwhat** [comment]
Good morning, please check the introduction section of decompiling article in the wiki for instructions on adding JNI tasks to your ant classpath.

**Comment by suewonjp** [comment]
Thanks, my bad :-)

**Comment by kwhat** [comment]
yah I need to go back though and cleanup some more of the docs.  I can actually log in to Apple's website again so I may go back and fix that.  They were saying that it was like a 48 hour turn around time to reset a password... yah seriously.  Anyway i'll take a look tomorrow and fix up the wiki.

**Comment by kwhat** [comment]
Docs have been updated.
