### ISSUE TITLE
Not implemented keys from KeyEvent (especially VK_CLEAR and VK_CONTEXT_MENU)

### ISSUE THREAD

**Issue by ancient-behemoth** [kwhat/jnativehook#93]
Hi, 

I'd like to ask - are you going to implement missing keys in your **NativeKeyEvent** class that are 
available in java **KeyEvent** class?

I need to use java **KeyStroke** objects to register selected keyboard shortcuts through your library, so to achieve that I'm making mapping util between java **KeyEvent** class (which is used in **KeyStroke**) and your **NativeKeyEvent** class. (which is used in your library) But on my keyboard (I'm using Windows) there are two keys that are available in java **KeyEvent**, but are not implemented in your **NativeKeyEvent**: ***KeyEvent.VK_CLEAR*** (which is ***KeyEvent.VK_NUMPAD5*** when Num Lock is off) and ***KeyEvent.VK_CONTEXT_MENU***. (Microsoft Windows Context Menu key, which on my keboard is between right Windows key and right Ctrl, pressing it opens context menu - same as using right mouse button on focused window) Is it possible for you to implements at least those two keys? That'd help me a lot.

Thank you in advance for your answer.

**Comment by kwhat** [comment]
As far as I know, these keys should work.  It is hard to support all the keyboard models out there, but I do fix problems as people discover them.  Please post the toString() output for the key pressed events corresponding or set the library log level to debut and run it from a terminal.  The demo application will get you the toString() output and there are instructions on setting the log level in the wiki.  See https://github.com/kwhat/jnativehook/wiki/ConsoleOutput

**Comment by ancient-behemoth** [comment]
For **_KeyEvent.VK_CLEAR_** (**_KeyEvent.VK_NUMPAD5_** when Num Lock is off):
`Key Pressed: code - Undefined | 0 | char - ￿ | location - 1 | rawCode - 93 | modifiers -  | 0`
`                UNDEFINED`
`INFO: process_key_pressed [239]: Key 0 pressed. (0X5D)`
`INFO: keycode_to_unicode [651]: Using keyboard layout 0X0000000004150415.`

For **_KeyEvent.VK_CONTEXT_MENU_** (Microsoft Windows Context Menu key):
`Key Pressed: code - Undefined | 0 | char - ￿ | location - 1 | rawCode - 12 | modifiers -  | 0`
`                UNDEFINED`
`INFO: process_key_pressed [239]: Key 0 pressed. (0XC)`
`INFO: keycode_to_unicode [651]: Using keyboard layout 0X0000000004150415.`

Hope that those are the logs you're asking for.

**Comment by kwhat** [comment]
This has been resolved for windows in the trunk, however, I noticed similar problems on Linux when the number lock is disabled.  I'll close the bug after I address that issue and test OSX.

**Comment by kwhat** [comment]
vk_clear will be in 2.1

**Comment by kwhat** [comment]
Should be fixed in the trunk.  Nightly should be available soon: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/
