### ISSUE TITLE
NativeKeyListener, NativeMouseInputListener losing signals

### ISSUE THREAD

**Issue by seniorivn** [kwhat/jnativehook#94]
On Linux, sometime signals don't receives, so i can't handle some mouse clicks, or can't receive key release and my program think that key pressed after it was released.
Could somebody confirm this issue?

**Comment by kwhat** [comment]
What event dispatcher are you using?  Its probably a problem with XRecord.  I hope that a better solution will be available with Wayland.

**Comment by seniorivn** [comment]
@kwhat
```java
            GlobalScreen.registerNativeHook();
            GlobalScreen.addNativeMouseListener(this);
            GlobalScreen.addNativeKeyListener(this);
```
And you think it's impossible to fix this issue on xorg? That's sad

**Comment by kwhat** [comment]
Try enabling a [debug log level](https://github.com/kwhat/jnativehook/wiki/ConsoleOutput#logging-and-console-output) to see if the events are even recieved by the native library.  I suspect they were not received for some upstream reason.

**Comment by seniorivn** [comment]
@kwhat i tried, but i can't find the moment when it happens, i need to make log listener, that detect this, may be i will, but not now.
Thanks. Should i close this issue?

**Comment by kwhat** [comment]
Unless we can find a way to duplicate the issue or see an obvious error message, there isn't a whole lot I can do.  2.1 has had some work done to the Linux subsystem so maybe that will help with this issue.  Please reopen if there is an update.
