### ISSUE TITLE
License not clear - LGPL or GPL?

### ISSUE THREAD

**Issue by deinhofer** [kwhat/jnativehook#95]
You have added two license files one for the LGPL license and one for the GPL. Which one is valid for the combined work of the library?
I would like to add it to a commercial program which would only be possible with LGPL as I understand it.

**Comment by kwhat** [comment]
As I understand it, "derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be."  In other words, ONLY non-GPL modification of the library and static linking are prohibited.  

To answer the second part of the question, the GPL is included because it is part of the Lesser-GPL.  All Lesser-GPL licensed work is GPL compatible and not subject to the former restriction. 

I hope that clears up any confusion.

**Comment by kwhat** [comment]
I am going to add a section to the readme to help clarify the LGPL v3.

**Comment by Sabir001** [comment]
I am still confused about the license. The license is GPL3 as I can see in the repo. 
![image](https://user-images.githubusercontent.com/8401228/49419000-121c9280-f7af-11e8-8153-26f21a90343e.png)

As I understand, if I use GPL3 licensed library in my software, I will have to make my source code available.

But, readme file suggests differently. So, does this mean, if I add this library as an external library, I will not have to make source code of my software available? I have a little knowledge about dual licensing. So, pardon me if my question seems silly.

**Comment by kwhat** [comment]
The lgpl license is an extension of the gpl like ense that basically grants
you the right to link against the library.

**Comment by Sabir001** [comment]
Does that mean I can use this library without making my source available?

**Comment by kwhat** [comment]
As long as the library is used as an independent jar, and the binary
interfere remains the same, you may use the library in any commercial
software.  No open source required.

**Comment by Sabir001** [comment]
Thanks

**Comment by jd3nn1s** [comment]
@kwhat thanks for clearing up your intentions w.r.t. what is acceptable usage, as well as specifying that LGPL is one of the licenses available to be used. My understanding of licenses means it would be clearer if you specified your sole license as LGPL. The GPL license does add additional responsibilities and has a broader scope of what code needs to be released and might scare off some possible users. Additionally the LGPL has a clause that states that distributing under GPL is acceptable. Therefore the dual licensing nature is redundant as GPL projects are free to distribute under the same license.

**Comment by kwhat** [comment]
> it would be clearer if you specified your sole license as LGPL. 

I believe you must specify both licenses as the LGPL is an extension of the GPL license that grants additional usage. 

> Additionally the LGPL has a clause that states that distributing under GPL is acceptable.

Yes, the LGPL is backward compatible with GPL code, however, that doesn't make the GPL portion redundant.  The LGPL depends on the GPL for the additional usage it grants.  It is not a dual license, the LGPL is just an extension of the GPL.


From the [GPL How To Guide](https://www.gnu.org/licenses/gpl-howto.en.html)

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, **whether they are released under the GPL or LGPL, should include the text version of the GPL.** In GNU programs we conventionally put the license in a file called COPYING.

> If you are releasing your program under the GNU AGPL, use the text version of the GNU AGPL instead of the GNU GPL.

> If you are releasing your program under the Lesser GPL, **you should also include the text version of the LGPL**, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights

**Comment by jd3nn1s** [comment]
OK thanks for the clarifications.

**Comment by kwhat** [comment]
Maybe the answer here is to clean up the README license section to just state that it is LGPL which is GPL backward compatible.  I can see how that block could be confusing given how I worded it.
